/**
 * @file src/systems/worldforge/bridge/townEconomy.ts
 * Pure helpers that identify and validate town-claimed worldBusinesses for the
 * daily economy simulation.
 *
 * Town-claimed businesses are generated by World3DWrapper when the player
 * enters a Worldforge village. They carry `burgId` (the Azgaar burg index)
 * and `plotId` (the TownPlan plot index) and are registered via
 * REGISTER_WORLD_BUSINESS like any other worldBusiness.
 *
 * ECON-WIRE-1 (SPEC §6 step 5 + §8): town businesses participate in the SAME
 * NpcBusinessManager daily sim as all other NPC-owned worldBusinesses. The
 * worldReducer step 6b iterates every worldBusiness with ownerType === 'npc'
 * and calls processAllNpcBusinesses — town businesses flow through for free
 * as long as they satisfy the NpcBusinessManager contract:
 *   - ownerType === 'npc'
 *   - npcOwnerProfile present (businessSkill, financialPressure, etc.)
 *   - businessType, metrics, lastDailyReport present
 *
 * This module provides:
 *   - isTownClaimedBusiness(): predicate for town-claimed businesses
 *   - getTownBusinessKey(): stable { burgId, plotId } address
 *   - validateTownBusinessForDailySim(): contract check for daily-sim readiness
 *   - getTownBusinessLedger(): extract a human-readable ledger snapshot
 *
 * Deterministic: all generation is seeded via existing world-seed conventions
 * (World3DWrapper passes wfSeed + burgId + plotId into SeededRandom).
 */

import type { WorldBusiness } from '../../../types/business';

/**
 * Returns true if the business was generated as part of a Worldforge town and
 * carries both a burgId and a plotId. Non-town NPC businesses (faction grants,
 * standalone founding, etc.) do not set these fields.
 */
export const isTownClaimedBusiness = (business: WorldBusiness): boolean =>
    business.burgId != null && business.plotId != null;

/**
 * Stable address for a town-claimed business: the burg index and the plot
 * index within that burg's TownPlan. Returns null for non-town businesses.
 */
export interface TownBusinessKey {
    burgId: number;
    plotId: number;
}

export const getTownBusinessKey = (business: WorldBusiness): TownBusinessKey | null => {
    if (business.burgId == null || business.plotId == null) return null;
    return { burgId: business.burgId, plotId: business.plotId };
};

/**
 * Result of validating a town business for daily-sim readiness.
 * `valid === true` means the business satisfies the NpcBusinessManager
 * contract and processNpcBusinessDaily will produce a meaningful tick.
 */
export interface DailySimValidationResult {
    valid: boolean;
    missing: string[];
}

/**
 * Checks that a town-claimed business carries all fields the
 * NpcBusinessManager daily sim requires. The check is structural — it
 * does not run the sim, only verifies the preconditions.
 *
 * Required contract (see NpcBusinessManager.processNpcBusinessDaily):
 *   - ownerType === 'npc'
 *   - npcOwnerProfile present with businessSkill and financialPressure
 *   - businessType is a known BusinessType (non-empty string)
 *   - metrics object present with the five core fields
 *   - lastDailyReport present
 */
export const validateTownBusinessForDailySim = (
    business: WorldBusiness
): DailySimValidationResult => {
    const missing: string[] = [];

    if (business.ownerType !== 'npc') {
        missing.push('ownerType must be "npc"');
    }

    if (!business.npcOwnerProfile) {
        missing.push('npcOwnerProfile');
    } else {
        if (typeof business.npcOwnerProfile.businessSkill !== 'number') {
            missing.push('npcOwnerProfile.businessSkill');
        }
        if (typeof business.npcOwnerProfile.financialPressure !== 'number') {
            missing.push('npcOwnerProfile.financialPressure');
        }
        if (typeof business.npcOwnerProfile.daysUnprofitable !== 'number') {
            missing.push('npcOwnerProfile.daysUnprofitable');
        }
    }

    if (!business.businessType) {
        missing.push('businessType');
    }

    if (!business.metrics) {
        missing.push('metrics');
    } else {
        for (const field of [
            'customerSatisfaction',
            'reputation',
            'competitorPressure',
            'supplyChainHealth',
            'staffEfficiency',
        ] as const) {
            if (typeof business.metrics[field] !== 'number') {
                missing.push(`metrics.${field}`);
            }
        }
    }

    if (!business.lastDailyReport) {
        missing.push('lastDailyReport');
    }

    return { valid: missing.length === 0, missing };
};

/**
 * Extracts a short, human-readable ledger snapshot from a town business's
 * last daily report and current metrics. Useful for debug probes and the
 * proof script that advances a town a week and prints the keeper's ledger.
 */
export interface TownBusinessLedger {
    id: string;
    name: string;
    burgId: number | null;
    plotId: number | null;
    ownerType: string;
    businessType: string;
    day: number;
    revenue: number;
    costs: number;
    profit: number;
    customersSatisfied: number;
    customersLost: number;
    financialPressure: number;
    daysUnprofitable: number;
    willingnessToSell: number;
    priceMultiplier: number;
    reputation: number;
    customerSatisfaction: number;
}

export const getTownBusinessLedger = (business: WorldBusiness): TownBusinessLedger => ({
    id: business.id,
    name: business.name,
    burgId: business.burgId ?? null,
    plotId: business.plotId ?? null,
    ownerType: business.ownerType,
    businessType: business.businessType,
    day: business.lastDailyReport?.day ?? -1,
    revenue: business.lastDailyReport?.revenue ?? 0,
    costs: business.lastDailyReport?.costs ?? 0,
    profit: business.lastDailyReport?.profit ?? 0,
    customersSatisfied: business.lastDailyReport?.customersSatisfied ?? 0,
    customersLost: business.lastDailyReport?.customersLost ?? 0,
    financialPressure: business.npcOwnerProfile?.financialPressure ?? 0,
    daysUnprofitable: business.npcOwnerProfile?.daysUnprofitable ?? 0,
    willingnessToSell: business.npcOwnerProfile?.willingnessToSell ?? 0,
    priceMultiplier: business.priceMultiplier,
    reputation: business.metrics.reputation,
    customerSatisfaction: business.metrics.customerSatisfaction,
});
