/**
 * @file src/systems/worldforge/bridge/townEconomy.ts
 * Pure helpers that identify and validate town-claimed worldBusinesses for the
 * daily economy simulation.
 *
 * Town-claimed businesses are generated by World3DWrapper when the player
 * enters a Worldforge village. They carry `burgId` (the Azgaar burg index)
 * and `plotId` (the TownPlan plot index) and are registered via
 * REGISTER_WORLD_BUSINESS like any other worldBusiness.
 *
 * ECON-WIRE-1 (SPEC §6 step 5 + §8): town businesses participate in the SAME
 * NpcBusinessManager daily sim as all other NPC-owned worldBusinesses. The
 * worldReducer step 6b iterates every worldBusiness with ownerType === 'npc'
 * and calls processAllNpcBusinesses — town businesses flow through for free
 * as long as they satisfy the NpcBusinessManager contract:
 *   - ownerType === 'npc'
 *   - npcOwnerProfile present (businessSkill, financialPressure, etc.)
 *   - businessType, metrics, lastDailyReport present
 *
 * This module provides:
 *   - isTownClaimedBusiness(): predicate for town-claimed businesses
 *   - getTownBusinessKey(): stable { burgId, plotId } address
 *   - validateTownBusinessForDailySim(): contract check for daily-sim readiness
 *   - getTownBusinessLedger(): extract a human-readable ledger snapshot
 *
 * Deterministic: all generation is seeded via existing world-seed conventions
 * (World3DWrapper passes wfSeed + burgId + plotId into SeededRandom).
 */
import type { WorldBusiness } from '../../../types/business';
/**
 * Returns true if the business was generated as part of a Worldforge town and
 * carries both a burgId and a plotId. Non-town NPC businesses (faction grants,
 * standalone founding, etc.) do not set these fields.
 */
export declare const isTownClaimedBusiness: (business: WorldBusiness) => boolean;
/**
 * Stable address for a town-claimed business: the burg index and the plot
 * index within that burg's TownPlan. Returns null for non-town businesses.
 */
export interface TownBusinessKey {
    burgId: number;
    plotId: number;
}
export declare const getTownBusinessKey: (business: WorldBusiness) => TownBusinessKey | null;
/**
 * Result of validating a town business for daily-sim readiness.
 * `valid === true` means the business satisfies the NpcBusinessManager
 * contract and processNpcBusinessDaily will produce a meaningful tick.
 */
export interface DailySimValidationResult {
    valid: boolean;
    missing: string[];
}
/**
 * Checks that a town-claimed business carries all fields the
 * NpcBusinessManager daily sim requires. The check is structural — it
 * does not run the sim, only verifies the preconditions.
 *
 * Required contract (see NpcBusinessManager.processNpcBusinessDaily):
 *   - ownerType === 'npc'
 *   - npcOwnerProfile present with businessSkill and financialPressure
 *   - businessType is a known BusinessType (non-empty string)
 *   - metrics object present with the five core fields
 *   - lastDailyReport present
 */
export declare const validateTownBusinessForDailySim: (business: WorldBusiness) => DailySimValidationResult;
/**
 * Extracts a short, human-readable ledger snapshot from a town business's
 * last daily report and current metrics. Useful for debug probes and the
 * proof script that advances a town a week and prints the keeper's ledger.
 */
export interface TownBusinessLedger {
    id: string;
    name: string;
    burgId: number | null;
    plotId: number | null;
    ownerType: string;
    businessType: string;
    day: number;
    revenue: number;
    costs: number;
    profit: number;
    customersSatisfied: number;
    customersLost: number;
    financialPressure: number;
    daysUnprofitable: number;
    willingnessToSell: number;
    priceMultiplier: number;
    reputation: number;
    customerSatisfaction: number;
}
export declare const getTownBusinessLedger: (business: WorldBusiness) => TownBusinessLedger;
