// @dependencies-start
/**
 * ARCHITECTURAL ADVISORY:
 * LOCAL HELPER: This file has a small, manageable dependency footprint.
 *
 * Last Sync: 09/09/2026, 09:07:39
 * Dependents: components/Combat/CombatLog.tsx
 * Imports: 4 files
 *
 * MULTI-AGENT SAFETY:
 * If you modify exports/imports, re-run the sync tool to update this header:
 * > npx tsx misc/dev_hub/codebase-visualizer/server/index.ts --sync [this-file-path]
 * See misc/dev_hub/codebase-visualizer/VISUALIZER_README.md for more info.
 */
// @dependencies-end

/**
 * @file src/services/combatLogService.ts
 *
 * This file provides the central service for managing combat log entries, rich message channels,
 * event classification, and structured resistance/vulnerability/immunity metadata tags.
 *
 * In the Aralia combat system, events are generated by various engine hooks and commands
 * (such as attacks, spells, heals, status effects, and round transitions). This service
 * categorizes those events into user-friendly channels (all, damage, healing, conditions,
 * spells, narrative/system), attaches rich metadata tags (e.g. [Resisted: Fire (-50%)],
 * [Vulnerable: Radiant (+100%)], [Immune: Poison]), and provides filtering and tokenizing
 * utilities for UI renderers.
 *
 * Called by: CombatLog components (for filtering and pill rendering), combatLogToMessageAdapter,
 *            and combat engines.
 * Depends on: src/types/combat.ts, src/types/combatMessages.ts, src/utils/combat/resistanceUtils.ts
 */

import type { CombatLogEntry, CombatCharacter } from '../types/combat';
import {
  CombatEventClass,
  CombatMessageType,
  type CombatMessage,
  type DamageMessageData,
} from '../types/combatMessages';
import { ResistanceCalculator, type ResistanceZoneContext } from '../utils/combat/resistanceUtils';
import type { DamageType } from '../types/spells';

// ============================================================================
// Channel Types and Constants
// ============================================================================
// This section defines the message channels used to categorize combat events.
// Players can filter the combat log tab by tab (e.g., viewing only Damage or Spells).
// ============================================================================

export type CombatLogChannel =
  | 'all'
  | 'damage'
  | 'healing'
  | 'conditions'
  | 'spells'
  | 'narrative/system'
  | 'system';

/**
 * Definition for channel UI tabs in combat log components.
 */
export interface ChannelTabDefinition {
  id: CombatLogChannel;
  label: string;
  description: string;
  colorClass: string;
}

export const COMBAT_LOG_CHANNELS: ChannelTabDefinition[] = [
  { id: 'all', label: 'All', description: 'All combat events', colorClass: 'text-amber-300' },
  { id: 'damage', label: 'Damage', description: 'Attacks, hits, damage taken and dealt', colorClass: 'text-red-400' },
  { id: 'healing', label: 'Healing', description: 'Healing, regeneration, and temporary HP', colorClass: 'text-green-400' },
  { id: 'conditions', label: 'Conditions', description: 'Status effects, buffs, debuffs, and saves', colorClass: 'text-purple-400' },
  { id: 'spells', label: 'Spells', description: 'Spell casting, abilities, and concentration', colorClass: 'text-blue-400' },
  { id: 'narrative/system', label: 'System', description: 'Turns, rounds, movement, and notifications', colorClass: 'text-gray-300' },
];

// ============================================================================
// Defense Metadata and Tag Formats
// ============================================================================
// When a character resists, is vulnerable to, or is immune to a damage type,
// this section formats structured bracketed tags (e.g. "[Resisted: Fire (-50%)]").
// It also provides parsers that turn string tags into interactive badge tokens for UI.
// ============================================================================

export interface DefenseBreakdown {
  baseDamage: number;
  finalDamage: number;
  damageType: string;
  isImmune: boolean;
  isResistant: boolean;
  effectiveResistance: boolean;
  ignoresResistance: boolean;
  isVulnerable: boolean;
  tags: string[];
  tagString: string;
}

export interface DefenseTagInfo {
  tag: string;
  kind: 'resisted' | 'vulnerable' | 'immune' | 'crit' | 'save' | 'generic';
  damageType?: string;
  percentDelta?: number;
  label: string;
}

export interface ParsedMessageToken {
  text: string;
  isTag: boolean;
  tagInfo?: DefenseTagInfo;
}

/**
 * Capitalizes a damage type string for consistent tag presentation (e.g. "fire" -> "Fire").
 */
function capitalizeDamageType(type?: string): string {
  if (!type) return 'Untyped';
  return type.charAt(0).toUpperCase() + type.slice(1).toLowerCase();
}

/**
 * Formats a structured resistance metadata tag (e.g. "[Resisted: Fire (-50%)]").
 */
export function formatResistanceTag(damageType: string, percentDelta: number = -50): string {
  const cap = capitalizeDamageType(damageType);
  const sign = percentDelta > 0 ? '+' : '';
  return `[Resisted: ${cap} (${sign}${percentDelta}%)]`;
}

/**
 * Formats a structured vulnerability metadata tag (e.g. "[Vulnerable: Radiant (+100%)]").
 */
export function formatVulnerabilityTag(damageType: string, percentDelta: number = 100): string {
  const cap = capitalizeDamageType(damageType);
  const sign = percentDelta > 0 ? '+' : '';
  return `[Vulnerable: ${cap} (${sign}${percentDelta}%)]`;
}

/**
 * Formats a structured immunity metadata tag (e.g. "[Immune: Poison]").
 */
export function formatImmunityTag(damageType: string): string {
  const cap = capitalizeDamageType(damageType);
  return `[Immune: ${cap}]`;
}

/**
 * Computes the full defense breakdown and builds the corresponding metadata tags.
 */
export function calculateDefenseBreakdown(
  baseDamage: number,
  damageType: string,
  target: CombatCharacter,
  source?: CombatCharacter | null,
  isMagical?: boolean,
  zoneContext?: ResistanceZoneContext
): DefenseBreakdown {
  if (!damageType || baseDamage <= 0) {
    const raw = Math.max(0, baseDamage);
    return {
      baseDamage: raw,
      finalDamage: raw,
      damageType: damageType || 'untyped',
      isImmune: false,
      isResistant: false,
      effectiveResistance: false,
      ignoresResistance: false,
      isVulnerable: false,
      tags: [],
      tagString: '',
    };
  }

  const breakdown = ResistanceCalculator.getDefenseBreakdown(
    baseDamage,
    damageType as DamageType,
    target,
    source,
    isMagical,
    zoneContext
  );

  return {
    baseDamage: breakdown.baseDamage,
    finalDamage: breakdown.finalDamage,
    damageType,
    isImmune: breakdown.isImmune,
    isResistant: breakdown.hasResistance,
    effectiveResistance: breakdown.effectiveResistance,
    ignoresResistance: breakdown.ignoresResistance,
    isVulnerable: breakdown.hasVulnerability,
    tags: breakdown.tags,
    tagString: breakdown.tags.join(' '),
  };
}

/**
 * Parses defense tags from a message string.
 */
export function parseDefenseTags(messageText: string): DefenseTagInfo[] {
  const tags: DefenseTagInfo[] = [];
  const tagRegex = /\[([^\]]+)\]/g;
  let match: RegExpExecArray | null;

  while ((match = tagRegex.exec(messageText)) !== null) {
    const fullTag = match[0];
    const inner = match[1];

    if (/^Resisted:\s*([a-zA-Z]+)(?:\s*\(([+-]?\d+)%\))?/i.test(inner)) {
      const resistMatch = inner.match(/^Resisted:\s*([a-zA-Z]+)(?:\s*\(([+-]?\d+)%\))?/i);
      tags.push({
        tag: fullTag,
        kind: 'resisted',
        damageType: resistMatch?.[1],
        percentDelta: resistMatch?.[2] ? parseInt(resistMatch[2], 10) : -50,
        label: inner,
      });
    } else if (/^Vulnerable:\s*([a-zA-Z]+)(?:\s*\(([+-]?\d+)%\))?/i.test(inner)) {
      const vulnMatch = inner.match(/^Vulnerable:\s*([a-zA-Z]+)(?:\s*\(([+-]?\d+)%\))?/i);
      tags.push({
        tag: fullTag,
        kind: 'vulnerable',
        damageType: vulnMatch?.[1],
        percentDelta: vulnMatch?.[2] ? parseInt(vulnMatch[2], 10) : 100,
        label: inner,
      });
    } else if (/^Immune:\s*([a-zA-Z]+)/i.test(inner)) {
      const immuneMatch = inner.match(/^Immune:\s*([a-zA-Z]+)/i);
      tags.push({
        tag: fullTag,
        kind: 'immune',
        damageType: immuneMatch?.[1],
        label: inner,
      });
    } else if (/^(?:Crit|Critical!|Critical Hit)/i.test(inner)) {
      tags.push({
        tag: fullTag,
        kind: 'crit',
        label: inner,
      });
    } else if (/^Save\s+DC/i.test(inner)) {
      tags.push({
        tag: fullTag,
        kind: 'save',
        label: inner,
      });
    } else {
      tags.push({
        tag: fullTag,
        kind: 'generic',
        label: inner,
      });
    }
  }

  return tags;
}

/**
 * Splits a message into string segments and tag tokens for rich pill rendering.
 */
export function tokenizeMessageWithTags(messageText: string): ParsedMessageToken[] {
  const tokens: ParsedMessageToken[] = [];
  const tagRegex = /\[([^\]]+)\]/g;
  let lastIndex = 0;
  let match: RegExpExecArray | null;

  while ((match = tagRegex.exec(messageText)) !== null) {
    if (match.index > lastIndex) {
      tokens.push({
        text: messageText.substring(lastIndex, match.index),
        isTag: false,
      });
    }

    const fullTag = match[0];
    const inner = match[1];
    let tagInfo: DefenseTagInfo;

    if (/^Resisted:\s*([a-zA-Z]+)(?:\s*\(([+-]?\d+)%\))?/i.test(inner)) {
      const resistMatch = inner.match(/^Resisted:\s*([a-zA-Z]+)(?:\s*\(([+-]?\d+)%\))?/i);
      tagInfo = {
        tag: fullTag,
        kind: 'resisted',
        damageType: resistMatch?.[1],
        percentDelta: resistMatch?.[2] ? parseInt(resistMatch[2], 10) : -50,
        label: inner,
      };
    } else if (/^Vulnerable:\s*([a-zA-Z]+)(?:\s*\(([+-]?\d+)%\))?/i.test(inner)) {
      const vulnMatch = inner.match(/^Vulnerable:\s*([a-zA-Z]+)(?:\s*\(([+-]?\d+)%\))?/i);
      tagInfo = {
        tag: fullTag,
        kind: 'vulnerable',
        damageType: vulnMatch?.[1],
        percentDelta: vulnMatch?.[2] ? parseInt(vulnMatch[2], 10) : 100,
        label: inner,
      };
    } else if (/^Immune:\s*([a-zA-Z]+)/i.test(inner)) {
      const immuneMatch = inner.match(/^Immune:\s*([a-zA-Z]+)/i);
      tagInfo = {
        tag: fullTag,
        kind: 'immune',
        damageType: immuneMatch?.[1],
        label: inner,
      };
    } else if (/^(?:Crit|Critical!|Critical Hit)/i.test(inner)) {
      tagInfo = {
        tag: fullTag,
        kind: 'crit',
        label: inner,
      };
    } else if (/^Save\s+DC/i.test(inner)) {
      tagInfo = {
        tag: fullTag,
        kind: 'save',
        label: inner,
      };
    } else {
      tagInfo = {
        tag: fullTag,
        kind: 'generic',
        label: inner,
      };
    }

    tokens.push({
      text: fullTag,
      isTag: true,
      tagInfo,
    });

    lastIndex = tagRegex.lastIndex;
  }

  if (lastIndex < messageText.length) {
    tokens.push({
      text: messageText.substring(lastIndex),
      isTag: false,
    });
  }

  return tokens;
}

// ============================================================================
// Event Classification and Channel Filtering
// ============================================================================
// This section sorts both legacy CombatLogEntry and rich CombatMessage objects
// into their respective channels based on their type, metadata, and message contents.
// ============================================================================

/**
 * Classifies a CombatLogEntry into one of the user-facing channels.
 */
export function classifyLogEntryChannel(entry: CombatLogEntry): CombatLogChannel {
  // If the record has an explicit channel tag in data, check it first
  if (entry.data?.channel) {
    const raw = entry.data.channel.toLowerCase();
    if (raw === 'damage') return 'damage';
    if (raw === 'heal' || raw === 'healing') return 'healing';
    if (raw === 'status' || raw === 'condition' || raw === 'conditions') return 'conditions';
    if (raw === 'spell' || raw === 'spells' || raw === 'summon') return 'spells';
    if (raw === 'system' || raw === 'narrative' || raw === 'narrative/system') return 'narrative/system';
  }

  switch (entry.type) {
    case 'damage':
      return 'damage';

    case 'heal':
      return 'healing';

    case 'status':
      return 'conditions';

    case 'summon':
      return 'spells';

    case 'action': {
      const msg = entry.message.toLowerCase();
      // Attack hits / misses / opportunity attacks go to damage channel
      if (msg.includes('attack') || msg.includes('strike') || msg.includes('hits') || msg.includes('misses')) {
        return 'damage';
      }
      // Spells and abilities go to spells channel
      if (msg.includes('casts') || msg.includes('spell') || msg.includes('sustains') || msg.includes('ability')) {
        return 'spells';
      }
      return 'spells';
    }

    case 'movement':
    case 'turn_start':
    case 'turn_end':
      return 'narrative/system';

    default:
      return 'narrative/system';
  }
}

/**
 * Classifies a rich CombatMessage into one of the user-facing channels.
 */
export function classifyMessageChannel(message: CombatMessage): CombatLogChannel {
  switch (message.type) {
    case CombatMessageType.DAMAGE_DEALT:
    case CombatMessageType.DAMAGE_TAKEN:
    case CombatMessageType.CRITICAL_HIT:
    case CombatMessageType.KILLING_BLOW:
    case CombatMessageType.MISSED_ATTACK:
    case CombatMessageType.ENVIRONMENTAL_DAMAGE:
      return 'damage';

    case CombatMessageType.HEALING_RECEIVED:
    case CombatMessageType.RESOURCE_GAINED:
      return 'healing';

    case CombatMessageType.STATUS_APPLIED:
    case CombatMessageType.STATUS_RESISTED:
    case CombatMessageType.STATUS_EXPIRED:
    case CombatMessageType.CONDITION_CLEARED:
      return 'conditions';

    case CombatMessageType.SPELL_CAST:
    case CombatMessageType.SPELL_RESISTED:
    case CombatMessageType.SPELL_IMMUNE:
    case CombatMessageType.ABILITY_USED:
    case CombatMessageType.RESOURCE_SPENT:
      return 'spells';

    case CombatMessageType.TURN_START:
    case CombatMessageType.ROUND_START:
    case CombatMessageType.COMBAT_ENTER:
    case CombatMessageType.COMBAT_EXIT:
    case CombatMessageType.LEVEL_UP:
    case CombatMessageType.MILESTONE_ACHIEVED:
    case CombatMessageType.STREAK_CONTINUED:
    case CombatMessageType.DEFENDED:
    default:
      return 'narrative/system';
  }
}

/**
 * Filters a list of CombatLogEntry items based on the active channel tab.
 */
export function filterLogEntriesByChannel(
  entries: CombatLogEntry[],
  channel: CombatLogChannel
): CombatLogEntry[] {
  if (channel === 'all') return entries;
  const targetChannel = channel === 'system' ? 'narrative/system' : channel;
  return entries.filter(entry => {
    const entryChannel = classifyLogEntryChannel(entry);
    return entryChannel === targetChannel;
  });
}

/**
 * Filters a list of CombatMessage items based on the active channel tab.
 */
export function filterMessagesByChannel(
  messages: CombatMessage[],
  channel: CombatLogChannel
): CombatMessage[] {
  if (channel === 'all') return messages;
  const targetChannel = channel === 'system' ? 'narrative/system' : channel;
  return messages.filter(message => {
    const messageChannel = classifyMessageChannel(message);
    return messageChannel === targetChannel;
  });
}

/**
 * Calculates item counts per channel for UI badge counters.
 */
export function getChannelCounts(
  entries: CombatLogEntry[]
): Record<CombatLogChannel, number> {
  const counts: Record<CombatLogChannel, number> = {
    all: entries.length,
    damage: 0,
    healing: 0,
    conditions: 0,
    spells: 0,
    'narrative/system': 0,
    system: 0,
  };

  for (const entry of entries) {
    const channel = classifyLogEntryChannel(entry);
    counts[channel]++;
  }

  counts.system = counts['narrative/system'];
  return counts;
}

// ============================================================================
// CombatLogService Class
// ============================================================================
// A centralized service class providing static and instance methods for
// log dispatching, channel filtering, and defense tag formatting.
// ============================================================================

export class CombatLogService {
  /**
   * Builds an enriched combat log entry with structured defense metadata.
   */
  static createDamageLogEntry(params: {
    caster?: CombatCharacter | null;
    target: CombatCharacter;
    baseDamage: number;
    damageType: string;
    sourceName?: string;
    isCritical?: boolean;
    isDeath?: boolean;
    zoneContext?: ResistanceZoneContext;
  }): CombatLogEntry {
    const {
      caster,
      target,
      baseDamage,
      damageType,
      sourceName = 'Attack',
      isCritical = false,
      isDeath = false,
      zoneContext,
    } = params;

    const breakdown = calculateDefenseBreakdown(
      baseDamage,
      damageType,
      target,
      caster,
      undefined,
      zoneContext
    );

    const critText = isCritical ? ' [Critical!]' : '';
    const tagSuffix = breakdown.tagString ? ` ${breakdown.tagString}` : '';
    const attackerName = caster?.name ?? 'An attacker';
    const deathText = isDeath ? ' and is defeated!' : '';

    const message = `${target.name} takes ${breakdown.finalDamage} ${damageType} damage from ${attackerName} (${sourceName})${critText}${tagSuffix}${deathText}`;

    // CMB-GAP-003: this emitter knows exactly what happened, so it states the event class
    // rather than leaving the adapter to recover it from the sentence it just built.
    const eventClass = isDeath
      ? CombatEventClass.KILL
      : isCritical
        ? CombatEventClass.CRITICAL_DAMAGE
        : CombatEventClass.DAMAGE;

    return {
      id: `log_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      timestamp: Date.now(),
      type: 'damage',
      eventClass,
      message,
      characterId: target.id,
      targetIds: [target.id],
      data: {
        damage: baseDamage,
        damageAmount: breakdown.finalDamage,
        damageType,
        damageDealt: breakdown.finalDamage,
        source: caster?.name,
        sourceCharacterId: caster?.id,
        targetCharacterId: target.id,
        isCrit: isCritical,
        isCritical,
        isDeath,
        isResisted: breakdown.isResistant,
        resistanceApplied: breakdown.effectiveResistance,
        resistedDamageType: breakdown.effectiveResistance ? damageType : undefined,
        isVulnerable: breakdown.isVulnerable,
        vulnerabilityApplied: breakdown.isVulnerable,
        vulnerableDamageType: breakdown.isVulnerable ? damageType : undefined,
        isImmune: breakdown.isImmune,
        immunityApplied: breakdown.isImmune,
        immuneDamageType: breakdown.isImmune ? damageType : undefined,
        defenseTags: breakdown.tags,
        channel: 'damage',
      },
    };
  }

  /**
   * Helper to classify a log entry into its channel.
   */
  static classifyChannel(entry: CombatLogEntry): CombatLogChannel {
    return classifyLogEntryChannel(entry);
  }

  /**
   * Helper to filter log entries.
   */
  static filterByChannel(entries: CombatLogEntry[], channel: CombatLogChannel): CombatLogEntry[] {
    return filterLogEntriesByChannel(entries, channel);
  }

  /**
   * Helper to tokenize a message for rich tag rendering.
   */
  static tokenize(message: string): ParsedMessageToken[] {
    return tokenizeMessageWithTags(message);
  }
}
