import fs from 'fs';
import path from 'path';

/**
 * Local Vite API for the Aralia Atlas explorer.
 *
 * The browser cannot import `.agent/atlas` directly because that folder is
 * ignored runtime state. This plugin exposes the latest Knowledge Tree export,
 * plan-health export, and reconciliation report through read-only local routes.
 *
 * Called by: vite.config.ts during local dev-server startup
 * Depends on: `.agent/atlas` files generated by `npm run atlas -- reconcile`
 */

// ============================================================================
// File And Response Helpers
// ============================================================================
// This section resolves the ignored Atlas runtime paths and provides small JSON
// response helpers for the three browser endpoints.
// ============================================================================

const ATLAS_ROOT = path.resolve(process.cwd(), '.agent', 'atlas');
const KNOWLEDGE_TREE_PATH = path.join(ATLAS_ROOT, 'exports', 'knowledge-tree.json');
const PLAN_HEALTH_PATH = path.join(ATLAS_ROOT, 'exports', 'plan-health.json');
const REPORT_DIR = path.join(ATLAS_ROOT, 'reports');

function sendJson(res: any, status: number, data: unknown): void {
  res.writeHead(status, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
  res.end(JSON.stringify(data));
}

function readJsonFile(filePath: string): unknown {
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
}

function latestReportPath(): string | null {
  if (!fs.existsSync(REPORT_DIR)) return null;

  const reports = fs.readdirSync(REPORT_DIR)
    .filter((file) => file.endsWith('-reconciliation.md'))
    .sort();

  return reports.length ? path.join(REPORT_DIR, reports[reports.length - 1]) : null;
}

// ============================================================================
// Vite Middleware
// ============================================================================
// This section serves read-only Atlas data. If the export is missing, the
// response names the reconciliation command instead of leaving the page blank.
// ============================================================================

export const atlasApiManager = () => ({
  name: 'atlas-api-manager',
  configureServer(server: any) {
    server.middlewares.use((req: any, res: any, next: any) => {
      const urlPath = (req.url || '').split('?')[0];

      if (urlPath === '/api/atlas/knowledge-tree') {
        if (!fs.existsSync(KNOWLEDGE_TREE_PATH)) {
          sendJson(res, 404, {
            error: 'Atlas export missing',
            message: 'Run `npm run atlas -- reconcile --target F:\\Repos\\Aralia` before opening the visual explorer.',
          });
          return;
        }
        sendJson(res, 200, readJsonFile(KNOWLEDGE_TREE_PATH));
        return;
      }

      if (urlPath === '/api/atlas/plan-health') {
        if (!fs.existsSync(PLAN_HEALTH_PATH)) {
          sendJson(res, 404, { error: 'Atlas plan-health export missing' });
          return;
        }
        sendJson(res, 200, readJsonFile(PLAN_HEALTH_PATH));
        return;
      }

      if (urlPath === '/api/atlas/latest-report') {
        const reportPath = latestReportPath();
        if (!reportPath) {
          sendJson(res, 404, { error: 'Atlas report missing' });
          return;
        }
        sendJson(res, 200, {
          path: reportPath,
          content: fs.readFileSync(reportPath, 'utf-8'),
        });
        return;
      }

      next();
    });
  },
});
