import fs from 'fs';
import path from 'path';
import { execFileSync } from 'child_process';

/**
 * Local Vite API for the Aralia Atlas explorer.
 *
 * The browser cannot import `.agent/atlas` directly because that folder is
 * ignored runtime state. This plugin exposes the latest Knowledge Tree export,
 * plan-health export, and reconciliation report through read-only local routes.
 *
 * Called by: vite.config.ts during local dev-server startup
 * Depends on: `.agent/atlas` files generated by `npm run atlas -- reconcile`
 */

// ============================================================================
// File And Response Helpers
// ============================================================================
// This section resolves the ignored Atlas runtime paths and provides small JSON
// response helpers for the three browser endpoints.
// ============================================================================

const ATLAS_ROOT = path.resolve(process.cwd(), '.agent', 'atlas');
const KNOWLEDGE_TREE_PATH = path.join(ATLAS_ROOT, 'exports', 'knowledge-tree.json');
const PLAN_HEALTH_PATH = path.join(ATLAS_ROOT, 'exports', 'plan-health.json');
const REPORT_DIR = path.join(ATLAS_ROOT, 'reports');
const BACKLOG_SNAPSHOT_PATH = path.resolve(process.cwd(), 'docs', 'tasks', 'backlog-retirement', 'WALKED_FILE_SNAPSHOT.json');
const BACKLOG_MARKER_PREFIX = '<!-- aralia-backlog-walked:';
const BACKLOG_RECENT_LIMIT = 8;

interface BacklogSnapshotEntry {
  backlogFile: string;
  walkState: string;
  exists?: boolean;
  kind?: string;
  modifiedUtc?: string | null;
  sha256?: string | null;
}

interface BacklogSnapshot {
  entries?: BacklogSnapshotEntry[];
}

function sendJson(res: any, status: number, data: unknown): void {
  res.writeHead(status, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
  res.end(JSON.stringify(data));
}

function readJsonFile(filePath: string): unknown {
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
}

function toRepoPath(absolutePath: string): string {
  return path.relative(process.cwd(), absolutePath).replace(/\\/g, '/');
}

function shouldSkipMarkdownDirectory(absolutePath: string): boolean {
  const directoryName = path.basename(absolutePath);
  const repoPath = toRepoPath(absolutePath);
  return ['.git', 'node_modules', 'dist', 'build', '.vite', '.cache', 'coverage'].includes(directoryName)
    || repoPath.startsWith('.agent/scratch/')
    || repoPath.startsWith('.agent/roadmap-local/tooling_state');
}

function walkMarkdownFiles(rootPath: string): string[] {
  const files: string[] = [];

  function visit(currentPath: string): void {
    if (shouldSkipMarkdownDirectory(currentPath)) return;

    const stat = fs.statSync(currentPath);
    if (stat.isDirectory()) {
      for (const child of fs.readdirSync(currentPath)) {
        visit(path.join(currentPath, child));
      }
      return;
    }

    if (stat.isFile() && currentPath.endsWith('.md')) {
      files.push(currentPath);
    }
  }

  if (fs.existsSync(rootPath)) visit(rootPath);
  return files.sort();
}

function readBacklogCandidates(): unknown {
  const output = execFileSync(
    process.execPath,
    ['scripts/audits/mark-backlog-walked.cjs', '--candidates', '--root', 'docs', '--limit', '12', '--json'],
    { cwd: process.cwd(), encoding: 'utf-8', timeout: 10_000 },
  );
  return JSON.parse(output);
}

function readRecentBacklogActivity(snapshot: BacklogSnapshot): unknown[] {
  const entries = Array.isArray(snapshot?.entries) ? snapshot.entries : [];

  // The ledger is append-oriented, so the newest concrete review rows are near
  // the end. Skip the ledger's self-reference and bucket globs because they are
  // control state, not files the user needs to see as "last worked".
  return entries
    .filter((entry) => typeof entry?.backlogFile === 'string')
    .filter((entry) => !entry.backlogFile.includes('*'))
    .filter((entry) => entry.backlogFile !== 'docs/tasks/backlog-retirement/RETIREMENT_LEDGER.md')
    .slice()
    .reverse()
    .slice(0, BACKLOG_RECENT_LIMIT)
    .map((entry) => ({
      path: entry.backlogFile,
      walkState: entry.walkState,
      exists: Boolean(entry.exists),
      kind: entry.kind,
      modifiedUtc: entry.modifiedUtc ?? null,
      sha256: entry.sha256 ?? null,
    }));
}

function readBacklogRetirementState(): unknown {
  if (!fs.existsSync(BACKLOG_SNAPSHOT_PATH)) {
    return {
      available: false,
      message: 'Run `npm run backlog:snapshot` before opening backlog-retirement progress.',
    };
  }

  const docsMarkdown = walkMarkdownFiles(path.resolve(process.cwd(), 'docs'));
  const markedMarkdown = docsMarkdown.filter((filePath) => fs.readFileSync(filePath, 'utf-8').includes(BACKLOG_MARKER_PREFIX));
  const snapshot = readJsonFile(BACKLOG_SNAPSHOT_PATH);

  return {
    available: true,
    generatedAt: new Date().toISOString(),
    snapshot,
    markerSummary: {
      totalMarkdown: docsMarkdown.length,
      markedMarkdown: markedMarkdown.length,
      missingMarkdown: docsMarkdown.length - markedMarkdown.length,
    },
    recentActivity: readRecentBacklogActivity(snapshot),
    candidates: readBacklogCandidates(),
  };
}

function latestReportPath(): string | null {
  if (!fs.existsSync(REPORT_DIR)) return null;

  const reports = fs.readdirSync(REPORT_DIR)
    .filter((file) => file.endsWith('-reconciliation.md'))
    .sort();

  return reports.length ? path.join(REPORT_DIR, reports[reports.length - 1]) : null;
}

// ============================================================================
// Vite Middleware
// ============================================================================
// This section serves read-only Atlas data. If the export is missing, the
// response names the reconciliation command instead of leaving the page blank.
// ============================================================================

export const atlasApiManager = () => ({
  name: 'atlas-api-manager',
  configureServer(server: any) {
    server.middlewares.use((req: any, res: any, next: any) => {
      const urlPath = (req.url || '').split('?')[0];

      if (urlPath === '/api/atlas/knowledge-tree') {
        if (!fs.existsSync(KNOWLEDGE_TREE_PATH)) {
          sendJson(res, 404, {
            error: 'Atlas export missing',
            message: 'Run `npm run atlas -- reconcile --target F:\\Repos\\Aralia` before opening the visual explorer.',
          });
          return;
        }
        sendJson(res, 200, readJsonFile(KNOWLEDGE_TREE_PATH));
        return;
      }

      if (urlPath === '/api/atlas/plan-health') {
        if (!fs.existsSync(PLAN_HEALTH_PATH)) {
          sendJson(res, 404, { error: 'Atlas plan-health export missing' });
          return;
        }
        sendJson(res, 200, readJsonFile(PLAN_HEALTH_PATH));
        return;
      }

      if (urlPath === '/api/atlas/latest-report') {
        const reportPath = latestReportPath();
        if (!reportPath) {
          sendJson(res, 404, { error: 'Atlas report missing' });
          return;
        }
        sendJson(res, 200, {
          path: reportPath,
          content: fs.readFileSync(reportPath, 'utf-8'),
        });
        return;
      }

      if (urlPath === '/api/atlas/backlog-retirement') {
        try {
          sendJson(res, 200, readBacklogRetirementState());
        } catch (error) {
          sendJson(res, 500, {
            error: 'Atlas backlog-retirement state failed to load',
            message: error instanceof Error ? error.message : String(error),
          });
        }
        return;
      }

      next();
    });
  },
});
