/**
 * ARCHITECTURAL ADVISORY:
 * LOCAL HELPER: This file has a small, manageable dependency footprint.
 *
 * Last Sync: 09/06/2026, 02:11:07
 * Dependents: components/Submap/SubmapPane.tsx, components/layout/GameLayout.tsx
 * Imports: 6 files
 *
 * MULTI-AGENT SAFETY:
 * If you modify exports/imports, re-run the sync tool to update this header:
 * > npx tsx misc/dev_hub/codebase-visualizer/server/index.ts --sync [this-file-path]
 * See misc/dev_hub/codebase-visualizer/VISUALIZER_README.md for more info.
 */
/**
 * @file ActionPane/index.tsx
 * This component displays available actions to the player.
 * It includes standard actions (Talk, Take, Move), Oracle interaction,
 * and dynamic actions generated by Gemini (e.g. from Look Around).
 *
 * It is now structured to separate UI components (ActionButton, SystemMenu)
 * and logic (useActionGeneration) from the main view.
 */
import React from 'react';
import { Location, Action, NPC, Item, PlayerCharacter } from '../../types';
interface ActionPaneProps {
    currentLocation: Location;
    npcsInLocation: NPC[];
    itemsInLocation: Item[];
    party: PlayerCharacter[];
    onAction: (action: Action) => void;
    disabled: boolean;
    geminiGeneratedActions: Action[] | null;
    isDevModeEnabled: boolean;
    unreadDiscoveryCount: number;
    autoSaveEnabled?: boolean;
    hasNewRateLimitError: boolean;
}
declare const ActionPane: React.FC<ActionPaneProps>;
export default ActionPane;
