/**
 * @file ActionPane/index.tsx
 * This component displays available actions to the player.
 * It includes standard actions (Talk, Take, Move), Oracle interaction,
 * and dynamic actions generated by Gemini (e.g. from Look Around).
 *
 * It is now structured to separate UI components (ActionButton, SystemMenu)
 * and logic (useActionGeneration) from the main view.
 */
import React, { useState, useEffect, useRef } from 'react';
import { AnimatePresence } from 'framer-motion';
import { Location, Action, NPC, Item, PlayerCharacter, HitPointDiceSpendMap } from '../../types';
import { ActionButton } from './ActionButton';
import { useActionGeneration } from './useActionGeneration';
import { SystemMenu } from './SystemMenu';
import RestModal from '../ui/RestModal';
import { UI_ID } from '../../styles/uiIds';

interface ActionPaneProps {
  currentLocation: Location;
  npcsInLocation: NPC[];
  itemsInLocation: Item[];
  party: PlayerCharacter[];
  onAction: (action: Action) => void;
  disabled: boolean;
  geminiGeneratedActions: Action[] | null;
  isDevDummyActive: boolean;
  isDevModeEnabled: boolean;
  unreadDiscoveryCount: number;
  autoSaveEnabled?: boolean;

  hasNewRateLimitError: boolean;
  subMapCoordinates?: { x: number; y: number };
  worldSeed?: number;
}

const ActionPane: React.FC<ActionPaneProps> = ({
  currentLocation,
  npcsInLocation,
  itemsInLocation,
  onAction,
  disabled,
  geminiGeneratedActions,
  isDevDummyActive,
  isDevModeEnabled,
  unreadDiscoveryCount,
  autoSaveEnabled = true,
  party,

  hasNewRateLimitError,
  subMapCoordinates,
  worldSeed,
}) => {
  const oracleInputRef = useRef<HTMLInputElement | null>(null);
  const [isOracleInputVisible, setIsOracleInputVisible] = useState(false);
  const [oracleQuery, setOracleQuery] = useState('');
  // Tracks whether the short-rest modal is open so we can collect Hit Dice spend.
  const [isRestModalOpen, setIsRestModalOpen] = useState(false);

  const { generalActions } = useActionGeneration({
    currentLocation,
    npcsInLocation,
    itemsInLocation,
    subMapCoordinates,
    worldSeed
  });

  useEffect(() => {
    if (isOracleInputVisible) {
      oracleInputRef.current?.focus();
    }
  }, [isOracleInputVisible]);

  const handleAskOracleClick = () => setIsOracleInputVisible(true);
  const handleOracleSubmit = () => {
    if (oracleQuery.trim() && !disabled) {
      onAction({ type: 'ask_oracle', label: 'Ask the Oracle', payload: { query: oracleQuery.trim() } });
      setOracleQuery('');
      setIsOracleInputVisible(false);
    }
  };

  const handleShortRestConfirm = (spend: HitPointDiceSpendMap) => {
    // Dispatch the SHORT_REST action with a per-character spend map.
    onAction({ type: 'SHORT_REST', label: 'Short Rest', payload: { hitPointDiceSpend: spend } });
  };

  const handleShortRestClick = (_action: Action) => {
    setIsRestModalOpen(true);
  };

  return (
    <div id={UI_ID.ACTION_PANE} data-testid={UI_ID.ACTION_PANE} className="bg-gray-800 p-4 rounded-lg shadow-xl border border-gray-700">
      <h2 className="text-xl font-bold text-amber-400 mb-4 border-b-2 border-amber-500 pb-2">Actions</h2>

      {/* Top Row: Oracle, Analyze */}
      <div className="mb-4 grid grid-cols-1 gap-2 sm:grid-cols-2">
        {!isOracleInputVisible && (
          <ActionButton
            action={{ type: 'custom', label: 'Ask the Oracle' }}
            onClick={handleAskOracleClick}
            disabled={disabled}
          />
        )}
        <ActionButton
          action={{ type: 'ANALYZE_SITUATION', label: 'Survey Surroundings' }}
          onClick={onAction}
          disabled={disabled}
        />
      </div>

      {/* Oracle Input */}
      {isOracleInputVisible && (
        <div className="mb-4 p-3 border border-purple-500 rounded-lg bg-gray-700/50">
          <input
            type="text"
            value={oracleQuery}
            onChange={(e) => setOracleQuery(e.target.value)}
            placeholder="Ask your question..."
            className="w-full px-3 py-2 bg-gray-900 border border-gray-600 rounded-md text-gray-200 focus:ring-1 focus:ring-purple-500 outline-none mb-2"
            onKeyDown={(e) => e.key === 'Enter' && handleOracleSubmit()}
            ref={oracleInputRef}
            aria-label="Ask the Oracle"
          />
          <div className="flex gap-2">
            <button onClick={handleOracleSubmit} disabled={disabled || !oracleQuery.trim()} className="flex-1 bg-green-600 text-white py-1 rounded hover:bg-green-500">Submit</button>
            <button onClick={() => setIsOracleInputVisible(false)} className="flex-1 bg-gray-500 text-white py-1 rounded hover:bg-gray-400">Cancel</button>
          </div>
        </div>
      )}

      {/* Gemini Generated Actions */}
      <AnimatePresence>
        {geminiGeneratedActions && geminiGeneratedActions.length > 0 && (
          <div className="mb-4">
            <h3 className="text-sm font-semibold text-teal-400 mb-2">Suggested Actions</h3>
            <div className="grid grid-cols-1 gap-2">
              {geminiGeneratedActions.map((action, index) => (
                <ActionButton
                  key={`gemini-${index}`}
                  action={action}
                  onClick={onAction}
                  disabled={disabled || isOracleInputVisible}
                  isGeminiAction
                />
              ))}
            </div>
          </div>
        )}
      </AnimatePresence>

      {/* Standard Context Actions */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
        {generalActions.map((action, index) => (
          <ActionButton
            key={`gen-${index}`}
            action={action}
            onClick={onAction}
            disabled={disabled || isOracleInputVisible}
          />
        ))}
      </div>

      {/* Rest Actions */}
      <div className="mb-4">
        <h3 className="text-sm font-semibold text-amber-300 mb-2">Rest & Recovery</h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
          <ActionButton
            action={{ type: 'SHORT_REST', label: 'Short Rest' }}
            onClick={handleShortRestClick}
            disabled={disabled}
          />
          <ActionButton
            action={{ type: 'LONG_REST', label: 'Long Rest' }}
            onClick={onAction}
            disabled={disabled}
          />
        </div>
      </div>

      {/* Dev Menu Button (when enabled) */}
      {isDevModeEnabled && (
        <div className="mb-4">
          <ActionButton
            action={{ type: 'toggle_dev_menu', label: 'Dev Menu' }}
            onClick={onAction}
            disabled={disabled}
          />
        </div>
      )}

      {/* System/Menu Actions */}
      <SystemMenu
        onAction={onAction}
        disabled={disabled}
        unreadDiscoveryCount={unreadDiscoveryCount}
        hasNewRateLimitError={hasNewRateLimitError}
        isDevDummyActive={isDevDummyActive}
        isDevModeEnabled={isDevModeEnabled}
        autoSaveEnabled={autoSaveEnabled}
      />

      {/* Modal collects Hit Dice spending for the entire party. */}
      <RestModal
        isOpen={isRestModalOpen}
        party={party}
        onClose={() => setIsRestModalOpen(false)}
        onConfirm={handleShortRestConfirm}
      />

    </div>
  );
};

export default ActionPane;
