// @dependencies-start
/**
 * ARCHITECTURAL ADVISORY:
 * LOCAL HELPER: This file has a small, manageable dependency footprint.
 *
 * Last Sync: 25/08/2026, 01:04:06
 * Dependents: components/DesignPreview/steps/PreviewIcons.tsx
 * Imports: None
 *
 * MULTI-AGENT SAFETY:
 * If you modify exports/imports, re-run the sync tool to update this header:
 * > npx tsx misc/dev_hub/codebase-visualizer/server/index.ts --sync [this-file-path]
 * See misc/dev_hub/codebase-visualizer/VISUALIZER_README.md for more info.
 */
// @dependencies-end

/**
 * This file lists every icon in the TW-D&D vendor collection.
 *
 * It acts as the catalog for 318 Dungeons & Dragons 5e icons created by David Kor
 * Kian Wei (intrinsical/tw-dnd), licensed under CC BY-SA 4.0. The collection spans
 * 24 thematic categories including ability scores, classes, conditions, damage types,
 * monsters, spell schools, area shapes, weapons, and VTT token markers.
 *
 * Called by: PreviewIcons.tsx (Design Preview icon review workbench)
 * Source assets: public/assets/icons/tw-dnd/ (mirrored from vendor/tw-dnd/icons/)
 */

// ============================================================================
// Types & Contracts
// ============================================================================
// These types describe each icon item and category in the TW-D&D collection.
// ============================================================================

export interface TwDndIcon {
  /** Unique key for state tracking and lookups, e.g. 'tw-dnd:class:fighter' */
  id: string;
  /** Human-readable title for UI cards, e.g. 'Fighter' */
  name: string;
  /** Subdirectory key in vendor repository, e.g. 'class' */
  categoryKey: string;
  /** Human-readable category label, e.g. 'Character Classes' */
  categoryLabel: string;
  /** Raw file basename without extension, e.g. 'fighter' */
  base: string;
  /** Graphic format ('svg' for crisp vector shapes, 'png' for Roll20 tokens) */
  format: 'svg' | 'png';
  /** Path relative to the public asset root for browser rendering */
  src: string;
  /** Attribution identifier referencing the vendor repository */
  source: string;
}

export interface TwDndCategoryInfo {
  /** Machine-readable category key matching directory name */
  key: string;
  /** User-facing category title */
  label: string;
  /** Short summary of what icons belong in this group */
  description: string;
  /** Number of icons in this category */
  count: number;
}

// ============================================================================
// Category Metadata Registry
// ============================================================================
// Summary information for all 24 categories in the collection.
// ============================================================================

export const TW_DND_CATEGORY_METADATA: TwDndCategoryInfo[] = [
  {
    key: 'ability',
    label: 'Ability Scores',
    description: 'Core character attributes (Strength, Dexterity, etc.)',
    count: 6,
  },
  {
    key: 'attribute',
    label: 'Attributes & Checks',
    description: 'Armor Class, range, vision, saving throws, and checks',
    count: 11,
  },
  {
    key: 'campaign',
    label: 'Campaigns & Adventures',
    description: 'Official 5e campaign modules and adventure settings',
    count: 12,
  },
  {
    key: 'class',
    label: 'Character Classes',
    description: 'Core 5e adventurer classes',
    count: 13,
  },
  {
    key: 'combat',
    label: 'Combat Actions',
    description: 'Actions, bonus actions, reactions, initiative, and reach',
    count: 9,
  },
  {
    key: 'condition',
    label: 'Conditions & States',
    description: 'Status conditions such as blinded, charmed, paralyzed, and poisoned',
    count: 17,
  },
  {
    key: 'd20test',
    label: 'D20 Tests',
    description: 'Attacker, defender, and saving throw contest markers',
    count: 3,
  },
  {
    key: 'damage',
    label: 'Damage & Resistances',
    description: 'Damage types, immunities, resistances, and vulnerabilities',
    count: 16,
  },
  {
    key: 'dice',
    label: 'Dice & Rolls',
    description: 'Polyhedral dice (d4 through d20), advantage, disadvantage, and roll indicators',
    count: 9,
  },
  {
    key: 'entity',
    label: 'Entity & Item Types',
    description: 'Inventory classifications including armor, weapons, potions, scrolls, and mounts',
    count: 26,
  },
  {
    key: 'game',
    label: 'Game & Encounter Meta',
    description: 'Meta-game elements: DM, inspiration, rests, traps, puzzles, and encounters',
    count: 18,
  },
  {
    key: 'hp',
    label: 'Hit Points & Health',
    description: 'Health indicators including bloodied, 0 HP, full HP, and temporary HP',
    count: 5,
  },
  {
    key: 'location',
    label: 'Locations & Structures',
    description: 'Points of interest: dungeons, castles, taverns, towers, and portals',
    count: 11,
  },
  {
    key: 'logo',
    label: 'Logos & Platforms',
    description: 'VTT platforms, official logos, and community tool icons',
    count: 9,
  },
  {
    key: 'monster',
    label: 'Monster Types',
    description: 'Creature classifications including aberrations, beasts, dragons, fiends, and undead',
    count: 14,
  },
  {
    key: 'movement',
    label: 'Movement Modes',
    description: 'Locomotion modes: burrowing, climbing, flying, swimming, and walking',
    count: 5,
  },
  {
    key: 'proficiency',
    label: 'Proficiency Levels',
    description: 'Proficiency ranks: untrained, half-proficient, proficient, and expertise',
    count: 4,
  },
  {
    key: 'skill',
    label: 'Skills',
    description: 'Character skill proficiencies (Acrobatics, Arcana, Stealth, etc.)',
    count: 18,
  },
  {
    key: 'slot',
    label: 'Spell Slots',
    description: 'Spell slot capacity and expenditure counters',
    count: 14,
  },
  {
    key: 'spell',
    label: 'Spell Schools & Casting',
    description: 'Magic schools (Abjuration, Evocation, etc.) and casting components',
    count: 18,
  },
  {
    key: 'target',
    label: 'Target & Area Shapes',
    description: 'Spell and effect area of effect shapes (cone, cube, sphere, line, etc.)',
    count: 11,
  },
  {
    key: 'util',
    label: 'Utility & System',
    description: 'General utility icons including search, cog, home, star, and checkmarks',
    count: 10,
  },
  {
    key: 'weapon',
    label: 'Weapon Types',
    description: 'Specific weapon categories (swords, bows, daggers, halberds, etc.)',
    count: 27,
  },
  {
    key: 'roll20',
    label: 'Roll20 Token Markers',
    description: 'VTT circular status tokens and combat condition overlays',
    count: 32,
  },
];

// ============================================================================
// Category Icon Inventories
// ============================================================================
// Each category holds its specific list of icons with display labels and paths.
// ============================================================================

export const TW_DND_CATEGORIES: Record<string, TwDndIcon[]> = {
  'Ability Scores': [
    {
      id: 'tw-dnd:ability:charisma',
      name: 'Charisma',
      categoryKey: 'ability',
      categoryLabel: 'Ability Scores',
      base: 'charisma',
      format: 'svg',
      src: 'assets/icons/tw-dnd/ability/charisma.svg',
      source: 'tw-dnd:ability/charisma.svg',
    },
    {
      id: 'tw-dnd:ability:constitution',
      name: 'Constitution',
      categoryKey: 'ability',
      categoryLabel: 'Ability Scores',
      base: 'constitution',
      format: 'svg',
      src: 'assets/icons/tw-dnd/ability/constitution.svg',
      source: 'tw-dnd:ability/constitution.svg',
    },
    {
      id: 'tw-dnd:ability:dexterity',
      name: 'Dexterity',
      categoryKey: 'ability',
      categoryLabel: 'Ability Scores',
      base: 'dexterity',
      format: 'svg',
      src: 'assets/icons/tw-dnd/ability/dexterity.svg',
      source: 'tw-dnd:ability/dexterity.svg',
    },
    {
      id: 'tw-dnd:ability:intelligence',
      name: 'Intelligence',
      categoryKey: 'ability',
      categoryLabel: 'Ability Scores',
      base: 'intelligence',
      format: 'svg',
      src: 'assets/icons/tw-dnd/ability/intelligence.svg',
      source: 'tw-dnd:ability/intelligence.svg',
    },
    {
      id: 'tw-dnd:ability:strength',
      name: 'Strength',
      categoryKey: 'ability',
      categoryLabel: 'Ability Scores',
      base: 'strength',
      format: 'svg',
      src: 'assets/icons/tw-dnd/ability/strength.svg',
      source: 'tw-dnd:ability/strength.svg',
    },
    {
      id: 'tw-dnd:ability:wisdom',
      name: 'Wisdom',
      categoryKey: 'ability',
      categoryLabel: 'Ability Scores',
      base: 'wisdom',
      format: 'svg',
      src: 'assets/icons/tw-dnd/ability/wisdom.svg',
      source: 'tw-dnd:ability/wisdom.svg',
    },
  ],
  'Attributes & Checks': [
    {
      id: 'tw-dnd:attribute:ac',
      name: 'Armor Class (AC)',
      categoryKey: 'attribute',
      categoryLabel: 'Attributes & Checks',
      base: 'ac',
      format: 'svg',
      src: 'assets/icons/tw-dnd/attribute/ac.svg',
      source: 'tw-dnd:attribute/ac.svg',
    },
    {
      id: 'tw-dnd:attribute:attunement',
      name: 'Attunement',
      categoryKey: 'attribute',
      categoryLabel: 'Attributes & Checks',
      base: 'attunement',
      format: 'svg',
      src: 'assets/icons/tw-dnd/attribute/attunement.svg',
      source: 'tw-dnd:attribute/attunement.svg',
    },
    {
      id: 'tw-dnd:attribute:bonus',
      name: 'Bonus',
      categoryKey: 'attribute',
      categoryLabel: 'Attributes & Checks',
      base: 'bonus',
      format: 'svg',
      src: 'assets/icons/tw-dnd/attribute/bonus.svg',
      source: 'tw-dnd:attribute/bonus.svg',
    },
    {
      id: 'tw-dnd:attribute:light',
      name: 'Light',
      categoryKey: 'attribute',
      categoryLabel: 'Attributes & Checks',
      base: 'light',
      format: 'svg',
      src: 'assets/icons/tw-dnd/attribute/light.svg',
      source: 'tw-dnd:attribute/light.svg',
    },
    {
      id: 'tw-dnd:attribute:penalty',
      name: 'Penalty',
      categoryKey: 'attribute',
      categoryLabel: 'Attributes & Checks',
      base: 'penalty',
      format: 'svg',
      src: 'assets/icons/tw-dnd/attribute/penalty.svg',
      source: 'tw-dnd:attribute/penalty.svg',
    },
    {
      id: 'tw-dnd:attribute:range',
      name: 'Range',
      categoryKey: 'attribute',
      categoryLabel: 'Attributes & Checks',
      base: 'range',
      format: 'svg',
      src: 'assets/icons/tw-dnd/attribute/range.svg',
      source: 'tw-dnd:attribute/range.svg',
    },
    {
      id: 'tw-dnd:attribute:saving-throw',
      name: 'Saving Throw',
      categoryKey: 'attribute',
      categoryLabel: 'Attributes & Checks',
      base: 'saving-throw',
      format: 'svg',
      src: 'assets/icons/tw-dnd/attribute/saving-throw.svg',
      source: 'tw-dnd:attribute/saving-throw.svg',
    },
    {
      id: 'tw-dnd:attribute:skillcheck',
      name: 'Skillcheck',
      categoryKey: 'attribute',
      categoryLabel: 'Attributes & Checks',
      base: 'skillcheck',
      format: 'svg',
      src: 'assets/icons/tw-dnd/attribute/skillcheck.svg',
      source: 'tw-dnd:attribute/skillcheck.svg',
    },
    {
      id: 'tw-dnd:attribute:terrain',
      name: 'Terrain',
      categoryKey: 'attribute',
      categoryLabel: 'Attributes & Checks',
      base: 'terrain',
      format: 'svg',
      src: 'assets/icons/tw-dnd/attribute/terrain.svg',
      source: 'tw-dnd:attribute/terrain.svg',
    },
    {
      id: 'tw-dnd:attribute:test',
      name: 'Test',
      categoryKey: 'attribute',
      categoryLabel: 'Attributes & Checks',
      base: 'test',
      format: 'svg',
      src: 'assets/icons/tw-dnd/attribute/test.svg',
      source: 'tw-dnd:attribute/test.svg',
    },
    {
      id: 'tw-dnd:attribute:vision',
      name: 'Vision',
      categoryKey: 'attribute',
      categoryLabel: 'Attributes & Checks',
      base: 'vision',
      format: 'svg',
      src: 'assets/icons/tw-dnd/attribute/vision.svg',
      source: 'tw-dnd:attribute/vision.svg',
    },
  ],
  'Campaigns & Adventures': [
    {
      id: 'tw-dnd:campaign:candlekeep',
      name: 'Candlekeep',
      categoryKey: 'campaign',
      categoryLabel: 'Campaigns & Adventures',
      base: 'candlekeep',
      format: 'svg',
      src: 'assets/icons/tw-dnd/campaign/candlekeep.svg',
      source: 'tw-dnd:campaign/candlekeep.svg',
    },
    {
      id: 'tw-dnd:campaign:curse-of-strahd',
      name: 'Curse Of Strahd',
      categoryKey: 'campaign',
      categoryLabel: 'Campaigns & Adventures',
      base: 'curse-of-strahd',
      format: 'svg',
      src: 'assets/icons/tw-dnd/campaign/curse-of-strahd.svg',
      source: 'tw-dnd:campaign/curse-of-strahd.svg',
    },
    {
      id: 'tw-dnd:campaign:descent-into-avernus',
      name: 'Descent Into Avernus',
      categoryKey: 'campaign',
      categoryLabel: 'Campaigns & Adventures',
      base: 'descent-into-avernus',
      format: 'svg',
      src: 'assets/icons/tw-dnd/campaign/descent-into-avernus.svg',
      source: 'tw-dnd:campaign/descent-into-avernus.svg',
    },
    {
      id: 'tw-dnd:campaign:elemental-evil',
      name: 'Elemental Evil',
      categoryKey: 'campaign',
      categoryLabel: 'Campaigns & Adventures',
      base: 'elemental-evil',
      format: 'svg',
      src: 'assets/icons/tw-dnd/campaign/elemental-evil.svg',
      source: 'tw-dnd:campaign/elemental-evil.svg',
    },
    {
      id: 'tw-dnd:campaign:hoard-of-the-dragon-queen',
      name: 'Hoard Of The Dragon Queen',
      categoryKey: 'campaign',
      categoryLabel: 'Campaigns & Adventures',
      base: 'hoard-of-the-dragon-queen',
      format: 'svg',
      src: 'assets/icons/tw-dnd/campaign/hoard-of-the-dragon-queen.svg',
      source: 'tw-dnd:campaign/hoard-of-the-dragon-queen.svg',
    },
    {
      id: 'tw-dnd:campaign:light-of-xaryxis',
      name: 'Light Of Xaryxis',
      categoryKey: 'campaign',
      categoryLabel: 'Campaigns & Adventures',
      base: 'light-of-xaryxis',
      format: 'svg',
      src: 'assets/icons/tw-dnd/campaign/light-of-xaryxis.svg',
      source: 'tw-dnd:campaign/light-of-xaryxis.svg',
    },
    {
      id: 'tw-dnd:campaign:out-of-the-abyss',
      name: 'Out Of The Abyss',
      categoryKey: 'campaign',
      categoryLabel: 'Campaigns & Adventures',
      base: 'out-of-the-abyss',
      format: 'svg',
      src: 'assets/icons/tw-dnd/campaign/out-of-the-abyss.svg',
      source: 'tw-dnd:campaign/out-of-the-abyss.svg',
    },
    {
      id: 'tw-dnd:campaign:rime-of-the-frostmaiden',
      name: 'Rime Of The Frostmaiden',
      categoryKey: 'campaign',
      categoryLabel: 'Campaigns & Adventures',
      base: 'rime-of-the-frostmaiden',
      format: 'svg',
      src: 'assets/icons/tw-dnd/campaign/rime-of-the-frostmaiden.svg',
      source: 'tw-dnd:campaign/rime-of-the-frostmaiden.svg',
    },
    {
      id: 'tw-dnd:campaign:storm-kings-thunder',
      name: 'Storm Kings Thunder',
      categoryKey: 'campaign',
      categoryLabel: 'Campaigns & Adventures',
      base: 'storm-kings-thunder',
      format: 'svg',
      src: 'assets/icons/tw-dnd/campaign/storm-kings-thunder.svg',
      source: 'tw-dnd:campaign/storm-kings-thunder.svg',
    },
    {
      id: 'tw-dnd:campaign:tomb-of-annihilation',
      name: 'Tomb Of Annihilation',
      categoryKey: 'campaign',
      categoryLabel: 'Campaigns & Adventures',
      base: 'tomb-of-annihilation',
      format: 'svg',
      src: 'assets/icons/tw-dnd/campaign/tomb-of-annihilation.svg',
      source: 'tw-dnd:campaign/tomb-of-annihilation.svg',
    },
    {
      id: 'tw-dnd:campaign:waterdeep',
      name: 'Waterdeep',
      categoryKey: 'campaign',
      categoryLabel: 'Campaigns & Adventures',
      base: 'waterdeep',
      format: 'svg',
      src: 'assets/icons/tw-dnd/campaign/waterdeep.svg',
      source: 'tw-dnd:campaign/waterdeep.svg',
    },
    {
      id: 'tw-dnd:campaign:yawning-portal',
      name: 'Yawning Portal',
      categoryKey: 'campaign',
      categoryLabel: 'Campaigns & Adventures',
      base: 'yawning-portal',
      format: 'svg',
      src: 'assets/icons/tw-dnd/campaign/yawning-portal.svg',
      source: 'tw-dnd:campaign/yawning-portal.svg',
    },
  ],
  'Character Classes': [
    {
      id: 'tw-dnd:class:artificer',
      name: 'Artificer',
      categoryKey: 'class',
      categoryLabel: 'Character Classes',
      base: 'artificer',
      format: 'svg',
      src: 'assets/icons/tw-dnd/class/artificer.svg',
      source: 'tw-dnd:class/artificer.svg',
    },
    {
      id: 'tw-dnd:class:barbarian',
      name: 'Barbarian',
      categoryKey: 'class',
      categoryLabel: 'Character Classes',
      base: 'barbarian',
      format: 'svg',
      src: 'assets/icons/tw-dnd/class/barbarian.svg',
      source: 'tw-dnd:class/barbarian.svg',
    },
    {
      id: 'tw-dnd:class:bard',
      name: 'Bard',
      categoryKey: 'class',
      categoryLabel: 'Character Classes',
      base: 'bard',
      format: 'svg',
      src: 'assets/icons/tw-dnd/class/bard.svg',
      source: 'tw-dnd:class/bard.svg',
    },
    {
      id: 'tw-dnd:class:cleric',
      name: 'Cleric',
      categoryKey: 'class',
      categoryLabel: 'Character Classes',
      base: 'cleric',
      format: 'svg',
      src: 'assets/icons/tw-dnd/class/cleric.svg',
      source: 'tw-dnd:class/cleric.svg',
    },
    {
      id: 'tw-dnd:class:druid',
      name: 'Druid',
      categoryKey: 'class',
      categoryLabel: 'Character Classes',
      base: 'druid',
      format: 'svg',
      src: 'assets/icons/tw-dnd/class/druid.svg',
      source: 'tw-dnd:class/druid.svg',
    },
    {
      id: 'tw-dnd:class:fighter',
      name: 'Fighter',
      categoryKey: 'class',
      categoryLabel: 'Character Classes',
      base: 'fighter',
      format: 'svg',
      src: 'assets/icons/tw-dnd/class/fighter.svg',
      source: 'tw-dnd:class/fighter.svg',
    },
    {
      id: 'tw-dnd:class:monk',
      name: 'Monk',
      categoryKey: 'class',
      categoryLabel: 'Character Classes',
      base: 'monk',
      format: 'svg',
      src: 'assets/icons/tw-dnd/class/monk.svg',
      source: 'tw-dnd:class/monk.svg',
    },
    {
      id: 'tw-dnd:class:paladin',
      name: 'Paladin',
      categoryKey: 'class',
      categoryLabel: 'Character Classes',
      base: 'paladin',
      format: 'svg',
      src: 'assets/icons/tw-dnd/class/paladin.svg',
      source: 'tw-dnd:class/paladin.svg',
    },
    {
      id: 'tw-dnd:class:ranger',
      name: 'Ranger',
      categoryKey: 'class',
      categoryLabel: 'Character Classes',
      base: 'ranger',
      format: 'svg',
      src: 'assets/icons/tw-dnd/class/ranger.svg',
      source: 'tw-dnd:class/ranger.svg',
    },
    {
      id: 'tw-dnd:class:rogue',
      name: 'Rogue',
      categoryKey: 'class',
      categoryLabel: 'Character Classes',
      base: 'rogue',
      format: 'svg',
      src: 'assets/icons/tw-dnd/class/rogue.svg',
      source: 'tw-dnd:class/rogue.svg',
    },
    {
      id: 'tw-dnd:class:sorcerer',
      name: 'Sorcerer',
      categoryKey: 'class',
      categoryLabel: 'Character Classes',
      base: 'sorcerer',
      format: 'svg',
      src: 'assets/icons/tw-dnd/class/sorcerer.svg',
      source: 'tw-dnd:class/sorcerer.svg',
    },
    {
      id: 'tw-dnd:class:warlock',
      name: 'Warlock',
      categoryKey: 'class',
      categoryLabel: 'Character Classes',
      base: 'warlock',
      format: 'svg',
      src: 'assets/icons/tw-dnd/class/warlock.svg',
      source: 'tw-dnd:class/warlock.svg',
    },
    {
      id: 'tw-dnd:class:wizard',
      name: 'Wizard',
      categoryKey: 'class',
      categoryLabel: 'Character Classes',
      base: 'wizard',
      format: 'svg',
      src: 'assets/icons/tw-dnd/class/wizard.svg',
      source: 'tw-dnd:class/wizard.svg',
    },
  ],
  'Combat Actions': [
    {
      id: 'tw-dnd:combat:action',
      name: 'Action',
      categoryKey: 'combat',
      categoryLabel: 'Combat Actions',
      base: 'action',
      format: 'svg',
      src: 'assets/icons/tw-dnd/combat/action.svg',
      source: 'tw-dnd:combat/action.svg',
    },
    {
      id: 'tw-dnd:combat:bonus-action',
      name: 'Bonus Action',
      categoryKey: 'combat',
      categoryLabel: 'Combat Actions',
      base: 'bonus-action',
      format: 'svg',
      src: 'assets/icons/tw-dnd/combat/bonus-action.svg',
      source: 'tw-dnd:combat/bonus-action.svg',
    },
    {
      id: 'tw-dnd:combat:initiative',
      name: 'Initiative',
      categoryKey: 'combat',
      categoryLabel: 'Combat Actions',
      base: 'initiative',
      format: 'svg',
      src: 'assets/icons/tw-dnd/combat/initiative.svg',
      source: 'tw-dnd:combat/initiative.svg',
    },
    {
      id: 'tw-dnd:combat:melee',
      name: 'Melee',
      categoryKey: 'combat',
      categoryLabel: 'Combat Actions',
      base: 'melee',
      format: 'svg',
      src: 'assets/icons/tw-dnd/combat/melee.svg',
      source: 'tw-dnd:combat/melee.svg',
    },
    {
      id: 'tw-dnd:combat:ranged',
      name: 'Ranged',
      categoryKey: 'combat',
      categoryLabel: 'Combat Actions',
      base: 'ranged',
      format: 'svg',
      src: 'assets/icons/tw-dnd/combat/ranged.svg',
      source: 'tw-dnd:combat/ranged.svg',
    },
    {
      id: 'tw-dnd:combat:reach',
      name: 'Reach',
      categoryKey: 'combat',
      categoryLabel: 'Combat Actions',
      base: 'reach',
      format: 'svg',
      src: 'assets/icons/tw-dnd/combat/reach.svg',
      source: 'tw-dnd:combat/reach.svg',
    },
    {
      id: 'tw-dnd:combat:reaction',
      name: 'Reaction',
      categoryKey: 'combat',
      categoryLabel: 'Combat Actions',
      base: 'reaction',
      format: 'svg',
      src: 'assets/icons/tw-dnd/combat/reaction.svg',
      source: 'tw-dnd:combat/reaction.svg',
    },
    {
      id: 'tw-dnd:combat:round',
      name: 'Round',
      categoryKey: 'combat',
      categoryLabel: 'Combat Actions',
      base: 'round',
      format: 'svg',
      src: 'assets/icons/tw-dnd/combat/round.svg',
      source: 'tw-dnd:combat/round.svg',
    },
    {
      id: 'tw-dnd:combat:target',
      name: 'Target',
      categoryKey: 'combat',
      categoryLabel: 'Combat Actions',
      base: 'target',
      format: 'svg',
      src: 'assets/icons/tw-dnd/combat/target.svg',
      source: 'tw-dnd:combat/target.svg',
    },
  ],
  'Conditions & States': [
    {
      id: 'tw-dnd:condition:blinded',
      name: 'Blinded',
      categoryKey: 'condition',
      categoryLabel: 'Conditions & States',
      base: 'blinded',
      format: 'svg',
      src: 'assets/icons/tw-dnd/condition/blinded.svg',
      source: 'tw-dnd:condition/blinded.svg',
    },
    {
      id: 'tw-dnd:condition:charmed',
      name: 'Charmed',
      categoryKey: 'condition',
      categoryLabel: 'Conditions & States',
      base: 'charmed',
      format: 'svg',
      src: 'assets/icons/tw-dnd/condition/charmed.svg',
      source: 'tw-dnd:condition/charmed.svg',
    },
    {
      id: 'tw-dnd:condition:deafened',
      name: 'Deafened',
      categoryKey: 'condition',
      categoryLabel: 'Conditions & States',
      base: 'deafened',
      format: 'svg',
      src: 'assets/icons/tw-dnd/condition/deafened.svg',
      source: 'tw-dnd:condition/deafened.svg',
    },
    {
      id: 'tw-dnd:condition:exhaustion',
      name: 'Exhaustion',
      categoryKey: 'condition',
      categoryLabel: 'Conditions & States',
      base: 'exhaustion',
      format: 'svg',
      src: 'assets/icons/tw-dnd/condition/exhaustion.svg',
      source: 'tw-dnd:condition/exhaustion.svg',
    },
    {
      id: 'tw-dnd:condition:frightened',
      name: 'Frightened',
      categoryKey: 'condition',
      categoryLabel: 'Conditions & States',
      base: 'frightened',
      format: 'svg',
      src: 'assets/icons/tw-dnd/condition/frightened.svg',
      source: 'tw-dnd:condition/frightened.svg',
    },
    {
      id: 'tw-dnd:condition:grappled',
      name: 'Grappled',
      categoryKey: 'condition',
      categoryLabel: 'Conditions & States',
      base: 'grappled',
      format: 'svg',
      src: 'assets/icons/tw-dnd/condition/grappled.svg',
      source: 'tw-dnd:condition/grappled.svg',
    },
    {
      id: 'tw-dnd:condition:incapacitated',
      name: 'Incapacitated',
      categoryKey: 'condition',
      categoryLabel: 'Conditions & States',
      base: 'incapacitated',
      format: 'svg',
      src: 'assets/icons/tw-dnd/condition/incapacitated.svg',
      source: 'tw-dnd:condition/incapacitated.svg',
    },
    {
      id: 'tw-dnd:condition:invisible',
      name: 'Invisible',
      categoryKey: 'condition',
      categoryLabel: 'Conditions & States',
      base: 'invisible',
      format: 'svg',
      src: 'assets/icons/tw-dnd/condition/invisible.svg',
      source: 'tw-dnd:condition/invisible.svg',
    },
    {
      id: 'tw-dnd:condition:paralyzed',
      name: 'Paralyzed',
      categoryKey: 'condition',
      categoryLabel: 'Conditions & States',
      base: 'paralyzed',
      format: 'svg',
      src: 'assets/icons/tw-dnd/condition/paralyzed.svg',
      source: 'tw-dnd:condition/paralyzed.svg',
    },
    {
      id: 'tw-dnd:condition:petrified',
      name: 'Petrified',
      categoryKey: 'condition',
      categoryLabel: 'Conditions & States',
      base: 'petrified',
      format: 'svg',
      src: 'assets/icons/tw-dnd/condition/petrified.svg',
      source: 'tw-dnd:condition/petrified.svg',
    },
    {
      id: 'tw-dnd:condition:poisoned',
      name: 'Poisoned',
      categoryKey: 'condition',
      categoryLabel: 'Conditions & States',
      base: 'poisoned',
      format: 'svg',
      src: 'assets/icons/tw-dnd/condition/poisoned.svg',
      source: 'tw-dnd:condition/poisoned.svg',
    },
    {
      id: 'tw-dnd:condition:prone',
      name: 'Prone',
      categoryKey: 'condition',
      categoryLabel: 'Conditions & States',
      base: 'prone',
      format: 'svg',
      src: 'assets/icons/tw-dnd/condition/prone.svg',
      source: 'tw-dnd:condition/prone.svg',
    },
    {
      id: 'tw-dnd:condition:restrained',
      name: 'Restrained',
      categoryKey: 'condition',
      categoryLabel: 'Conditions & States',
      base: 'restrained',
      format: 'svg',
      src: 'assets/icons/tw-dnd/condition/restrained.svg',
      source: 'tw-dnd:condition/restrained.svg',
    },
    {
      id: 'tw-dnd:condition:silenced',
      name: 'Silenced',
      categoryKey: 'condition',
      categoryLabel: 'Conditions & States',
      base: 'silenced',
      format: 'svg',
      src: 'assets/icons/tw-dnd/condition/silenced.svg',
      source: 'tw-dnd:condition/silenced.svg',
    },
    {
      id: 'tw-dnd:condition:sleep',
      name: 'Sleep',
      categoryKey: 'condition',
      categoryLabel: 'Conditions & States',
      base: 'sleep',
      format: 'svg',
      src: 'assets/icons/tw-dnd/condition/sleep.svg',
      source: 'tw-dnd:condition/sleep.svg',
    },
    {
      id: 'tw-dnd:condition:stunned',
      name: 'Stunned',
      categoryKey: 'condition',
      categoryLabel: 'Conditions & States',
      base: 'stunned',
      format: 'svg',
      src: 'assets/icons/tw-dnd/condition/stunned.svg',
      source: 'tw-dnd:condition/stunned.svg',
    },
    {
      id: 'tw-dnd:condition:unconscious',
      name: 'Unconscious',
      categoryKey: 'condition',
      categoryLabel: 'Conditions & States',
      base: 'unconscious',
      format: 'svg',
      src: 'assets/icons/tw-dnd/condition/unconscious.svg',
      source: 'tw-dnd:condition/unconscious.svg',
    },
  ],
  'D20 Tests': [
    {
      id: 'tw-dnd:d20test:attacked',
      name: 'Attacked',
      categoryKey: 'd20test',
      categoryLabel: 'D20 Tests',
      base: 'attacked',
      format: 'svg',
      src: 'assets/icons/tw-dnd/d20test/attacked.svg',
      source: 'tw-dnd:d20test/attacked.svg',
    },
    {
      id: 'tw-dnd:d20test:attacking',
      name: 'Attacking',
      categoryKey: 'd20test',
      categoryLabel: 'D20 Tests',
      base: 'attacking',
      format: 'svg',
      src: 'assets/icons/tw-dnd/d20test/attacking.svg',
      source: 'tw-dnd:d20test/attacking.svg',
    },
    {
      id: 'tw-dnd:d20test:saving-throw',
      name: 'Saving Throw',
      categoryKey: 'd20test',
      categoryLabel: 'D20 Tests',
      base: 'saving-throw',
      format: 'svg',
      src: 'assets/icons/tw-dnd/d20test/saving-throw.svg',
      source: 'tw-dnd:d20test/saving-throw.svg',
    },
  ],
  'Damage & Resistances': [
    {
      id: 'tw-dnd:damage:acid',
      name: 'Acid',
      categoryKey: 'damage',
      categoryLabel: 'Damage & Resistances',
      base: 'acid',
      format: 'svg',
      src: 'assets/icons/tw-dnd/damage/acid.svg',
      source: 'tw-dnd:damage/acid.svg',
    },
    {
      id: 'tw-dnd:damage:bludgeoning',
      name: 'Bludgeoning',
      categoryKey: 'damage',
      categoryLabel: 'Damage & Resistances',
      base: 'bludgeoning',
      format: 'svg',
      src: 'assets/icons/tw-dnd/damage/bludgeoning.svg',
      source: 'tw-dnd:damage/bludgeoning.svg',
    },
    {
      id: 'tw-dnd:damage:cold',
      name: 'Cold',
      categoryKey: 'damage',
      categoryLabel: 'Damage & Resistances',
      base: 'cold',
      format: 'svg',
      src: 'assets/icons/tw-dnd/damage/cold.svg',
      source: 'tw-dnd:damage/cold.svg',
    },
    {
      id: 'tw-dnd:damage:fire',
      name: 'Fire',
      categoryKey: 'damage',
      categoryLabel: 'Damage & Resistances',
      base: 'fire',
      format: 'svg',
      src: 'assets/icons/tw-dnd/damage/fire.svg',
      source: 'tw-dnd:damage/fire.svg',
    },
    {
      id: 'tw-dnd:damage:force',
      name: 'Force',
      categoryKey: 'damage',
      categoryLabel: 'Damage & Resistances',
      base: 'force',
      format: 'svg',
      src: 'assets/icons/tw-dnd/damage/force.svg',
      source: 'tw-dnd:damage/force.svg',
    },
    {
      id: 'tw-dnd:damage:immunity',
      name: 'Immunity',
      categoryKey: 'damage',
      categoryLabel: 'Damage & Resistances',
      base: 'immunity',
      format: 'svg',
      src: 'assets/icons/tw-dnd/damage/immunity.svg',
      source: 'tw-dnd:damage/immunity.svg',
    },
    {
      id: 'tw-dnd:damage:lightning',
      name: 'Lightning',
      categoryKey: 'damage',
      categoryLabel: 'Damage & Resistances',
      base: 'lightning',
      format: 'svg',
      src: 'assets/icons/tw-dnd/damage/lightning.svg',
      source: 'tw-dnd:damage/lightning.svg',
    },
    {
      id: 'tw-dnd:damage:necrotic',
      name: 'Necrotic',
      categoryKey: 'damage',
      categoryLabel: 'Damage & Resistances',
      base: 'necrotic',
      format: 'svg',
      src: 'assets/icons/tw-dnd/damage/necrotic.svg',
      source: 'tw-dnd:damage/necrotic.svg',
    },
    {
      id: 'tw-dnd:damage:piercing',
      name: 'Piercing',
      categoryKey: 'damage',
      categoryLabel: 'Damage & Resistances',
      base: 'piercing',
      format: 'svg',
      src: 'assets/icons/tw-dnd/damage/piercing.svg',
      source: 'tw-dnd:damage/piercing.svg',
    },
    {
      id: 'tw-dnd:damage:poison',
      name: 'Poison',
      categoryKey: 'damage',
      categoryLabel: 'Damage & Resistances',
      base: 'poison',
      format: 'svg',
      src: 'assets/icons/tw-dnd/damage/poison.svg',
      source: 'tw-dnd:damage/poison.svg',
    },
    {
      id: 'tw-dnd:damage:psychic',
      name: 'Psychic',
      categoryKey: 'damage',
      categoryLabel: 'Damage & Resistances',
      base: 'psychic',
      format: 'svg',
      src: 'assets/icons/tw-dnd/damage/psychic.svg',
      source: 'tw-dnd:damage/psychic.svg',
    },
    {
      id: 'tw-dnd:damage:radiant',
      name: 'Radiant',
      categoryKey: 'damage',
      categoryLabel: 'Damage & Resistances',
      base: 'radiant',
      format: 'svg',
      src: 'assets/icons/tw-dnd/damage/radiant.svg',
      source: 'tw-dnd:damage/radiant.svg',
    },
    {
      id: 'tw-dnd:damage:resistance',
      name: 'Resistance',
      categoryKey: 'damage',
      categoryLabel: 'Damage & Resistances',
      base: 'resistance',
      format: 'svg',
      src: 'assets/icons/tw-dnd/damage/resistance.svg',
      source: 'tw-dnd:damage/resistance.svg',
    },
    {
      id: 'tw-dnd:damage:slashing',
      name: 'Slashing',
      categoryKey: 'damage',
      categoryLabel: 'Damage & Resistances',
      base: 'slashing',
      format: 'svg',
      src: 'assets/icons/tw-dnd/damage/slashing.svg',
      source: 'tw-dnd:damage/slashing.svg',
    },
    {
      id: 'tw-dnd:damage:thunder',
      name: 'Thunder',
      categoryKey: 'damage',
      categoryLabel: 'Damage & Resistances',
      base: 'thunder',
      format: 'svg',
      src: 'assets/icons/tw-dnd/damage/thunder.svg',
      source: 'tw-dnd:damage/thunder.svg',
    },
    {
      id: 'tw-dnd:damage:vulnerability',
      name: 'Vulnerability',
      categoryKey: 'damage',
      categoryLabel: 'Damage & Resistances',
      base: 'vulnerability',
      format: 'svg',
      src: 'assets/icons/tw-dnd/damage/vulnerability.svg',
      source: 'tw-dnd:damage/vulnerability.svg',
    },
  ],
  'Dice & Rolls': [
    {
      id: 'tw-dnd:dice:advantage',
      name: 'Advantage',
      categoryKey: 'dice',
      categoryLabel: 'Dice & Rolls',
      base: 'advantage',
      format: 'svg',
      src: 'assets/icons/tw-dnd/dice/advantage.svg',
      source: 'tw-dnd:dice/advantage.svg',
    },
    {
      id: 'tw-dnd:dice:d10',
      name: 'd10 Die',
      categoryKey: 'dice',
      categoryLabel: 'Dice & Rolls',
      base: 'd10',
      format: 'svg',
      src: 'assets/icons/tw-dnd/dice/d10.svg',
      source: 'tw-dnd:dice/d10.svg',
    },
    {
      id: 'tw-dnd:dice:d12',
      name: 'd12 Die',
      categoryKey: 'dice',
      categoryLabel: 'Dice & Rolls',
      base: 'd12',
      format: 'svg',
      src: 'assets/icons/tw-dnd/dice/d12.svg',
      source: 'tw-dnd:dice/d12.svg',
    },
    {
      id: 'tw-dnd:dice:d20',
      name: 'd20 Die',
      categoryKey: 'dice',
      categoryLabel: 'Dice & Rolls',
      base: 'd20',
      format: 'svg',
      src: 'assets/icons/tw-dnd/dice/d20.svg',
      source: 'tw-dnd:dice/d20.svg',
    },
    {
      id: 'tw-dnd:dice:d4',
      name: 'd4 Die',
      categoryKey: 'dice',
      categoryLabel: 'Dice & Rolls',
      base: 'd4',
      format: 'svg',
      src: 'assets/icons/tw-dnd/dice/d4.svg',
      source: 'tw-dnd:dice/d4.svg',
    },
    {
      id: 'tw-dnd:dice:d6',
      name: 'd6 Die',
      categoryKey: 'dice',
      categoryLabel: 'Dice & Rolls',
      base: 'd6',
      format: 'svg',
      src: 'assets/icons/tw-dnd/dice/d6.svg',
      source: 'tw-dnd:dice/d6.svg',
    },
    {
      id: 'tw-dnd:dice:d8',
      name: 'd8 Die',
      categoryKey: 'dice',
      categoryLabel: 'Dice & Rolls',
      base: 'd8',
      format: 'svg',
      src: 'assets/icons/tw-dnd/dice/d8.svg',
      source: 'tw-dnd:dice/d8.svg',
    },
    {
      id: 'tw-dnd:dice:disadvantage',
      name: 'Disadvantage',
      categoryKey: 'dice',
      categoryLabel: 'Dice & Rolls',
      base: 'disadvantage',
      format: 'svg',
      src: 'assets/icons/tw-dnd/dice/disadvantage.svg',
      source: 'tw-dnd:dice/disadvantage.svg',
    },
    {
      id: 'tw-dnd:dice:roll',
      name: 'Roll',
      categoryKey: 'dice',
      categoryLabel: 'Dice & Rolls',
      base: 'roll',
      format: 'svg',
      src: 'assets/icons/tw-dnd/dice/roll.svg',
      source: 'tw-dnd:dice/roll.svg',
    },
  ],
  'Entity & Item Types': [
    {
      id: 'tw-dnd:entity:archive',
      name: 'Archive',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'archive',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/archive.svg',
      source: 'tw-dnd:entity/archive.svg',
    },
    {
      id: 'tw-dnd:entity:armor',
      name: 'Armor',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'armor',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/armor.svg',
      source: 'tw-dnd:entity/armor.svg',
    },
    {
      id: 'tw-dnd:entity:book',
      name: 'Book',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'book',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/book.svg',
      source: 'tw-dnd:entity/book.svg',
    },
    {
      id: 'tw-dnd:entity:location',
      name: 'Location',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'location',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/location.svg',
      source: 'tw-dnd:entity/location.svg',
    },
    {
      id: 'tw-dnd:entity:loot',
      name: 'Loot',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'loot',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/loot.svg',
      source: 'tw-dnd:entity/loot.svg',
    },
    {
      id: 'tw-dnd:entity:magic-item',
      name: 'Magic Item',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'magic-item',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/magic-item.svg',
      source: 'tw-dnd:entity/magic-item.svg',
    },
    {
      id: 'tw-dnd:entity:map',
      name: 'Map',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'map',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/map.svg',
      source: 'tw-dnd:entity/map.svg',
    },
    {
      id: 'tw-dnd:entity:mount',
      name: 'Mount',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'mount',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/mount.svg',
      source: 'tw-dnd:entity/mount.svg',
    },
    {
      id: 'tw-dnd:entity:object',
      name: 'Object',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'object',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/object.svg',
      source: 'tw-dnd:entity/object.svg',
    },
    {
      id: 'tw-dnd:entity:organization',
      name: 'Organization',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'organization',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/organization.svg',
      source: 'tw-dnd:entity/organization.svg',
    },
    {
      id: 'tw-dnd:entity:pack',
      name: 'Pack',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'pack',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/pack.svg',
      source: 'tw-dnd:entity/pack.svg',
    },
    {
      id: 'tw-dnd:entity:person',
      name: 'Person',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'person',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/person.svg',
      source: 'tw-dnd:entity/person.svg',
    },
    {
      id: 'tw-dnd:entity:pet',
      name: 'Pet',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'pet',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/pet.svg',
      source: 'tw-dnd:entity/pet.svg',
    },
    {
      id: 'tw-dnd:entity:potion',
      name: 'Potion',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'potion',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/potion.svg',
      source: 'tw-dnd:entity/potion.svg',
    },
    {
      id: 'tw-dnd:entity:ring',
      name: 'Ring',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'ring',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/ring.svg',
      source: 'tw-dnd:entity/ring.svg',
    },
    {
      id: 'tw-dnd:entity:scroll',
      name: 'Scroll',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'scroll',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/scroll.svg',
      source: 'tw-dnd:entity/scroll.svg',
    },
    {
      id: 'tw-dnd:entity:ship',
      name: 'Ship',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'ship',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/ship.svg',
      source: 'tw-dnd:entity/ship.svg',
    },
    {
      id: 'tw-dnd:entity:spellbook',
      name: 'Spellbook',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'spellbook',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/spellbook.svg',
      source: 'tw-dnd:entity/spellbook.svg',
    },
    {
      id: 'tw-dnd:entity:summon',
      name: 'Summon',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'summon',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/summon.svg',
      source: 'tw-dnd:entity/summon.svg',
    },
    {
      id: 'tw-dnd:entity:time',
      name: 'Time',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'time',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/time.svg',
      source: 'tw-dnd:entity/time.svg',
    },
    {
      id: 'tw-dnd:entity:tool',
      name: 'Tool',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'tool',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/tool.svg',
      source: 'tw-dnd:entity/tool.svg',
    },
    {
      id: 'tw-dnd:entity:trinket',
      name: 'Trinket',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'trinket',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/trinket.svg',
      source: 'tw-dnd:entity/trinket.svg',
    },
    {
      id: 'tw-dnd:entity:vehicle',
      name: 'Vehicle',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'vehicle',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/vehicle.svg',
      source: 'tw-dnd:entity/vehicle.svg',
    },
    {
      id: 'tw-dnd:entity:wand',
      name: 'Wand',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'wand',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/wand.svg',
      source: 'tw-dnd:entity/wand.svg',
    },
    {
      id: 'tw-dnd:entity:weapon',
      name: 'Weapon',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'weapon',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/weapon.svg',
      source: 'tw-dnd:entity/weapon.svg',
    },
    {
      id: 'tw-dnd:entity:world',
      name: 'World',
      categoryKey: 'entity',
      categoryLabel: 'Entity & Item Types',
      base: 'world',
      format: 'svg',
      src: 'assets/icons/tw-dnd/entity/world.svg',
      source: 'tw-dnd:entity/world.svg',
    },
  ],
  'Game & Encounter Meta': [
    {
      id: 'tw-dnd:game:adventure-book',
      name: 'Adventure Book',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'adventure-book',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/adventure-book.svg',
      source: 'tw-dnd:game/adventure-book.svg',
    },
    {
      id: 'tw-dnd:game:campaign',
      name: 'Campaign',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'campaign',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/campaign.svg',
      source: 'tw-dnd:game/campaign.svg',
    },
    {
      id: 'tw-dnd:game:character',
      name: 'Character',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'character',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/character.svg',
      source: 'tw-dnd:game/character.svg',
    },
    {
      id: 'tw-dnd:game:combat',
      name: 'Combat',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'combat',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/combat.svg',
      source: 'tw-dnd:game/combat.svg',
    },
    {
      id: 'tw-dnd:game:concentration',
      name: 'Concentration',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'concentration',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/concentration.svg',
      source: 'tw-dnd:game/concentration.svg',
    },
    {
      id: 'tw-dnd:game:dm',
      name: 'Dungeon Master (DM)',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'dm',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/dm.svg',
      source: 'tw-dnd:game/dm.svg',
    },
    {
      id: 'tw-dnd:game:explore',
      name: 'Explore',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'explore',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/explore.svg',
      source: 'tw-dnd:game/explore.svg',
    },
    {
      id: 'tw-dnd:game:hazard',
      name: 'Hazard',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'hazard',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/hazard.svg',
      source: 'tw-dnd:game/hazard.svg',
    },
    {
      id: 'tw-dnd:game:inspiration',
      name: 'Inspiration',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'inspiration',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/inspiration.svg',
      source: 'tw-dnd:game/inspiration.svg',
    },
    {
      id: 'tw-dnd:game:lock',
      name: 'Lock',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'lock',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/lock.svg',
      source: 'tw-dnd:game/lock.svg',
    },
    {
      id: 'tw-dnd:game:monster',
      name: 'Monster',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'monster',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/monster.svg',
      source: 'tw-dnd:game/monster.svg',
    },
    {
      id: 'tw-dnd:game:party',
      name: 'Party',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'party',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/party.svg',
      source: 'tw-dnd:game/party.svg',
    },
    {
      id: 'tw-dnd:game:puzzle',
      name: 'Puzzle',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'puzzle',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/puzzle.svg',
      source: 'tw-dnd:game/puzzle.svg',
    },
    {
      id: 'tw-dnd:game:rest',
      name: 'Rest',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'rest',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/rest.svg',
      source: 'tw-dnd:game/rest.svg',
    },
    {
      id: 'tw-dnd:game:social',
      name: 'Social',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'social',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/social.svg',
      source: 'tw-dnd:game/social.svg',
    },
    {
      id: 'tw-dnd:game:source-book',
      name: 'Source Book',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'source-book',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/source-book.svg',
      source: 'tw-dnd:game/source-book.svg',
    },
    {
      id: 'tw-dnd:game:spell',
      name: 'Spell',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'spell',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/spell.svg',
      source: 'tw-dnd:game/spell.svg',
    },
    {
      id: 'tw-dnd:game:trap',
      name: 'Trap',
      categoryKey: 'game',
      categoryLabel: 'Game & Encounter Meta',
      base: 'trap',
      format: 'svg',
      src: 'assets/icons/tw-dnd/game/trap.svg',
      source: 'tw-dnd:game/trap.svg',
    },
  ],
  'Hit Points & Health': [
    {
      id: 'tw-dnd:hp:blood',
      name: 'Blood',
      categoryKey: 'hp',
      categoryLabel: 'Hit Points & Health',
      base: 'blood',
      format: 'svg',
      src: 'assets/icons/tw-dnd/hp/blood.svg',
      source: 'tw-dnd:hp/blood.svg',
    },
    {
      id: 'tw-dnd:hp:empty',
      name: 'Empty',
      categoryKey: 'hp',
      categoryLabel: 'Hit Points & Health',
      base: 'empty',
      format: 'svg',
      src: 'assets/icons/tw-dnd/hp/empty.svg',
      source: 'tw-dnd:hp/empty.svg',
    },
    {
      id: 'tw-dnd:hp:full',
      name: 'Full',
      categoryKey: 'hp',
      categoryLabel: 'Hit Points & Health',
      base: 'full',
      format: 'svg',
      src: 'assets/icons/tw-dnd/hp/full.svg',
      source: 'tw-dnd:hp/full.svg',
    },
    {
      id: 'tw-dnd:hp:half',
      name: 'Half',
      categoryKey: 'hp',
      categoryLabel: 'Hit Points & Health',
      base: 'half',
      format: 'svg',
      src: 'assets/icons/tw-dnd/hp/half.svg',
      source: 'tw-dnd:hp/half.svg',
    },
    {
      id: 'tw-dnd:hp:temp',
      name: 'Temp',
      categoryKey: 'hp',
      categoryLabel: 'Hit Points & Health',
      base: 'temp',
      format: 'svg',
      src: 'assets/icons/tw-dnd/hp/temp.svg',
      source: 'tw-dnd:hp/temp.svg',
    },
  ],
  'Locations & Structures': [
    {
      id: 'tw-dnd:location:bastion',
      name: 'Bastion',
      categoryKey: 'location',
      categoryLabel: 'Locations & Structures',
      base: 'bastion',
      format: 'svg',
      src: 'assets/icons/tw-dnd/location/bastion.svg',
      source: 'tw-dnd:location/bastion.svg',
    },
    {
      id: 'tw-dnd:location:camp',
      name: 'Camp',
      categoryKey: 'location',
      categoryLabel: 'Locations & Structures',
      base: 'camp',
      format: 'svg',
      src: 'assets/icons/tw-dnd/location/camp.svg',
      source: 'tw-dnd:location/camp.svg',
    },
    {
      id: 'tw-dnd:location:castle',
      name: 'Castle',
      categoryKey: 'location',
      categoryLabel: 'Locations & Structures',
      base: 'castle',
      format: 'svg',
      src: 'assets/icons/tw-dnd/location/castle.svg',
      source: 'tw-dnd:location/castle.svg',
    },
    {
      id: 'tw-dnd:location:dungeon',
      name: 'Dungeon',
      categoryKey: 'location',
      categoryLabel: 'Locations & Structures',
      base: 'dungeon',
      format: 'svg',
      src: 'assets/icons/tw-dnd/location/dungeon.svg',
      source: 'tw-dnd:location/dungeon.svg',
    },
    {
      id: 'tw-dnd:location:forest',
      name: 'Forest',
      categoryKey: 'location',
      categoryLabel: 'Locations & Structures',
      base: 'forest',
      format: 'svg',
      src: 'assets/icons/tw-dnd/location/forest.svg',
      source: 'tw-dnd:location/forest.svg',
    },
    {
      id: 'tw-dnd:location:hut',
      name: 'Hut',
      categoryKey: 'location',
      categoryLabel: 'Locations & Structures',
      base: 'hut',
      format: 'svg',
      src: 'assets/icons/tw-dnd/location/hut.svg',
      source: 'tw-dnd:location/hut.svg',
    },
    {
      id: 'tw-dnd:location:mountain',
      name: 'Mountain',
      categoryKey: 'location',
      categoryLabel: 'Locations & Structures',
      base: 'mountain',
      format: 'svg',
      src: 'assets/icons/tw-dnd/location/mountain.svg',
      source: 'tw-dnd:location/mountain.svg',
    },
    {
      id: 'tw-dnd:location:portal',
      name: 'Portal',
      categoryKey: 'location',
      categoryLabel: 'Locations & Structures',
      base: 'portal',
      format: 'svg',
      src: 'assets/icons/tw-dnd/location/portal.svg',
      source: 'tw-dnd:location/portal.svg',
    },
    {
      id: 'tw-dnd:location:tavern',
      name: 'Tavern',
      categoryKey: 'location',
      categoryLabel: 'Locations & Structures',
      base: 'tavern',
      format: 'svg',
      src: 'assets/icons/tw-dnd/location/tavern.svg',
      source: 'tw-dnd:location/tavern.svg',
    },
    {
      id: 'tw-dnd:location:tower',
      name: 'Tower',
      categoryKey: 'location',
      categoryLabel: 'Locations & Structures',
      base: 'tower',
      format: 'svg',
      src: 'assets/icons/tw-dnd/location/tower.svg',
      source: 'tw-dnd:location/tower.svg',
    },
    {
      id: 'tw-dnd:location:village',
      name: 'Village',
      categoryKey: 'location',
      categoryLabel: 'Locations & Structures',
      base: 'village',
      format: 'svg',
      src: 'assets/icons/tw-dnd/location/village.svg',
      source: 'tw-dnd:location/village.svg',
    },
  ],
  'Logos & Platforms': [
    {
      id: 'tw-dnd:logo:adventurers-league',
      name: 'Adventurers League',
      categoryKey: 'logo',
      categoryLabel: 'Logos & Platforms',
      base: 'adventurers-league',
      format: 'svg',
      src: 'assets/icons/tw-dnd/logo/adventurers-league.svg',
      source: 'tw-dnd:logo/adventurers-league.svg',
    },
    {
      id: 'tw-dnd:logo:critical-role',
      name: 'Critical Role',
      categoryKey: 'logo',
      categoryLabel: 'Logos & Platforms',
      base: 'critical-role',
      format: 'svg',
      src: 'assets/icons/tw-dnd/logo/critical-role.svg',
      source: 'tw-dnd:logo/critical-role.svg',
    },
    {
      id: 'tw-dnd:logo:dnd-beyond',
      name: 'D&D Beyond',
      categoryKey: 'logo',
      categoryLabel: 'Logos & Platforms',
      base: 'dnd-beyond',
      format: 'svg',
      src: 'assets/icons/tw-dnd/logo/dnd-beyond.svg',
      source: 'tw-dnd:logo/dnd-beyond.svg',
    },
    {
      id: 'tw-dnd:logo:dnd',
      name: 'Dungeons & Dragons',
      categoryKey: 'logo',
      categoryLabel: 'Logos & Platforms',
      base: 'dnd',
      format: 'svg',
      src: 'assets/icons/tw-dnd/logo/dnd.svg',
      source: 'tw-dnd:logo/dnd.svg',
    },
    {
      id: 'tw-dnd:logo:fantasy-grounds',
      name: 'Fantasy Grounds',
      categoryKey: 'logo',
      categoryLabel: 'Logos & Platforms',
      base: 'fantasy-grounds',
      format: 'svg',
      src: 'assets/icons/tw-dnd/logo/fantasy-grounds.svg',
      source: 'tw-dnd:logo/fantasy-grounds.svg',
    },
    {
      id: 'tw-dnd:logo:foundry',
      name: 'Foundry',
      categoryKey: 'logo',
      categoryLabel: 'Logos & Platforms',
      base: 'foundry',
      format: 'svg',
      src: 'assets/icons/tw-dnd/logo/foundry.svg',
      source: 'tw-dnd:logo/foundry.svg',
    },
    {
      id: 'tw-dnd:logo:owlbear-rodeo',
      name: 'Owlbear Rodeo',
      categoryKey: 'logo',
      categoryLabel: 'Logos & Platforms',
      base: 'owlbear-rodeo',
      format: 'svg',
      src: 'assets/icons/tw-dnd/logo/owlbear-rodeo.svg',
      source: 'tw-dnd:logo/owlbear-rodeo.svg',
    },
    {
      id: 'tw-dnd:logo:roll20',
      name: 'Roll20',
      categoryKey: 'logo',
      categoryLabel: 'Logos & Platforms',
      base: 'roll20',
      format: 'svg',
      src: 'assets/icons/tw-dnd/logo/roll20.svg',
      source: 'tw-dnd:logo/roll20.svg',
    },
    {
      id: 'tw-dnd:logo:tiddlywiki',
      name: 'Tiddlywiki',
      categoryKey: 'logo',
      categoryLabel: 'Logos & Platforms',
      base: 'tiddlywiki',
      format: 'svg',
      src: 'assets/icons/tw-dnd/logo/tiddlywiki.svg',
      source: 'tw-dnd:logo/tiddlywiki.svg',
    },
  ],
  'Monster Types': [
    {
      id: 'tw-dnd:monster:aberration',
      name: 'Aberration',
      categoryKey: 'monster',
      categoryLabel: 'Monster Types',
      base: 'aberration',
      format: 'svg',
      src: 'assets/icons/tw-dnd/monster/aberration.svg',
      source: 'tw-dnd:monster/aberration.svg',
    },
    {
      id: 'tw-dnd:monster:beast',
      name: 'Beast',
      categoryKey: 'monster',
      categoryLabel: 'Monster Types',
      base: 'beast',
      format: 'svg',
      src: 'assets/icons/tw-dnd/monster/beast.svg',
      source: 'tw-dnd:monster/beast.svg',
    },
    {
      id: 'tw-dnd:monster:celestial',
      name: 'Celestial',
      categoryKey: 'monster',
      categoryLabel: 'Monster Types',
      base: 'celestial',
      format: 'svg',
      src: 'assets/icons/tw-dnd/monster/celestial.svg',
      source: 'tw-dnd:monster/celestial.svg',
    },
    {
      id: 'tw-dnd:monster:construct',
      name: 'Construct',
      categoryKey: 'monster',
      categoryLabel: 'Monster Types',
      base: 'construct',
      format: 'svg',
      src: 'assets/icons/tw-dnd/monster/construct.svg',
      source: 'tw-dnd:monster/construct.svg',
    },
    {
      id: 'tw-dnd:monster:dragon',
      name: 'Dragon',
      categoryKey: 'monster',
      categoryLabel: 'Monster Types',
      base: 'dragon',
      format: 'svg',
      src: 'assets/icons/tw-dnd/monster/dragon.svg',
      source: 'tw-dnd:monster/dragon.svg',
    },
    {
      id: 'tw-dnd:monster:elemental',
      name: 'Elemental',
      categoryKey: 'monster',
      categoryLabel: 'Monster Types',
      base: 'elemental',
      format: 'svg',
      src: 'assets/icons/tw-dnd/monster/elemental.svg',
      source: 'tw-dnd:monster/elemental.svg',
    },
    {
      id: 'tw-dnd:monster:fae',
      name: 'Fae',
      categoryKey: 'monster',
      categoryLabel: 'Monster Types',
      base: 'fae',
      format: 'svg',
      src: 'assets/icons/tw-dnd/monster/fae.svg',
      source: 'tw-dnd:monster/fae.svg',
    },
    {
      id: 'tw-dnd:monster:fiend',
      name: 'Fiend',
      categoryKey: 'monster',
      categoryLabel: 'Monster Types',
      base: 'fiend',
      format: 'svg',
      src: 'assets/icons/tw-dnd/monster/fiend.svg',
      source: 'tw-dnd:monster/fiend.svg',
    },
    {
      id: 'tw-dnd:monster:giant',
      name: 'Giant',
      categoryKey: 'monster',
      categoryLabel: 'Monster Types',
      base: 'giant',
      format: 'svg',
      src: 'assets/icons/tw-dnd/monster/giant.svg',
      source: 'tw-dnd:monster/giant.svg',
    },
    {
      id: 'tw-dnd:monster:humanoid',
      name: 'Humanoid',
      categoryKey: 'monster',
      categoryLabel: 'Monster Types',
      base: 'humanoid',
      format: 'svg',
      src: 'assets/icons/tw-dnd/monster/humanoid.svg',
      source: 'tw-dnd:monster/humanoid.svg',
    },
    {
      id: 'tw-dnd:monster:monstrosity',
      name: 'Monstrosity',
      categoryKey: 'monster',
      categoryLabel: 'Monster Types',
      base: 'monstrosity',
      format: 'svg',
      src: 'assets/icons/tw-dnd/monster/monstrosity.svg',
      source: 'tw-dnd:monster/monstrosity.svg',
    },
    {
      id: 'tw-dnd:monster:ooze',
      name: 'Ooze',
      categoryKey: 'monster',
      categoryLabel: 'Monster Types',
      base: 'ooze',
      format: 'svg',
      src: 'assets/icons/tw-dnd/monster/ooze.svg',
      source: 'tw-dnd:monster/ooze.svg',
    },
    {
      id: 'tw-dnd:monster:plant',
      name: 'Plant',
      categoryKey: 'monster',
      categoryLabel: 'Monster Types',
      base: 'plant',
      format: 'svg',
      src: 'assets/icons/tw-dnd/monster/plant.svg',
      source: 'tw-dnd:monster/plant.svg',
    },
    {
      id: 'tw-dnd:monster:undead',
      name: 'Undead',
      categoryKey: 'monster',
      categoryLabel: 'Monster Types',
      base: 'undead',
      format: 'svg',
      src: 'assets/icons/tw-dnd/monster/undead.svg',
      source: 'tw-dnd:monster/undead.svg',
    },
  ],
  'Movement Modes': [
    {
      id: 'tw-dnd:movement:burrowing',
      name: 'Burrowing',
      categoryKey: 'movement',
      categoryLabel: 'Movement Modes',
      base: 'burrowing',
      format: 'svg',
      src: 'assets/icons/tw-dnd/movement/burrowing.svg',
      source: 'tw-dnd:movement/burrowing.svg',
    },
    {
      id: 'tw-dnd:movement:climbing',
      name: 'Climbing',
      categoryKey: 'movement',
      categoryLabel: 'Movement Modes',
      base: 'climbing',
      format: 'svg',
      src: 'assets/icons/tw-dnd/movement/climbing.svg',
      source: 'tw-dnd:movement/climbing.svg',
    },
    {
      id: 'tw-dnd:movement:flying',
      name: 'Flying',
      categoryKey: 'movement',
      categoryLabel: 'Movement Modes',
      base: 'flying',
      format: 'svg',
      src: 'assets/icons/tw-dnd/movement/flying.svg',
      source: 'tw-dnd:movement/flying.svg',
    },
    {
      id: 'tw-dnd:movement:swimming',
      name: 'Swimming',
      categoryKey: 'movement',
      categoryLabel: 'Movement Modes',
      base: 'swimming',
      format: 'svg',
      src: 'assets/icons/tw-dnd/movement/swimming.svg',
      source: 'tw-dnd:movement/swimming.svg',
    },
    {
      id: 'tw-dnd:movement:walking',
      name: 'Walking',
      categoryKey: 'movement',
      categoryLabel: 'Movement Modes',
      base: 'walking',
      format: 'svg',
      src: 'assets/icons/tw-dnd/movement/walking.svg',
      source: 'tw-dnd:movement/walking.svg',
    },
  ],
  'Proficiency Levels': [
    {
      id: 'tw-dnd:proficiency:expertise',
      name: 'Expertise',
      categoryKey: 'proficiency',
      categoryLabel: 'Proficiency Levels',
      base: 'expertise',
      format: 'svg',
      src: 'assets/icons/tw-dnd/proficiency/expertise.svg',
      source: 'tw-dnd:proficiency/expertise.svg',
    },
    {
      id: 'tw-dnd:proficiency:half',
      name: 'Half',
      categoryKey: 'proficiency',
      categoryLabel: 'Proficiency Levels',
      base: 'half',
      format: 'svg',
      src: 'assets/icons/tw-dnd/proficiency/half.svg',
      source: 'tw-dnd:proficiency/half.svg',
    },
    {
      id: 'tw-dnd:proficiency:proficient',
      name: 'Proficient',
      categoryKey: 'proficiency',
      categoryLabel: 'Proficiency Levels',
      base: 'proficient',
      format: 'svg',
      src: 'assets/icons/tw-dnd/proficiency/proficient.svg',
      source: 'tw-dnd:proficiency/proficient.svg',
    },
    {
      id: 'tw-dnd:proficiency:unskilled',
      name: 'Unskilled',
      categoryKey: 'proficiency',
      categoryLabel: 'Proficiency Levels',
      base: 'unskilled',
      format: 'svg',
      src: 'assets/icons/tw-dnd/proficiency/unskilled.svg',
      source: 'tw-dnd:proficiency/unskilled.svg',
    },
  ],
  'Skills': [
    {
      id: 'tw-dnd:skill:acrobatics',
      name: 'Acrobatics',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'acrobatics',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/acrobatics.svg',
      source: 'tw-dnd:skill/acrobatics.svg',
    },
    {
      id: 'tw-dnd:skill:animal-handling',
      name: 'Animal Handling',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'animal-handling',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/animal-handling.svg',
      source: 'tw-dnd:skill/animal-handling.svg',
    },
    {
      id: 'tw-dnd:skill:arcana',
      name: 'Arcana',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'arcana',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/arcana.svg',
      source: 'tw-dnd:skill/arcana.svg',
    },
    {
      id: 'tw-dnd:skill:athletics',
      name: 'Athletics',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'athletics',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/athletics.svg',
      source: 'tw-dnd:skill/athletics.svg',
    },
    {
      id: 'tw-dnd:skill:deception',
      name: 'Deception',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'deception',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/deception.svg',
      source: 'tw-dnd:skill/deception.svg',
    },
    {
      id: 'tw-dnd:skill:history',
      name: 'History',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'history',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/history.svg',
      source: 'tw-dnd:skill/history.svg',
    },
    {
      id: 'tw-dnd:skill:insight',
      name: 'Insight',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'insight',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/insight.svg',
      source: 'tw-dnd:skill/insight.svg',
    },
    {
      id: 'tw-dnd:skill:intimidation',
      name: 'Intimidation',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'intimidation',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/intimidation.svg',
      source: 'tw-dnd:skill/intimidation.svg',
    },
    {
      id: 'tw-dnd:skill:investigation',
      name: 'Investigation',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'investigation',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/investigation.svg',
      source: 'tw-dnd:skill/investigation.svg',
    },
    {
      id: 'tw-dnd:skill:medicine',
      name: 'Medicine',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'medicine',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/medicine.svg',
      source: 'tw-dnd:skill/medicine.svg',
    },
    {
      id: 'tw-dnd:skill:nature',
      name: 'Nature',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'nature',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/nature.svg',
      source: 'tw-dnd:skill/nature.svg',
    },
    {
      id: 'tw-dnd:skill:perception',
      name: 'Perception',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'perception',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/perception.svg',
      source: 'tw-dnd:skill/perception.svg',
    },
    {
      id: 'tw-dnd:skill:performance',
      name: 'Performance',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'performance',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/performance.svg',
      source: 'tw-dnd:skill/performance.svg',
    },
    {
      id: 'tw-dnd:skill:persuasion',
      name: 'Persuasion',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'persuasion',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/persuasion.svg',
      source: 'tw-dnd:skill/persuasion.svg',
    },
    {
      id: 'tw-dnd:skill:religion',
      name: 'Religion',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'religion',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/religion.svg',
      source: 'tw-dnd:skill/religion.svg',
    },
    {
      id: 'tw-dnd:skill:sleight-of-hand',
      name: 'Sleight Of Hand',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'sleight-of-hand',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/sleight-of-hand.svg',
      source: 'tw-dnd:skill/sleight-of-hand.svg',
    },
    {
      id: 'tw-dnd:skill:stealth',
      name: 'Stealth',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'stealth',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/stealth.svg',
      source: 'tw-dnd:skill/stealth.svg',
    },
    {
      id: 'tw-dnd:skill:survival',
      name: 'Survival',
      categoryKey: 'skill',
      categoryLabel: 'Skills',
      base: 'survival',
      format: 'svg',
      src: 'assets/icons/tw-dnd/skill/survival.svg',
      source: 'tw-dnd:skill/survival.svg',
    },
  ],
  'Spell Slots': [
    {
      id: 'tw-dnd:slot:slot-1-0',
      name: 'Level 1 Slot (0/1)',
      categoryKey: 'slot',
      categoryLabel: 'Spell Slots',
      base: 'slot-1-0',
      format: 'svg',
      src: 'assets/icons/tw-dnd/slot/slot-1-0.svg',
      source: 'tw-dnd:slot/slot-1-0.svg',
    },
    {
      id: 'tw-dnd:slot:slot-1-1',
      name: 'Level 1 Slot (1/1)',
      categoryKey: 'slot',
      categoryLabel: 'Spell Slots',
      base: 'slot-1-1',
      format: 'svg',
      src: 'assets/icons/tw-dnd/slot/slot-1-1.svg',
      source: 'tw-dnd:slot/slot-1-1.svg',
    },
    {
      id: 'tw-dnd:slot:slot-2-0',
      name: 'Level 2 Slot (0/2)',
      categoryKey: 'slot',
      categoryLabel: 'Spell Slots',
      base: 'slot-2-0',
      format: 'svg',
      src: 'assets/icons/tw-dnd/slot/slot-2-0.svg',
      source: 'tw-dnd:slot/slot-2-0.svg',
    },
    {
      id: 'tw-dnd:slot:slot-2-1',
      name: 'Level 2 Slot (1/2)',
      categoryKey: 'slot',
      categoryLabel: 'Spell Slots',
      base: 'slot-2-1',
      format: 'svg',
      src: 'assets/icons/tw-dnd/slot/slot-2-1.svg',
      source: 'tw-dnd:slot/slot-2-1.svg',
    },
    {
      id: 'tw-dnd:slot:slot-2-2',
      name: 'Level 2 Slot (2/2)',
      categoryKey: 'slot',
      categoryLabel: 'Spell Slots',
      base: 'slot-2-2',
      format: 'svg',
      src: 'assets/icons/tw-dnd/slot/slot-2-2.svg',
      source: 'tw-dnd:slot/slot-2-2.svg',
    },
    {
      id: 'tw-dnd:slot:slot-3-0',
      name: 'Level 3 Slot (0/3)',
      categoryKey: 'slot',
      categoryLabel: 'Spell Slots',
      base: 'slot-3-0',
      format: 'svg',
      src: 'assets/icons/tw-dnd/slot/slot-3-0.svg',
      source: 'tw-dnd:slot/slot-3-0.svg',
    },
    {
      id: 'tw-dnd:slot:slot-3-1',
      name: 'Level 3 Slot (1/3)',
      categoryKey: 'slot',
      categoryLabel: 'Spell Slots',
      base: 'slot-3-1',
      format: 'svg',
      src: 'assets/icons/tw-dnd/slot/slot-3-1.svg',
      source: 'tw-dnd:slot/slot-3-1.svg',
    },
    {
      id: 'tw-dnd:slot:slot-3-2',
      name: 'Level 3 Slot (2/3)',
      categoryKey: 'slot',
      categoryLabel: 'Spell Slots',
      base: 'slot-3-2',
      format: 'svg',
      src: 'assets/icons/tw-dnd/slot/slot-3-2.svg',
      source: 'tw-dnd:slot/slot-3-2.svg',
    },
    {
      id: 'tw-dnd:slot:slot-3-3',
      name: 'Level 3 Slot (3/3)',
      categoryKey: 'slot',
      categoryLabel: 'Spell Slots',
      base: 'slot-3-3',
      format: 'svg',
      src: 'assets/icons/tw-dnd/slot/slot-3-3.svg',
      source: 'tw-dnd:slot/slot-3-3.svg',
    },
    {
      id: 'tw-dnd:slot:slot-4-0',
      name: 'Level 4 Slot (0/4)',
      categoryKey: 'slot',
      categoryLabel: 'Spell Slots',
      base: 'slot-4-0',
      format: 'svg',
      src: 'assets/icons/tw-dnd/slot/slot-4-0.svg',
      source: 'tw-dnd:slot/slot-4-0.svg',
    },
    {
      id: 'tw-dnd:slot:slot-4-1',
      name: 'Level 4 Slot (1/4)',
      categoryKey: 'slot',
      categoryLabel: 'Spell Slots',
      base: 'slot-4-1',
      format: 'svg',
      src: 'assets/icons/tw-dnd/slot/slot-4-1.svg',
      source: 'tw-dnd:slot/slot-4-1.svg',
    },
    {
      id: 'tw-dnd:slot:slot-4-2',
      name: 'Level 4 Slot (2/4)',
      categoryKey: 'slot',
      categoryLabel: 'Spell Slots',
      base: 'slot-4-2',
      format: 'svg',
      src: 'assets/icons/tw-dnd/slot/slot-4-2.svg',
      source: 'tw-dnd:slot/slot-4-2.svg',
    },
    {
      id: 'tw-dnd:slot:slot-4-3',
      name: 'Level 4 Slot (3/4)',
      categoryKey: 'slot',
      categoryLabel: 'Spell Slots',
      base: 'slot-4-3',
      format: 'svg',
      src: 'assets/icons/tw-dnd/slot/slot-4-3.svg',
      source: 'tw-dnd:slot/slot-4-3.svg',
    },
    {
      id: 'tw-dnd:slot:slot-4-4',
      name: 'Level 4 Slot (4/4)',
      categoryKey: 'slot',
      categoryLabel: 'Spell Slots',
      base: 'slot-4-4',
      format: 'svg',
      src: 'assets/icons/tw-dnd/slot/slot-4-4.svg',
      source: 'tw-dnd:slot/slot-4-4.svg',
    },
  ],
  'Spell Schools & Casting': [
    {
      id: 'tw-dnd:spell:abjuration',
      name: 'Abjuration',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'abjuration',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/abjuration.svg',
      source: 'tw-dnd:spell/abjuration.svg',
    },
    {
      id: 'tw-dnd:spell:concentration',
      name: 'Concentration',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'concentration',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/concentration.svg',
      source: 'tw-dnd:spell/concentration.svg',
    },
    {
      id: 'tw-dnd:spell:conjuration',
      name: 'Conjuration',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'conjuration',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/conjuration.svg',
      source: 'tw-dnd:spell/conjuration.svg',
    },
    {
      id: 'tw-dnd:spell:consumed',
      name: 'Consumed',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'consumed',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/consumed.svg',
      source: 'tw-dnd:spell/consumed.svg',
    },
    {
      id: 'tw-dnd:spell:cost',
      name: 'Cost',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'cost',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/cost.svg',
      source: 'tw-dnd:spell/cost.svg',
    },
    {
      id: 'tw-dnd:spell:divination',
      name: 'Divination',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'divination',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/divination.svg',
      source: 'tw-dnd:spell/divination.svg',
    },
    {
      id: 'tw-dnd:spell:enchantment',
      name: 'Enchantment',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'enchantment',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/enchantment.svg',
      source: 'tw-dnd:spell/enchantment.svg',
    },
    {
      id: 'tw-dnd:spell:evocation',
      name: 'Evocation',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'evocation',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/evocation.svg',
      source: 'tw-dnd:spell/evocation.svg',
    },
    {
      id: 'tw-dnd:spell:illusion',
      name: 'Illusion',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'illusion',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/illusion.svg',
      source: 'tw-dnd:spell/illusion.svg',
    },
    {
      id: 'tw-dnd:spell:instantaneous',
      name: 'Instantaneous',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'instantaneous',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/instantaneous.svg',
      source: 'tw-dnd:spell/instantaneous.svg',
    },
    {
      id: 'tw-dnd:spell:material',
      name: 'Material',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'material',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/material.svg',
      source: 'tw-dnd:spell/material.svg',
    },
    {
      id: 'tw-dnd:spell:necromancy',
      name: 'Necromancy',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'necromancy',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/necromancy.svg',
      source: 'tw-dnd:spell/necromancy.svg',
    },
    {
      id: 'tw-dnd:spell:octagon',
      name: 'Octagon',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'octagon',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/octagon.svg',
      source: 'tw-dnd:spell/octagon.svg',
    },
    {
      id: 'tw-dnd:spell:ritual',
      name: 'Ritual',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'ritual',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/ritual.svg',
      source: 'tw-dnd:spell/ritual.svg',
    },
    {
      id: 'tw-dnd:spell:somatic',
      name: 'Somatic',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'somatic',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/somatic.svg',
      source: 'tw-dnd:spell/somatic.svg',
    },
    {
      id: 'tw-dnd:spell:transmutation',
      name: 'Transmutation',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'transmutation',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/transmutation.svg',
      source: 'tw-dnd:spell/transmutation.svg',
    },
    {
      id: 'tw-dnd:spell:upcast',
      name: 'Upcast',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'upcast',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/upcast.svg',
      source: 'tw-dnd:spell/upcast.svg',
    },
    {
      id: 'tw-dnd:spell:vocal',
      name: 'Vocal',
      categoryKey: 'spell',
      categoryLabel: 'Spell Schools & Casting',
      base: 'vocal',
      format: 'svg',
      src: 'assets/icons/tw-dnd/spell/vocal.svg',
      source: 'tw-dnd:spell/vocal.svg',
    },
  ],
  'Target & Area Shapes': [
    {
      id: 'tw-dnd:target:circle',
      name: 'Circle',
      categoryKey: 'target',
      categoryLabel: 'Target & Area Shapes',
      base: 'circle',
      format: 'svg',
      src: 'assets/icons/tw-dnd/target/circle.svg',
      source: 'tw-dnd:target/circle.svg',
    },
    {
      id: 'tw-dnd:target:cone',
      name: 'Cone',
      categoryKey: 'target',
      categoryLabel: 'Target & Area Shapes',
      base: 'cone',
      format: 'svg',
      src: 'assets/icons/tw-dnd/target/cone.svg',
      source: 'tw-dnd:target/cone.svg',
    },
    {
      id: 'tw-dnd:target:cube',
      name: 'Cube',
      categoryKey: 'target',
      categoryLabel: 'Target & Area Shapes',
      base: 'cube',
      format: 'svg',
      src: 'assets/icons/tw-dnd/target/cube.svg',
      source: 'tw-dnd:target/cube.svg',
    },
    {
      id: 'tw-dnd:target:cylinder',
      name: 'Cylinder',
      categoryKey: 'target',
      categoryLabel: 'Target & Area Shapes',
      base: 'cylinder',
      format: 'svg',
      src: 'assets/icons/tw-dnd/target/cylinder.svg',
      source: 'tw-dnd:target/cylinder.svg',
    },
    {
      id: 'tw-dnd:target:emanation',
      name: 'Emanation',
      categoryKey: 'target',
      categoryLabel: 'Target & Area Shapes',
      base: 'emanation',
      format: 'svg',
      src: 'assets/icons/tw-dnd/target/emanation.svg',
      source: 'tw-dnd:target/emanation.svg',
    },
    {
      id: 'tw-dnd:target:line',
      name: 'Line',
      categoryKey: 'target',
      categoryLabel: 'Target & Area Shapes',
      base: 'line',
      format: 'svg',
      src: 'assets/icons/tw-dnd/target/line.svg',
      source: 'tw-dnd:target/line.svg',
    },
    {
      id: 'tw-dnd:target:self',
      name: 'Self',
      categoryKey: 'target',
      categoryLabel: 'Target & Area Shapes',
      base: 'self',
      format: 'svg',
      src: 'assets/icons/tw-dnd/target/self.svg',
      source: 'tw-dnd:target/self.svg',
    },
    {
      id: 'tw-dnd:target:sphere',
      name: 'Sphere',
      categoryKey: 'target',
      categoryLabel: 'Target & Area Shapes',
      base: 'sphere',
      format: 'svg',
      src: 'assets/icons/tw-dnd/target/sphere.svg',
      source: 'tw-dnd:target/sphere.svg',
    },
    {
      id: 'tw-dnd:target:square',
      name: 'Square',
      categoryKey: 'target',
      categoryLabel: 'Target & Area Shapes',
      base: 'square',
      format: 'svg',
      src: 'assets/icons/tw-dnd/target/square.svg',
      source: 'tw-dnd:target/square.svg',
    },
    {
      id: 'tw-dnd:target:touch',
      name: 'Touch',
      categoryKey: 'target',
      categoryLabel: 'Target & Area Shapes',
      base: 'touch',
      format: 'svg',
      src: 'assets/icons/tw-dnd/target/touch.svg',
      source: 'tw-dnd:target/touch.svg',
    },
    {
      id: 'tw-dnd:target:wall',
      name: 'Wall',
      categoryKey: 'target',
      categoryLabel: 'Target & Area Shapes',
      base: 'wall',
      format: 'svg',
      src: 'assets/icons/tw-dnd/target/wall.svg',
      source: 'tw-dnd:target/wall.svg',
    },
  ],
  'Utility & System': [
    {
      id: 'tw-dnd:util:bubble',
      name: 'Bubble',
      categoryKey: 'util',
      categoryLabel: 'Utility & System',
      base: 'bubble',
      format: 'svg',
      src: 'assets/icons/tw-dnd/util/bubble.svg',
      source: 'tw-dnd:util/bubble.svg',
    },
    {
      id: 'tw-dnd:util:build',
      name: 'Build',
      categoryKey: 'util',
      categoryLabel: 'Utility & System',
      base: 'build',
      format: 'svg',
      src: 'assets/icons/tw-dnd/util/build.svg',
      source: 'tw-dnd:util/build.svg',
    },
    {
      id: 'tw-dnd:util:cog',
      name: 'Cog',
      categoryKey: 'util',
      categoryLabel: 'Utility & System',
      base: 'cog',
      format: 'svg',
      src: 'assets/icons/tw-dnd/util/cog.svg',
      source: 'tw-dnd:util/cog.svg',
    },
    {
      id: 'tw-dnd:util:cross',
      name: 'Cross',
      categoryKey: 'util',
      categoryLabel: 'Utility & System',
      base: 'cross',
      format: 'svg',
      src: 'assets/icons/tw-dnd/util/cross.svg',
      source: 'tw-dnd:util/cross.svg',
    },
    {
      id: 'tw-dnd:util:home',
      name: 'Home',
      categoryKey: 'util',
      categoryLabel: 'Utility & System',
      base: 'home',
      format: 'svg',
      src: 'assets/icons/tw-dnd/util/home.svg',
      source: 'tw-dnd:util/home.svg',
    },
    {
      id: 'tw-dnd:util:not-applicable',
      name: 'Not Applicable (N/A)',
      categoryKey: 'util',
      categoryLabel: 'Utility & System',
      base: 'not-applicable',
      format: 'svg',
      src: 'assets/icons/tw-dnd/util/not-applicable.svg',
      source: 'tw-dnd:util/not-applicable.svg',
    },
    {
      id: 'tw-dnd:util:search',
      name: 'Search',
      categoryKey: 'util',
      categoryLabel: 'Utility & System',
      base: 'search',
      format: 'svg',
      src: 'assets/icons/tw-dnd/util/search.svg',
      source: 'tw-dnd:util/search.svg',
    },
    {
      id: 'tw-dnd:util:star',
      name: 'Star',
      categoryKey: 'util',
      categoryLabel: 'Utility & System',
      base: 'star',
      format: 'svg',
      src: 'assets/icons/tw-dnd/util/star.svg',
      source: 'tw-dnd:util/star.svg',
    },
    {
      id: 'tw-dnd:util:tick',
      name: 'Tick',
      categoryKey: 'util',
      categoryLabel: 'Utility & System',
      base: 'tick',
      format: 'svg',
      src: 'assets/icons/tw-dnd/util/tick.svg',
      source: 'tw-dnd:util/tick.svg',
    },
    {
      id: 'tw-dnd:util:trade',
      name: 'Trade',
      categoryKey: 'util',
      categoryLabel: 'Utility & System',
      base: 'trade',
      format: 'svg',
      src: 'assets/icons/tw-dnd/util/trade.svg',
      source: 'tw-dnd:util/trade.svg',
    },
  ],
  'Weapon Types': [
    {
      id: 'tw-dnd:weapon:arrow',
      name: 'Arrow',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'arrow',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/arrow.svg',
      source: 'tw-dnd:weapon/arrow.svg',
    },
    {
      id: 'tw-dnd:weapon:battleaxe',
      name: 'Battleaxe',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'battleaxe',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/battleaxe.svg',
      source: 'tw-dnd:weapon/battleaxe.svg',
    },
    {
      id: 'tw-dnd:weapon:bow',
      name: 'Bow',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'bow',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/bow.svg',
      source: 'tw-dnd:weapon/bow.svg',
    },
    {
      id: 'tw-dnd:weapon:club',
      name: 'Club',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'club',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/club.svg',
      source: 'tw-dnd:weapon/club.svg',
    },
    {
      id: 'tw-dnd:weapon:crossbow',
      name: 'Crossbow',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'crossbow',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/crossbow.svg',
      source: 'tw-dnd:weapon/crossbow.svg',
    },
    {
      id: 'tw-dnd:weapon:dagger',
      name: 'Dagger',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'dagger',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/dagger.svg',
      source: 'tw-dnd:weapon/dagger.svg',
    },
    {
      id: 'tw-dnd:weapon:flail',
      name: 'Flail',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'flail',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/flail.svg',
      source: 'tw-dnd:weapon/flail.svg',
    },
    {
      id: 'tw-dnd:weapon:glaive',
      name: 'Glaive',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'glaive',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/glaive.svg',
      source: 'tw-dnd:weapon/glaive.svg',
    },
    {
      id: 'tw-dnd:weapon:halberd',
      name: 'Halberd',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'halberd',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/halberd.svg',
      source: 'tw-dnd:weapon/halberd.svg',
    },
    {
      id: 'tw-dnd:weapon:hammer',
      name: 'Hammer',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'hammer',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/hammer.svg',
      source: 'tw-dnd:weapon/hammer.svg',
    },
    {
      id: 'tw-dnd:weapon:handaxe',
      name: 'Handaxe',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'handaxe',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/handaxe.svg',
      source: 'tw-dnd:weapon/handaxe.svg',
    },
    {
      id: 'tw-dnd:weapon:lance',
      name: 'Lance',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'lance',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/lance.svg',
      source: 'tw-dnd:weapon/lance.svg',
    },
    {
      id: 'tw-dnd:weapon:mace',
      name: 'Mace',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'mace',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/mace.svg',
      source: 'tw-dnd:weapon/mace.svg',
    },
    {
      id: 'tw-dnd:weapon:morningstar',
      name: 'Morningstar',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'morningstar',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/morningstar.svg',
      source: 'tw-dnd:weapon/morningstar.svg',
    },
    {
      id: 'tw-dnd:weapon:musket',
      name: 'Musket',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'musket',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/musket.svg',
      source: 'tw-dnd:weapon/musket.svg',
    },
    {
      id: 'tw-dnd:weapon:pike',
      name: 'Pike',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'pike',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/pike.svg',
      source: 'tw-dnd:weapon/pike.svg',
    },
    {
      id: 'tw-dnd:weapon:pistol',
      name: 'Pistol',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'pistol',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/pistol.svg',
      source: 'tw-dnd:weapon/pistol.svg',
    },
    {
      id: 'tw-dnd:weapon:rapier',
      name: 'Rapier',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'rapier',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/rapier.svg',
      source: 'tw-dnd:weapon/rapier.svg',
    },
    {
      id: 'tw-dnd:weapon:scimitar',
      name: 'Scimitar',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'scimitar',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/scimitar.svg',
      source: 'tw-dnd:weapon/scimitar.svg',
    },
    {
      id: 'tw-dnd:weapon:sickle',
      name: 'Sickle',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'sickle',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/sickle.svg',
      source: 'tw-dnd:weapon/sickle.svg',
    },
    {
      id: 'tw-dnd:weapon:sling',
      name: 'Sling',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'sling',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/sling.svg',
      source: 'tw-dnd:weapon/sling.svg',
    },
    {
      id: 'tw-dnd:weapon:spear',
      name: 'Spear',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'spear',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/spear.svg',
      source: 'tw-dnd:weapon/spear.svg',
    },
    {
      id: 'tw-dnd:weapon:staff',
      name: 'Staff',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'staff',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/staff.svg',
      source: 'tw-dnd:weapon/staff.svg',
    },
    {
      id: 'tw-dnd:weapon:strike',
      name: 'Strike',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'strike',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/strike.svg',
      source: 'tw-dnd:weapon/strike.svg',
    },
    {
      id: 'tw-dnd:weapon:sword',
      name: 'Sword',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'sword',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/sword.svg',
      source: 'tw-dnd:weapon/sword.svg',
    },
    {
      id: 'tw-dnd:weapon:trident',
      name: 'Trident',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'trident',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/trident.svg',
      source: 'tw-dnd:weapon/trident.svg',
    },
    {
      id: 'tw-dnd:weapon:whip',
      name: 'Whip',
      categoryKey: 'weapon',
      categoryLabel: 'Weapon Types',
      base: 'whip',
      format: 'svg',
      src: 'assets/icons/tw-dnd/weapon/whip.svg',
      source: 'tw-dnd:weapon/whip.svg',
    },
  ],
  'Roll20 Token Markers': [
    {
      id: 'tw-dnd:roll20:advantage',
      name: 'Advantage',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'advantage',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/advantage.png',
      source: 'tw-dnd:roll20/advantage.png',
    },
    {
      id: 'tw-dnd:roll20:attacked-adv',
      name: 'Advantage when Attacked',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'attacked-adv',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/attacked-adv.png',
      source: 'tw-dnd:roll20/attacked-adv.png',
    },
    {
      id: 'tw-dnd:roll20:attacked-dis',
      name: 'Disadvantage when Attacked',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'attacked-dis',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/attacked-dis.png',
      source: 'tw-dnd:roll20/attacked-dis.png',
    },
    {
      id: 'tw-dnd:roll20:attacking-adv',
      name: 'Advantage when Attacking',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'attacking-adv',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/attacking-adv.png',
      source: 'tw-dnd:roll20/attacking-adv.png',
    },
    {
      id: 'tw-dnd:roll20:attacking-dis',
      name: 'Disadvantage when Attacking',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'attacking-dis',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/attacking-dis.png',
      source: 'tw-dnd:roll20/attacking-dis.png',
    },
    {
      id: 'tw-dnd:roll20:blinded',
      name: 'Blinded',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'blinded',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/blinded.png',
      source: 'tw-dnd:roll20/blinded.png',
    },
    {
      id: 'tw-dnd:roll20:bloodied',
      name: 'Bloodied',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'bloodied',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/bloodied.png',
      source: 'tw-dnd:roll20/bloodied.png',
    },
    {
      id: 'tw-dnd:roll20:burrowing',
      name: 'Burrowing',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'burrowing',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/burrowing.png',
      source: 'tw-dnd:roll20/burrowing.png',
    },
    {
      id: 'tw-dnd:roll20:charmed',
      name: 'Charmed',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'charmed',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/charmed.png',
      source: 'tw-dnd:roll20/charmed.png',
    },
    {
      id: 'tw-dnd:roll20:climbing',
      name: 'Climbing',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'climbing',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/climbing.png',
      source: 'tw-dnd:roll20/climbing.png',
    },
    {
      id: 'tw-dnd:roll20:concentration-1',
      name: 'Concentrating (Variant 1)',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'concentration-1',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/concentration-1.png',
      source: 'tw-dnd:roll20/concentration-1.png',
    },
    {
      id: 'tw-dnd:roll20:concentration-2',
      name: 'Concentrating (Variant 2)',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'concentration-2',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/concentration-2.png',
      source: 'tw-dnd:roll20/concentration-2.png',
    },
    {
      id: 'tw-dnd:roll20:deafened',
      name: 'Deafened',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'deafened',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/deafened.png',
      source: 'tw-dnd:roll20/deafened.png',
    },
    {
      id: 'tw-dnd:roll20:disadvantage',
      name: 'Disadvantage',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'disadvantage',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/disadvantage.png',
      source: 'tw-dnd:roll20/disadvantage.png',
    },
    {
      id: 'tw-dnd:roll20:flying',
      name: 'Flying',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'flying',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/flying.png',
      source: 'tw-dnd:roll20/flying.png',
    },
    {
      id: 'tw-dnd:roll20:frightened',
      name: 'Frightened',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'frightened',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/frightened.png',
      source: 'tw-dnd:roll20/frightened.png',
    },
    {
      id: 'tw-dnd:roll20:grappled',
      name: 'Grappled',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'grappled',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/grappled.png',
      source: 'tw-dnd:roll20/grappled.png',
    },
    {
      id: 'tw-dnd:roll20:incapacitated',
      name: 'Incapacitated',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'incapacitated',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/incapacitated.png',
      source: 'tw-dnd:roll20/incapacitated.png',
    },
    {
      id: 'tw-dnd:roll20:invisible',
      name: 'Invisible',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'invisible',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/invisible.png',
      source: 'tw-dnd:roll20/invisible.png',
    },
    {
      id: 'tw-dnd:roll20:paralyzed',
      name: 'Paralyzed',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'paralyzed',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/paralyzed.png',
      source: 'tw-dnd:roll20/paralyzed.png',
    },
    {
      id: 'tw-dnd:roll20:petrified',
      name: 'Petrified',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'petrified',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/petrified.png',
      source: 'tw-dnd:roll20/petrified.png',
    },
    {
      id: 'tw-dnd:roll20:poisoned',
      name: 'Poisoned',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'poisoned',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/poisoned.png',
      source: 'tw-dnd:roll20/poisoned.png',
    },
    {
      id: 'tw-dnd:roll20:prone',
      name: 'Prone',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'prone',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/prone.png',
      source: 'tw-dnd:roll20/prone.png',
    },
    {
      id: 'tw-dnd:roll20:restrained',
      name: 'Restrained',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'restrained',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/restrained.png',
      source: 'tw-dnd:roll20/restrained.png',
    },
    {
      id: 'tw-dnd:roll20:saving-adv',
      name: 'Advantage on Saves',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'saving-adv',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/saving-adv.png',
      source: 'tw-dnd:roll20/saving-adv.png',
    },
    {
      id: 'tw-dnd:roll20:saving-dis',
      name: 'Disadvantage on Saves',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'saving-dis',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/saving-dis.png',
      source: 'tw-dnd:roll20/saving-dis.png',
    },
    {
      id: 'tw-dnd:roll20:silenced',
      name: 'Silenced',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'silenced',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/silenced.png',
      source: 'tw-dnd:roll20/silenced.png',
    },
    {
      id: 'tw-dnd:roll20:sleep',
      name: 'Sleep',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'sleep',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/sleep.png',
      source: 'tw-dnd:roll20/sleep.png',
    },
    {
      id: 'tw-dnd:roll20:stunned',
      name: 'Stunned',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'stunned',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/stunned.png',
      source: 'tw-dnd:roll20/stunned.png',
    },
    {
      id: 'tw-dnd:roll20:swimming',
      name: 'Swimming',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'swimming',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/swimming.png',
      source: 'tw-dnd:roll20/swimming.png',
    },
    {
      id: 'tw-dnd:roll20:unconscious',
      name: 'Unconscious',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'unconscious',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/unconscious.png',
      source: 'tw-dnd:roll20/unconscious.png',
    },
    {
      id: 'tw-dnd:roll20:walking',
      name: 'Walking',
      categoryKey: 'roll20',
      categoryLabel: 'Roll20 Token Markers',
      base: 'walking',
      format: 'png',
      src: 'assets/icons/tw-dnd/roll20/walking.png',
      source: 'tw-dnd:roll20/walking.png',
    },
  ],
};

// ============================================================================
// Complete Flat Icon Inventory
// ============================================================================
// A single list of all 318 icons for quick searching and batch filtering.
// ============================================================================

export const TW_DND_ICONS: TwDndIcon[] = Object.values(TW_DND_CATEGORIES).flat();
