// scripts/spell-icons/generate-gemini.mjs
//
// Generate spell icons with the Gemini API, directly.
//
// WHY NOT JULES: the Jules pilot (2026-07-14) produced 9 files per spell that were
// 88-94% byte-similar to each other — the same arcane-circle scaffold with a tiny
// glyph swapped, and v3 added nothing over v2. A coding agent writing files in one
// shot has no pressure to make the concepts actually differ.
//
// WHAT THIS DOES DIFFERENTLY:
//   1. Each icon is its own API call, so we control every one.
//   2. TRUE iteration: v2 is generated by feeding v1 back and demanding a real
//      change; v3 likewise from v2. The model SEES its previous attempt.
//   3. FORCED distinctness: when drafting concept N, we show the model the concepts
//      it already used and forbid reusing their composition or framing.
//
// Output: public/assets/icons/spells/{spell-id}/c{1-3}-v{1-3}.svg  (9 per spell)
//
// Key: Windows Credential Manager "AgentMatrix/Google/GEMINI_API_KEY" (or env
// GEMINI_API_KEY). Never printed.
//
// Usage:
//   node scripts/spell-icons/generate-gemini.mjs --batch 0
//   node scripts/spell-icons/generate-gemini.mjs --spells acid-splash,alarm
//   node scripts/spell-icons/generate-gemini.mjs --batch 0 --model gemini-3.5-flash
//   node scripts/spell-icons/generate-gemini.mjs --batch 0 --dry-run
//
// Zero deps: Node built-ins + global fetch.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readWinCred } from '../../tools/groq-proxy/proxy.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..', '..');
const MANIFEST = path.join(REPO_ROOT, '.agent', 'scratch', 'jules-icons', 'manifest.json');
const OUT_ROOT = path.join(REPO_ROOT, 'public', 'assets', 'icons', 'spells');

const CRED_TARGET = 'AgentMatrix/Google/GEMINI_API_KEY';
const API = 'https://generativelanguage.googleapis.com/v1beta/models';

const SCHOOL_COLORS = {
  evocation: '#F87171', abjuration: '#60A5FA', divination: '#2DD4BF',
  conjuration: '#818CF8', illusion: '#C084FC', transmutation: '#FBBF24',
  necromancy: '#34D399',
};
const colorFor = (s) => SCHOOL_COLORS[String(s || '').toLowerCase()] || '#94A3B8';

const arg = (n, d) => { const i = process.argv.indexOf(n); return i !== -1 && process.argv[i + 1] !== undefined ? process.argv[i + 1] : d; };
const has = (n) => process.argv.includes(n);

const STYLE = `STYLE RULES (all versions):
- Exactly one root element: <svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">.
- Self-contained: no <script>, no external hrefs, no fonts, no <image>.
- Hardcoded hex colors only. Never use currentColor.
- Rich and readable at 64px: use gradients (radialGradient/linearGradient) and a soft
  glow (feGaussianBlur + feMerge). Depth via light and dark shades of the main color.
- It must READ as the spell at a glance. Depict what the spell actually DOES.
- Output ONLY the SVG markup. No markdown fences, no commentary, no explanation.`;

function draftPrompt(spell, color, conceptNo, priorConcepts) {
  const avoid = priorConcepts.length
    ? `\nCONCEPTS ALREADY USED FOR THIS SPELL — you MUST NOT repeat them:\n${priorConcepts.map((c, i) => `  Concept ${i + 1}: ${c}`).join('\n')}\nYour concept ${conceptNo} must be a fundamentally DIFFERENT visual idea: a different subject, a different composition, and a different framing. Do NOT reuse their layout, background treatment, or framing device. If they used a circular frame, do not use a circular frame.`
    : '';
  return `You are drawing icon ${conceptNo} of 3 for a fantasy RPG spell. Each of the 3 must be a genuinely different visual idea, not the same picture with a different glyph.

SPELL
  Name: ${spell.name}
  School: ${spell.school} (main color ${color})
  Description: ${spell.description}

TASK
Invent concept ${conceptNo}: a distinct way to depict this spell. Think about what the spell DOES, then choose a subject that shows it — the effect itself, the thing it creates, the moment it lands, an object it uses, or its consequence. Avoid generic filler shapes (plain triangles, plain hexagons, plain circles) unless the shape genuinely IS the spell.
${avoid}

Use ${color} as the dominant color, shaded darker and lighter for depth.

${STYLE}

First, in ONE short line prefixed with "CONCEPT:", name your visual idea (e.g. "CONCEPT: a cracked skull dissolving into green ash").
Then output the SVG on the following lines.`;
}

function improvePrompt(spell, color, conceptDesc, prevSvg, round) {
  const goal = round === 2
    ? `Make it substantially BETTER, not merely tidier. Add real visual interest: stronger silhouette, more depth and shading, secondary detail, better composition. The result must look clearly different and clearly improved.`
    : `Final polish pass. Push the craft: refine the silhouette, deepen the lighting, sharpen the focal point, add a last layer of detail. It must be visibly better than what you were given.`;
  return `You are improving an SVG icon for the spell "${spell.name}" (${spell.school}, main color ${color}).

The concept is: ${conceptDesc}

Here is the current version:

${prevSvg}

TASK (improvement round ${round} of 3)
${goal}
Keep the same concept and subject — do not switch to a different idea. Improve THIS drawing.

${STYLE}

Output ONLY the improved SVG.`;
}

async function loadKey() {
  let k = null;
  try { k = await readWinCred(CRED_TARGET); } catch { k = null; }
  return k || process.env.GEMINI_API_KEY || null;
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/**
 * One Gemini call, with backoff. New models (gemini-3.5-flash) return 503
 * "high demand" often, and the free tier 429s — both are transient, so retry
 * rather than losing the whole run.
 */
async function gemini(key, model, prompt, attempt = 0) {
  const MAX = 6;
  let res, j;
  try {
    res = await fetch(`${API}/${model}:generateContent`, {
      method: 'POST',
      headers: { 'x-goog-api-key': key, 'content-type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: { temperature: 1.0, maxOutputTokens: 8192 },
      }),
    });
    j = await res.json();
  } catch (e) {
    if (attempt < MAX) { await sleep(1500 * 2 ** attempt); return gemini(key, model, prompt, attempt + 1); }
    throw e;
  }
  if (!res.ok) {
    const transient = res.status === 503 || res.status === 429 || res.status >= 500;
    if (transient && attempt < MAX) {
      const wait = 2000 * 2 ** attempt + Math.floor(Math.random() * 800);
      process.stdout.write(`      (${res.status} — retrying in ${Math.round(wait / 1000)}s)\n`);
      await sleep(wait);
      return gemini(key, model, prompt, attempt + 1);
    }
    throw new Error(`${res.status}: ${JSON.stringify(j).slice(0, 160)}`);
  }
  const parts = j.candidates?.[0]?.content?.parts || [];
  const text = parts.map((p) => p.text || '').join('');
  if (!text) throw new Error(`empty response (finish: ${j.candidates?.[0]?.finishReason})`);
  return text;
}

/** Pull "CONCEPT: ..." line and the <svg>...</svg> block out of a model reply. */
function parseReply(text) {
  const conceptMatch = text.match(/^\s*CONCEPT:\s*(.+)$/im);
  const concept = conceptMatch ? conceptMatch[1].trim() : '';
  const start = text.indexOf('<svg');
  const end = text.lastIndexOf('</svg>');
  if (start === -1 || end === -1) return { concept, svg: null };
  return { concept, svg: text.slice(start, end + 6).trim() };
}

async function generateSpell(key, model, spell, dryRun) {
  const color = colorFor(spell.school);
  const dir = path.join(OUT_ROOT, spell.id);
  const priorConcepts = [];
  let made = 0;

  for (let c = 1; c <= 3; c++) {
    // v1 — draft a concept that must differ from the ones already used.
    const reply = await gemini(key, model, draftPrompt(spell, color, c, priorConcepts));
    const { concept, svg } = parseReply(reply);
    if (!svg) { console.log(`    c${c}: FAILED to parse SVG from draft`); continue; }
    const conceptDesc = concept || `concept ${c}`;
    priorConcepts.push(conceptDesc);
    console.log(`    c${c}: ${conceptDesc}`);

    let current = svg;
    if (!dryRun) { await mkdir(dir, { recursive: true }); await writeFile(path.join(dir, `c${c}-v1.svg`), current + '\n'); }
    made++;

    // v2, v3 — TRUE iteration: the model sees its own previous SVG.
    for (const round of [2, 3]) {
      try {
        const next = await gemini(key, model, improvePrompt(spell, color, conceptDesc, current, round));
        const parsed = parseReply(next);
        if (!parsed.svg) { console.log(`         v${round}: no SVG returned, keeping v${round - 1}`); continue; }
        current = parsed.svg;
        if (!dryRun) await writeFile(path.join(dir, `c${c}-v${round}.svg`), current + '\n');
        made++;
      } catch (e) {
        console.log(`         v${round}: ERROR ${e.message}`);
      }
    }
  }
  return made;
}

async function main() {
  const model = arg('--model', 'gemini-3.5-flash');
  const dryRun = has('--dry-run');
  const batchIdx = Number(arg('--batch', '0'));
  const only = arg('--spells', '');

  const key = await loadKey();
  if (!key) { console.error(`ERROR: no Gemini key (Credential Manager "${CRED_TARGET}" or env GEMINI_API_KEY)`); process.exit(1); }
  console.log(`gemini spell-icon generator`);
  console.log(`  model:  ${model}`);
  console.log(`  key:    loaded (${key.length} chars), not printed`);

  const manifest = JSON.parse(await readFile(MANIFEST, 'utf8'));
  let spells = manifest.batches[batchIdx]?.spells || [];
  if (only) { const want = new Set(only.split(',').map((s) => s.trim())); spells = spells.filter((s) => want.has(s.id)); }
  console.log(`  spells: ${spells.length}${dryRun ? '  (DRY RUN — nothing written)' : ''}\n`);

  // Enrich each spell with its description from its JSON.
  for (const s of spells) {
    try {
      const j = JSON.parse(await readFile(path.join(REPO_ROOT, s.jsonPath), 'utf8'));
      s.description = String(j.description || '').slice(0, 900);
    } catch { s.description = ''; }
  }

  let total = 0;
  for (const spell of spells) {
    console.log(`${spell.name} (${spell.school})`);
    try {
      total += await generateSpell(key, model, spell, dryRun);
    } catch (e) {
      console.log(`  ERROR: ${e.message}`);
    }
  }
  console.log(`\nDONE: ${total} SVG(s) ${dryRun ? 'would be written' : 'written'} (${spells.length} spells x 9).`);
}

main().catch((e) => { console.error('failed:', e.message); process.exit(1); });
