import { type Grid } from "./utils/graphUtils";
import type { Pack } from "./features";
import type { NamesGenerator } from "./names-generator";
import type { RoutesModule } from "./routes-generator";
import type { StatesModule } from "./states-generator";
import type { MapNote } from "./military-generator";
export interface Marker {
    i: number;
    type: string;
    icon: string;
    x: number;
    y: number;
    cell: number;
    dx?: number;
    dy?: number;
    px?: number;
    lock?: boolean;
}
export interface MarkerConfigRow {
    type: string;
    icon: string;
    dx?: number;
    dy?: number;
    px?: number;
    min: number;
    each: number;
    multiplier: number;
    list: (pack: Pack) => number[] | ArrayLike<number>;
    add: (id: string, cell: number) => void;
}
export interface MarkersContext {
    pack: Pack;
    grid: Grid;
    biomesData: {
        habitability: ArrayLike<number>;
    };
    seed: string;
    Names: NamesGenerator;
    Routes: RoutesModule;
    States: StatesModule;
    notes: MapNote[];
    /** Upstream culturesSet select — "...Fantasy" enables portal/rift/burial types. */
    culturesSet?: string;
    populationRate?: number;
    urbanization?: number;
    era?: string;
    heightUnit?: string;
    heightExponent?: number;
}
export declare class MarkersModule {
    private pack;
    private seed;
    private Names;
    private Routes;
    private States;
    private notes;
    private biomesData;
    private populationRate;
    private urbanization;
    private era;
    private heightUnit;
    private getFriendlyHeight;
    private config;
    private occupied;
    private isFantasy;
    constructor(context: MarkersContext);
    getDefaultConfig(): MarkerConfigRow[];
    getConfig(): MarkerConfigRow[];
    setConfig(newConfig: MarkerConfigRow[]): void;
    generate(): void;
    regenerate(): void;
    add(marker: Partial<Marker> & {
        cell: number;
        type?: string;
    }): Marker;
    private generateTypes;
    private getQuantity;
    private extractAnyElement;
    private getMarkerCoordinates;
    private addMarker;
    deleteMarker(markerId: number): void;
    private listVolcanoes;
    private addVolcano;
    private listHotSprings;
    private addHotSpring;
    private listWaterSources;
    private addWaterSource;
    private listMines;
    private addMine;
    private listBridges;
    private addBridge;
    private listInns;
    private addInn;
    private listLighthouses;
    private addLighthouse;
    private listWaterfalls;
    private addWaterfall;
    private listBattlefields;
    private addBattlefield;
    private listDungeons;
    private addDungeon;
    private listLakeMonsters;
    private addLakeMonster;
    private listSeaMonsters;
    private addSeaMonster;
    private listHillMonsters;
    private addHillMonster;
    private listSacredMountains;
    private addSacredMountain;
    private listSacredForests;
    private addSacredForest;
    private listSacredPineries;
    private addSacredPinery;
    private listSacredPalmGroves;
    private addSacredPalmGrove;
    private listBrigands;
    private addBrigands;
    private listPirates;
    private addPirates;
    private listStatues;
    private addStatue;
    private listRuins;
    private addRuins;
    private listLibraries;
    private addLibrary;
    private listCircuses;
    private addCircuse;
    private listJousts;
    private addJoust;
    private listFairs;
    private addFair;
    private listCanoes;
    private addCanoe;
    private listMigrations;
    private addMigration;
    private listDances;
    private addDances;
    private listMirage;
    private addMirage;
    private listCaves;
    private addCave;
    private listPortals;
    private addPortal;
    private listRifts;
    private addRift;
    private listDisturbedBurial;
    private addDisturbedBurial;
    private listNecropolis;
    private addNecropolis;
    private listEncounters;
    private addEncounter;
}
