/**
 * @file GameLayout.tsx
 * @description
 * This component defines the primary visual layout for the "PLAYING" game phase (Exploration Mode).
 * It organizes the screen into distinct panes:
 * - CompassPane: Navigation controls and current location info.
 * - ActionPane: Controls for interacting with the environment, NPCs, and items.
 * - WorldPane: The main text-based narrative display / log.
 * - Minimap: A visual representation of the immediate surroundings.
 * 
 * It uses a responsive flexbox layout to adapt between mobile (column) and desktop (row) views.
 */
import React from 'react';
import { Location, MapData, GameMessage, Action, NPC, Item } from '../../types';
import ErrorBoundary from '../ErrorBoundary';
import { VersionDisplay } from '../VersionDisplay';
import CompassPane from '../CompassPane';
import ActionPane from '../ActionPane';
import WorldPane from '../WorldPane';
import Minimap from '../Minimap';

interface GameLayoutProps {
    /** The current location data object, including name, description, and biome. */
    currentLocation: Location;
    /** Coordinates of the player within the sub-regional map (if applicable). */
    subMapCoordinates: { x: number; y: number } | null;
    /** The global map data, containing tile information for the entire world. */
    mapData: MapData | null;
    /** The current in-game date and time. */
    gameTime: Date;
    /** The list of narrative messages to display in the WorldPane. */
    messages: GameMessage[];
    /** List of NPCs currently present in the player's location. */
    npcsInLocation: NPC[];
    /** List of interactable items currently present in the player's location. */
    itemsInLocation: Item[];
    /** AI-suggested actions generated by the Gemini engine (optional). */
    geminiGeneratedActions: Action[] | null;
    /** Count of unread entries in the discovery log, used for UI badges. */
    unreadDiscoveryCount: number;
    /** Flag indicating if a rate limit error has occurred for AI services. */
    hasNewRateLimitError: boolean;
    /** The seed value used for procedural generation, ensuring consistent rendering. */
    worldSeed: number;
    /** Debug flag indicating if the developer dummy character is active. */
    isDevDummyActive: boolean;
    /** If true, disables all interactive elements (buttons, inputs) in the layout. */
    disabled: boolean;
    /** Central handler for dispatching user actions (movement, interaction, etc.). */
    onAction: (action: Action) => void;
}

/**
 * Renders the main exploration UI.
 * Wraps child panes in ErrorBoundaries to prevent a single component failure from crashing the entire view.
 */
const GameLayout: React.FC<GameLayoutProps> = ({
    currentLocation,
    subMapCoordinates,
    mapData,
    gameTime,
    messages,
    npcsInLocation,
    itemsInLocation,
    geminiGeneratedActions,
    unreadDiscoveryCount,
    hasNewRateLimitError,
    worldSeed,
    isDevDummyActive,
    disabled,
    onAction,
}) => {
    return (
        <div className="flex flex-col md:flex-row h-screen p-2 sm:p-4 gap-2 sm:gap-4 bg-gray-900 text-gray-200">
            <VersionDisplay position="game-screen" />

            {/* Left Column: Navigation and Actions */}
            <div className="md:w-2/5 lg:w-1/3 flex flex-col gap-2 sm:gap-4 min-h-0">
                <ErrorBoundary fallbackMessage="Error in Compass Pane.">
                    <CompassPane
                        currentLocation={currentLocation}
                        currentSubMapCoordinates={subMapCoordinates}
                        worldMapCoords={currentLocation.mapCoordinates}
                        subMapCoords={subMapCoordinates}
                        onAction={onAction}
                        disabled={disabled}
                        mapData={mapData}
                        gameTime={gameTime}
                    />
                </ErrorBoundary>
                <ErrorBoundary fallbackMessage="Error in Action Pane.">
                    <ActionPane
                        currentLocation={currentLocation}
                        npcsInLocation={npcsInLocation}
                        itemsInLocation={itemsInLocation}
                        onAction={onAction}
                        disabled={disabled}
                        geminiGeneratedActions={geminiGeneratedActions || []}
                        isDevDummyActive={isDevDummyActive}
                        unreadDiscoveryCount={unreadDiscoveryCount}
                        hasNewRateLimitError={hasNewRateLimitError}
                        subMapCoordinates={subMapCoordinates}
                        worldSeed={worldSeed}
                    />
                </ErrorBoundary>
            </div>

            {/* Right Column: Narrative Log and Minimap */}
            <div className="md:w-3/5 lg:w-2/3 flex flex-col gap-2 sm:gap-4 min-h-0 relative">
                <ErrorBoundary fallbackMessage="Error in World Pane.">
                    <WorldPane messages={messages} />
                </ErrorBoundary>
                <Minimap
                    mapData={mapData}
                    currentLocationCoords={currentLocation.mapCoordinates}
                    submapCoords={subMapCoordinates}
                    visible={true} // Always visible in this layout
                    toggleMap={() => onAction({ type: 'toggle_map', label: 'Open Map' })}
                />
            </div>
        </div>
    );
};

export default GameLayout;
