/**
 * ARCHITECTURAL ADVISORY:
 * LOCAL HELPER: This file has a small, manageable dependency footprint.
 *
 * Last Sync: 05/07/2026, 07:17:04
 * Dependents: App.tsx
 * Imports: 7 files
 *
 * MULTI-AGENT SAFETY:
 * If you modify exports/imports, re-run the sync tool to update this header:
 * > npx tsx misc/dev_hub/codebase-visualizer/server/index.ts --sync [this-file-path]
 * See misc/dev_hub/codebase-visualizer/VISUALIZER_README.md for more info.
 */
/**
 * @file GameLayout.tsx
 * @description
 * This component defines the primary visual layout for the "PLAYING" game phase (Exploration Mode).
 * It organizes the screen into distinct panes:
 * - CompassPane: Navigation controls and current location info.
 * - ActionPane: Controls for interacting with the environment, NPCs, and items.
 * - WorldPane: The main text-based narrative display / log.
 * - Minimap: A visual representation of the immediate surroundings.
 *
 * It uses a responsive flexbox layout to adapt between mobile (column) and desktop (row) views.
 */
import React from 'react';
import { Location, GameMessage, Action, NPC, Item, PlayerCharacter } from '../../types';
import type { PlayerWorldPosition } from '../../types';
interface GameLayoutProps {
    /** The current location data object, including name, description, and biome. */
    currentLocation: Location;
    /** The current in-game date and time. */
    gameTime: Date;
    /** The list of narrative messages to display in the WorldPane. */
    messages: GameMessage[];
    /**
     * Opening-situation entry status (gameEntry.status). When 'generating', the
     * Log shows an honest "the world is taking shape" placeholder so a brand-new
     * player never faces a blank narrative panel during the (possibly multi-second)
     * model call that writes their opening scene.
     */
    openingStatus?: string;
    /** List of NPCs currently present in the player's location. */
    npcsInLocation: NPC[];
    /** List of interactable items currently present in the player's location. */
    itemsInLocation: Item[];
    /** Current party roster for rest actions. */
    party: PlayerCharacter[];
    /** AI-suggested actions generated by the Gemini engine (optional). */
    geminiGeneratedActions: Action[] | null;
    /** Count of unread entries in the discovery log, used for UI badges. */
    unreadDiscoveryCount: number;
    /** Flag indicating if a rate limit error has occurred for AI services. */
    hasNewRateLimitError: boolean;
    /** The seed value used for procedural generation, ensuring consistent rendering. */
    worldSeed: number;
    /** Flag indicating if developer mode logic (menus, cheats) is enabled. */
    isDevModeEnabled: boolean;
    /** User preference: if true, the game periodically saves to the auto-save slot. */
    autoSaveEnabled: boolean;
    /** If true, disables all interactive elements (buttons, inputs) in the layout. */
    disabled: boolean;
    /** Central handler for dispatching user actions (movement, interaction, etc.). */
    onAction: (action: Action) => void;
    /** Last known streamed-world position — drives always-visible atlas strip (W3DUI-23). */
    playerWorldPos?: PlayerWorldPosition | null;
    /** Optional sibling control for switching between the available 2D map surfaces. */
    surfaceToggle?: React.ReactNode;
    /** Opens the glossary at a term — used by the party-condition chips' rule links. */
    onNavigateToGlossary?: (termId: string) => void;
}
declare const _default: React.NamedExoticComponent<GameLayoutProps>;
export default _default;
