// @dependencies-start
/**
 * ARCHITECTURAL ADVISORY:
 * LOCAL HELPER: This file has a small, manageable dependency footprint.
 *
 * Last Sync: 09/06/2026, 02:11:18
 * Dependents: App.tsx
 * Imports: 9 files
 *
 * MULTI-AGENT SAFETY:
 * If you modify exports/imports, re-run the sync tool to update this header:
 * > npx tsx misc/dev_hub/codebase-visualizer/server/index.ts --sync [this-file-path]
 * See misc/dev_hub/codebase-visualizer/VISUALIZER_README.md for more info.
 */
// @dependencies-end

/**
 * @file GameLayout.tsx
 * @description
 * This component defines the primary visual layout for the "PLAYING" game phase (Exploration Mode).
 * It organizes the screen into distinct panes:
 * - CompassPane: Navigation controls and current location info.
 * - ActionPane: Controls for interacting with the environment, NPCs, and items.
 * - WorldPane: The main text-based narrative display / log.
 * - Minimap: A visual representation of the immediate surroundings.
 * 
 * It uses a responsive flexbox layout to adapt between mobile (column) and desktop (row) views.
 */
import React from 'react';
import { Location, MapData, GameMessage, Action, NPC, Item, PlayerCharacter } from '../../types';
import ErrorBoundary from '../ui/ErrorBoundary';
import { VersionDisplay } from '../ui/VersionDisplay';
import ActionPane from '../ActionPane';
import WorldPane from '../WorldPane';
import WorldAtlasStrip from '../World3D/WorldAtlasStrip';
import { UI_ID } from '../../styles/uiIds';
import type { PlayerWorldPosition } from '../../types';

interface GameLayoutProps {
    /** The current location data object, including name, description, and biome. */
    currentLocation: Location;
    /** Coordinates of the player within the sub-regional map (if applicable). */
    subMapCoordinates: { x: number; y: number } | null;
    /** The global map data, containing tile information for the entire world. */
    mapData: MapData | null;
    /** The current in-game date and time. */
    gameTime: Date;
    /** The list of narrative messages to display in the WorldPane. */
    messages: GameMessage[];
    /**
     * Opening-situation entry status (gameEntry.status). When 'generating', the
     * Log shows an honest "the world is taking shape" placeholder so a brand-new
     * player never faces a blank narrative panel during the (possibly multi-second)
     * model call that writes their opening scene.
     */
    openingStatus?: string;
    /** List of NPCs currently present in the player's location. */
    npcsInLocation: NPC[];
    /** List of interactable items currently present in the player's location. */
    itemsInLocation: Item[];
    /** Current party roster for rest actions. */
    party: PlayerCharacter[];
    /** AI-suggested actions generated by the Gemini engine (optional). */
    geminiGeneratedActions: Action[] | null;
    /** Count of unread entries in the discovery log, used for UI badges. */
    unreadDiscoveryCount: number;
    /** Flag indicating if a rate limit error has occurred for AI services. */
    hasNewRateLimitError: boolean;
    /** The seed value used for procedural generation, ensuring consistent rendering. */
    worldSeed: number;
    /** Flag indicating if developer mode logic (menus, cheats) is enabled. */
    isDevModeEnabled: boolean;
    /** User preference: if true, the game periodically saves to the auto-save slot. */
    autoSaveEnabled: boolean;
    /** If true, disables all interactive elements (buttons, inputs) in the layout. */
    disabled: boolean;
    /** Central handler for dispatching user actions (movement, interaction, etc.). */
    onAction: (action: Action) => void;
    /** Last known streamed-world position — drives always-visible atlas strip (W3DUI-23). */
    playerWorldPos?: PlayerWorldPosition | null;
}

/**
 * Renders the main exploration UI.
 * Wraps child panes in ErrorBoundaries to prevent a single component failure from crashing the entire view.
 */
const GameLayout: React.FC<GameLayoutProps> = ({
    currentLocation,
    subMapCoordinates,
    mapData,
    gameTime,
    messages,
    openingStatus,
    npcsInLocation,
    itemsInLocation,
    party,
    geminiGeneratedActions,
    unreadDiscoveryCount,
    hasNewRateLimitError,
    worldSeed,
    isDevModeEnabled,
    autoSaveEnabled,
    disabled,
    onAction,
    playerWorldPos = null,
}) => {
    const openWorldMap = () => onAction({ type: 'toggle_map', label: 'Open World Map' });
    return (
        <div id={UI_ID.GAME_LAYOUT} data-testid={UI_ID.GAME_LAYOUT} className="flex flex-col md:flex-row h-screen p-2 sm:p-4 gap-2 sm:gap-4 bg-gray-900 text-gray-200">
            <VersionDisplay position="game-screen" />

            {/* Left Column: Navigation and Actions */}
            <div id={UI_ID.LEFT_COLUMN} data-testid={UI_ID.LEFT_COLUMN} className="md:w-2/5 lg:w-1/3 flex flex-col gap-2 sm:gap-4 min-h-0 md:overflow-y-auto md:overflow-x-hidden md:pr-1">
                {/* Grid retirement: the 30x20 compass is removed. Overland travel is
                    the cell-native World Map (atlas fast-travel); local movement is the
                    3D/Locale view. This is the sole overland navigation entry point. */}
                <button
                    type="button"
                    onClick={openWorldMap}
                    disabled={disabled}
                    data-testid="open-world-map"
                    className="w-full rounded-lg border border-amber-600/60 bg-gray-800 px-4 py-3 text-sm font-semibold text-amber-200 hover:bg-gray-700 disabled:opacity-50"
                >
                    Open World Map
                </button>
                <ErrorBoundary fallbackMessage="Error in Action Pane.">
                    <ActionPane
                        currentLocation={currentLocation}
                        npcsInLocation={npcsInLocation}
                        itemsInLocation={itemsInLocation}
                        party={party}
                        onAction={onAction}
                        disabled={disabled}
                        geminiGeneratedActions={geminiGeneratedActions || []}
                        isDevModeEnabled={isDevModeEnabled}
                        unreadDiscoveryCount={unreadDiscoveryCount}
                        autoSaveEnabled={autoSaveEnabled}
                        hasNewRateLimitError={hasNewRateLimitError}
                    />
                </ErrorBoundary>
            </div>

            {/* Right Column: Narrative Log + atlas strip. The old square Minimap
                was removed 2026-06-23 — it has no valid local/submap dataset to
                render yet; revisit once the WF local layer is the source. */}
            <div id={UI_ID.RIGHT_COLUMN} data-testid={UI_ID.RIGHT_COLUMN} className="md:w-3/5 lg:w-2/3 flex flex-col gap-2 sm:gap-4 min-h-0 relative">
                <ErrorBoundary fallbackMessage="Error in World Pane.">
                    <WorldPane messages={messages} openingStatus={openingStatus} />
                </ErrorBoundary>
                <WorldAtlasStrip
                    mapData={mapData}
                    playerWorldPos={playerWorldPos}
                    onOpenWorldMap={openWorldMap}
                />
            </div>
        </div>
    );
};

// Wrap GameLayout with React.memo to prevent unnecessary re-renders
// React.memo is a performance optimization that tells React to only re-render this component
// when its props actually change. Without this, GameLayout would re-render every time the parent
// App component re-renders, even if none of GameLayout's props changed.
// This is important because GameLayout is a large component that renders many child components.
export default React.memo(GameLayout);
