/**
 * Copyright (c) 2024 Aralia RPG
 * Licensed under the MIT License
 *
 * @file src/components/gameEntry/OpeningSituationGate.tsx
 *
 * Drives the opening-situation entry flow on PLAYING entry and renders its
 * transient surfaces:
 *  - `generating`        → a non-blocking "the world is taking shape…" overlay so
 *                          the player never sees a blank PLAYING frame.
 *  - `model-unavailable` → the honest Ollama dependency block + a retry button.
 *                          NO canned scene is ever substituted (D-NOFB).
 *
 * Once `in-situation`, the seeded conversation (ConversationPanel) carries the
 * experience and this gate renders nothing.
 */

import React from 'react';
import { GameState } from '../../types';
import { AppAction } from '../../state/actionTypes';
import { useOpeningSituation, type UseOpeningSituationOptions } from '../../hooks/useOpeningSituation';
import { OllamaDependencyModal } from '../ui/OllamaDependencyModal';

interface OpeningSituationGateProps {
    gameState: GameState;
    dispatch: React.Dispatch<AppAction>;
    /** Test seam: inject the situation generator. */
    options?: UseOpeningSituationOptions;
}

export const OpeningSituationGate: React.FC<OpeningSituationGateProps> = ({ gameState, dispatch, options }) => {
    useOpeningSituation(gameState, dispatch, options);

    const status = gameState.gameEntry?.status ?? 'idle';
    // This shared dismiss path removes only the failed opening overlay. It keeps
    // the no-fallback promise intact because no substitute scene is created.
    const skipOpening = () => dispatch({ type: 'SKIP_OPENING_SITUATION' });

    if (status === 'generating') {
        return (
            <div
                data-testid="opening-situation-generating"
                className="fixed inset-x-0 top-0 z-50 flex justify-center pointer-events-none p-3"
            >
                <div className="pointer-events-auto bg-gray-900/90 border border-amber-500/50 rounded-full px-5 py-2 text-amber-200 text-sm shadow-lg flex items-center gap-3">
                    <span className="inline-block w-3 h-3 rounded-full bg-amber-400 animate-pulse" aria-hidden="true" />
                    The world is taking shape around you…
                </div>
            </div>
        );
    }

    if (status === 'model-unavailable') {
        return (
            <>
                <OllamaDependencyModal
                    isOpen
                    onClose={skipOpening}
                    onDontShowAgain={() => { /* no-op: entry is gated on a live model */ }}
                />
                <div
                    data-testid="opening-situation-unavailable"
                    className="fixed inset-0 z-40 flex items-center justify-center pointer-events-none p-4"
                >
                    <div className="pointer-events-auto bg-gray-900 border border-amber-500/60 rounded-xl shadow-2xl max-w-md w-full p-6 text-gray-100">
                        <h2 className="text-lg font-bold text-amber-300 mb-2">The opening can't be written yet</h2>
                        <p className="text-sm text-gray-300 mb-2">
                            Aralia drops you into a freshly written situation generated by a local
                            Ollama model. That model isn't reachable right now, so there's nothing
                            to step into — and Aralia will not fake a scene.
                        </p>
                        {gameState.gameEntry?.error && (
                            <p className="text-xs text-gray-500 mb-4 break-words">
                                Details: {gameState.gameEntry.error}
                            </p>
                        )}
                        <div className="flex justify-end gap-3">
                            <button
                                type="button"
                                data-testid="opening-situation-dismiss"
                                onClick={skipOpening}
                                className="px-4 py-2 rounded bg-gray-700 hover:bg-gray-600 text-gray-100 font-semibold transition-colors"
                            >
                                Dismiss
                            </button>
                            <button
                                type="button"
                                data-testid="opening-situation-retry"
                                onClick={() => dispatch({ type: 'BEGIN_OPENING_SITUATION' })}
                                className="px-4 py-2 rounded bg-amber-600 hover:bg-amber-500 text-gray-900 font-semibold transition-colors"
                            >
                                Retry
                            </button>
                        </div>
                    </div>
                </div>
            </>
        );
    }

    return null;
};

export default OpeningSituationGate;
