// VitePress configuration for the Aralia documentation site.
//
// Layout:
//   docs-site/           <- VitePress root (srcDir = this directory)
//   docs-site/index.md   <- Home page (the landing page at /)
//   docs-site/api/       <- Generated by TypeDoc (npm run docs:api)
//   docs-site/.vitepress <- This config
//
// The existing docs/ directory is resolved via srcDir: '..'
// so all docs/*.md files are served at /docs/*.

import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'Aralia Docs',
  description: 'Developer documentation for the Aralia RPG project',

  outDir: '../docs-site-dist',

  // Existing docs contain many archival and tool-facing links that are useful
  // as historical breadcrumbs even when the target is not part of this site.
  ignoreDeadLinks: true,

  vite: {
    // The app's root Vite config has React-specific manual chunking. VitePress
    // builds Vue pages, so it should not inherit that application bundle setup.
    configFile: false,
  },

  // Serve from the repo root so both docs/ and docs-site/ are in scope.
  srcDir: '..',

  srcExclude: [
    'src/**',
    'scripts/**',
    'tests/**',
    'node_modules/**',
    'dist/**',
    'docs-site-dist/**',
    'docs/archive/**',
    'docs/generated/**',
    'docs/tasks/**',
    'docs/images/**',
    'docs/portraits/**',
    'docs/Prompts/**',
    'docs/superpowers/**',
    'docs/status-effects/**',
    'devtools/**',
    'deprecated/**',
    'misc/**',
    'conductor/**',
    'verification/**',
    '.agent/**',
    '.claude/**',
    '.gemini/**',
    'Aralia/**',
    '**/.vitepress/**',
  ],

  cleanUrls: true,

  markdown: {
    html: false,
    // TypeDoc creates repeated section names such as "Parameters" and "Returns".
    // Disabling permalinks avoids strict duplicate-anchor failures during docs dev.
    anchor: {
      permalink: false,
    },
  },

  themeConfig: {
    nav: [
      { text: 'Home', link: '/docs-site/index' },
      { text: 'Architecture', link: '/docs/PROJECT_ARCHITECTURE' },
      { text: 'Dev Guide', link: '/docs/DEVELOPMENT_GUIDE' },
      { text: 'Backlog', link: '/docs/BACKLOG' },
      { text: 'API Reference', link: '/docs-site/api/index' },
    ],

    sidebar: [
      {
        text: 'Start Here',
        items: [
          { text: 'Documentation Index', link: '/docs/@README-INDEX' },
          { text: 'Project & Architecture', link: '/docs/PROJECT_ARCHITECTURE' },
          { text: 'Development Guide', link: '/docs/DEVELOPMENT_GUIDE' },
          { text: 'Vision', link: '/docs/VISION' },
        ],
      },
      {
        text: 'Active Work',
        items: [
          { text: 'Backlog', link: '/docs/BACKLOG' },
          { text: 'Spell Integration Status', link: '/docs/SPELL_INTEGRATION_STATUS' },
        ],
      },
      {
        text: 'Architecture Domains',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/docs/architecture/' },
          { text: 'Battle Map', link: '/docs/architecture/domains/battle-map' },
          { text: 'Character Creator', link: '/docs/architecture/domains/character-creator' },
          { text: 'Character Sheet', link: '/docs/architecture/domains/character-sheet' },
          { text: 'Combat', link: '/docs/architecture/domains/combat' },
          { text: 'Glossary', link: '/docs/architecture/domains/glossary' },
          { text: 'Items / Trade / Inventory', link: '/docs/architecture/domains/items-trade-inventory' },
          { text: 'NPCs & Companions', link: '/docs/architecture/domains/npcs-companions' },
          { text: 'Spells', link: '/docs/architecture/domains/spells' },
          { text: 'Submap', link: '/docs/architecture/domains/submap' },
          { text: 'Town Map', link: '/docs/architecture/domains/town-map' },
          { text: 'World Map', link: '/docs/architecture/domains/world-map' },
        ],
      },
      {
        text: 'Guides & Governance',
        collapsed: true,
        items: [
          { text: 'AI Prompt Guide', link: '/docs/@AI-PROMPT-GUIDE' },
          { text: 'Documentation Guide', link: '/docs/@DOCUMENTATION-GUIDE' },
          { text: 'Doc Registry', link: '/docs/@DOC-REGISTRY' },
        ],
      },
      {
        text: 'API Reference',
        collapsed: true,
        items: [
          { text: 'All Exports', link: '/docs-site/api/index' },
        ],
      },
    ],

    search: {
      provider: 'local',
    },

    editLink: {
      pattern: 'https://github.com/Gambitnl/Aralia/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/Gambitnl/Aralia' },
    ],

    footer: {
      message: 'Aralia RPG - Internal Developer Documentation',
    },
  },
})
