/**
 * @file creatureGenomeSchema.ts — Zod schema for procedural creature genomes.
 *
 * Defines the complete JSON blueprint generated by DeepSeek (or other LLMs)
 * that describes a creature's bone hierarchy, joint constraints, skin, and
 * locomotion parameters.
 *
 * BIOMECHANICS RULES ENFORCED IN SCHEMA:
 * - Knees: hinge joint, flex 0° to ~130° (backward relative to hip)
 * - Elbows: hinge joint, flex 0° to ~145° (forward relative to shoulder)
 * - Shoulders: ball_and_socket, ~120° cone angle, ~90° twist
 * - Hips: ball_and_socket, ~90° cone angle, ~45° twist
 * - Spine: pivot joints, individually <15° rotation (compounds across segments)
 * - Wrists/ankles: saddle joints, pitch + yaw ranges, no roll
 * - Neck atlas: pivot joint (twist only)
 * - Forearm pronation: pivot joint (twist only)
 * - Quadruped hind legs: ~1.1x foreleg length
 * - Hexapod legs: arranged in 3 pairs with alternating tripod gait
 */

import { z } from 'zod';

// ============================================================================
// Joint Constraints
// ============================================================================

export const JointConstraintSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('hinge'),
    /** Flexion axis: 'forward' (elbows) or 'backward' (knees) */
    axis: z.enum(['forward', 'backward']),
    /** Min angle in degrees (typically 0 for flexion) */
    minAngle: z.number().min(0).max(180),
    /** Max angle in degrees - knees: 130°, elbows: 145° */
    maxAngle: z.number().min(0).max(180),
    /** Stiffness 0-1 */
    stiffness: z.number().min(0).max(1).default(0.5),
  }),
  z.object({
    type: z.literal('ball_and_socket'),
    /** Cone half-angle limit in degrees (shoulders ~120°, hips ~90°) */
    coneAngle: z.number().min(0).max(180),
    /** Twist limit in degrees (shoulders ~90°, hips ~45°) */
    twistLimit: z.number().min(0).max(180),
    /** Stiffness 0-1 */
    stiffness: z.number().min(0).max(1).default(0.5),
  }),
  z.object({
    type: z.literal('saddle'),
    /** Pitch range in degrees */
    pitchRange: z.number().min(0).max(180),
    /** Yaw range in degrees */
    yawRange: z.number().min(0).max(180),
    /** Stiffness 0-1 */
    stiffness: z.number().min(0).max(1).default(0.5),
  }),
  z.object({
    type: z.literal('pivot'),
    /** Twist range in degrees (rotation around bone axis) */
    twistRange: z.number().min(0).max(180),
    /** Stiffness 0-1 */
    stiffness: z.number().min(0).max(1).default(0.5),
  }),
  z.object({
    type: z.literal('fixed'),
    /** Stiffness always 1 for fixed joints */
    stiffness: z.literal(1).default(1),
  }),
]);

export type JointConstraint = z.infer<typeof JointConstraintSchema>;

// ============================================================================
// Bone Hierarchy
// ============================================================================

export const BoneNodeSchema: z.ZodType<any> = z.lazy(() =>
  z.object({
    id: z.string().min(1),
    name: z.string().min(1),
    /** Bone length in feet */
    length: z.number().positive(),
    /** Bone thickness in feet */
    thickness: z.number().positive(),
    /** Rest rotation in degrees [pitch, yaw, roll] */
    restRotation: z.tuple([z.number(), z.number(), z.number()]).default([0, 0, 0]),
    /** Joint constraint connecting to parent (null for root bone) */
    joint: JointConstraintSchema.nullable(),
    /** Mirror flag - auto-generates symmetric counterpart */
    mirror: z.boolean().default(false),
    /** Child bones */
    children: z.array(z.lazy(() => BoneNodeSchema)).default([]),
  })
);

export type BoneNode = z.infer<typeof BoneNodeSchema>;

// ============================================================================
// Spine Configuration
// ============================================================================

export const SpineSchema = z.object({
  /** Number of spine segments (typically 3-10) */
  segmentCount: z.number().int().min(1).max(20),
  /** Overall spine curvature in degrees */
  curvature: z.number().min(-90).max(90).default(0),
  /** Length of each segment in feet */
  segmentLength: z.number().positive(),
  /** Max rotation per segment in degrees - biomechanically <15° */
  maxSegmentRotation: z.number().min(1).max(14).default(10),
});

export type SpineConfig = z.infer<typeof SpineSchema>;

// ============================================================================
// Locomotion Configuration
// ============================================================================

export const LocomotionSchema = z.object({
  /** Gait type determines leg coordination patterns */
  gaitType: z.enum([
    'walk',
    'trot',
    'gallop',
    'bipedal',
    'tripod',
    'ripple',
    'serpentine',
    'flight',
    'custom',
  ]),
  /** Stride length in feet */
  strideLength: z.number().positive(),
  /** Step frequency in Hz */
  stepFrequency: z.number().positive(),
  /** Leg group definitions with phase offsets (0-1) */
  legGroups: z.array(
    z.object({
      name: z.string(),
      boneIds: z.array(z.string()),
      phaseOffset: z.number().min(0).max(1),
      amplitudeScale: z.number().positive().default(1),
    })
  ).default([]),
});

export type LocomotionConfig = z.infer<typeof LocomotionSchema>;

// ============================================================================
// Skin Configuration
// ============================================================================

export const SkinSchema = z.object({
  primaryColor: z.string().regex(/^#[0-9A-Fa-f]{6}$/),
  secondaryColor: z.string().regex(/^#[0-9A-Fa-f]{6}$/),
  pattern: z.enum([
    'solid',
    'striped',
    'spotted',
    'camouflage',
    'scaly',
    'feathered',
    'chitinous',
    'custom',
  ]),
  thicknessProfile: z.number().min(0).max(1).default(0.5),
});

export type SkinConfig = z.infer<typeof SkinSchema>;

// ============================================================================
// Creature Genome Schema
// ============================================================================

export const CreatureGenomeSchema = z.object({
  schemaVersion: z.literal('1.0').default('1.0'),
  archetype: z.enum([
    'biped',
    'quadruped',
    'hexapod',
    'serpentine',
    'avian',
    'arachnid',
    'custom',
  ]),
  symmetryType: z.enum(['bilateral', 'radial', 'none']).default('bilateral'),
  rootBone: BoneNodeSchema,
  spine: SpineSchema,
  locomotion: LocomotionSchema,
  skin: SkinSchema,
  scaleMultiplier: z.number().positive().default(1),
  mass: z.number().positive(),
});

export type CreatureGenome = z.infer<typeof CreatureGenomeSchema>;

// ============================================================================
// Helpers & Validation
// ============================================================================

export function creatureGenomeToJsonSchema(): Record<string, unknown> {
  return {
    $schema: 'http://json-schema.org/draft-07/schema#',
    title: 'CreatureGenome',
    type: 'object',
    required: ['archetype', 'rootBone', 'spine', 'locomotion', 'skin', 'mass'],
    properties: {
      schemaVersion: { type: 'string', default: '1.0' },
      archetype: { type: 'string', enum: ['biped', 'quadruped', 'hexapod', 'serpentine', 'avian', 'arachnid', 'custom'] },
      symmetryType: { type: 'string', enum: ['bilateral', 'radial', 'none'], default: 'bilateral' },
      scaleMultiplier: { type: 'number', default: 1.0 },
      mass: { type: 'number', description: 'Mass in kg' },
      skin: {
        type: 'object',
        required: ['primaryColor', 'secondaryColor', 'pattern'],
        properties: {
          primaryColor: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
          secondaryColor: { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' },
          pattern: { type: 'string', enum: ['solid', 'striped', 'spotted', 'camouflage', 'scaly', 'feathered', 'chitinous', 'custom'] },
          thicknessProfile: { type: 'number', default: 0.5 }
        }
      },
      spine: {
        type: 'object',
        required: ['segmentCount', 'segmentLength'],
        properties: {
          segmentCount: { type: 'integer', minimum: 1, maximum: 20 },
          curvature: { type: 'number', minimum: -90, maximum: 90 },
          segmentLength: { type: 'number', description: 'Length in feet' },
          maxSegmentRotation: { type: 'number', maximum: 14 }
        }
      },
      locomotion: {
        type: 'object',
        required: ['gaitType', 'strideLength', 'stepFrequency'],
        properties: {
          gaitType: { type: 'string', enum: ['walk', 'trot', 'gallop', 'bipedal', 'tripod', 'ripple', 'serpentine', 'flight', 'custom'] },
          strideLength: { type: 'number', description: 'Stride length in feet' },
          stepFrequency: { type: 'number', description: 'Step frequency in Hz' }
        }
      },
      rootBone: {
        type: 'object',
        description: 'Recursive BoneNode structure with id, name, length (feet), thickness (feet), restRotation [pitch, yaw, roll], joint, mirror, children'
      }
    }
  };
}

export function validateGenome(
  data: unknown
): { success: true; data: CreatureGenome } | { success: false; errors: string[] } {
  const result = CreatureGenomeSchema.safeParse(data);
  if (result.success) {
    return { success: true, data: result.data };
  }
  const errors = result.error.issues.map((issue) => {
    const path = issue.path.join('.');
    return `Invalid at ${path}: ${issue.message}`;
  });
  return { success: false, errors };
}

export function createBoneNode(
  id: string,
  name: string,
  length: number,
  thickness: number,
  joint: JointConstraint | null = null,
  options: Partial<Omit<BoneNode, 'id' | 'name' | 'length' | 'thickness' | 'joint'>> = {}
): BoneNode {
  return {
    id,
    name,
    length,
    thickness,
    joint,
    restRotation: [0, 0, 0],
    mirror: false,
    children: [],
    ...options,
  };
}

export function createQuadrupedHindLeg(hipId: string, scale: number = 1): BoneNode {
  const hip = createBoneNode(hipId, 'hip', 0.8 * scale, 0.3 * scale, {
    type: 'ball_and_socket',
    coneAngle: 90,
    twistLimit: 45,
    stiffness: 0.6,
  });

  const femur = createBoneNode(`${hipId}_femur`, 'femur', 1.1 * scale, 0.25 * scale, {
    type: 'hinge',
    axis: 'backward',
    minAngle: 0,
    maxAngle: 130,
    stiffness: 0.5,
  });

  const tibia = createBoneNode(`${hipId}_tibia`, 'tibia', 1.0 * scale, 0.2 * scale, {
    type: 'hinge',
    axis: 'backward',
    minAngle: 0,
    maxAngle: 130,
    stiffness: 0.5,
  });

  const foot = createBoneNode(`${hipId}_foot`, 'foot', 0.3 * scale, 0.15 * scale, {
    type: 'saddle',
    pitchRange: 45,
    yawRange: 20,
    stiffness: 0.7,
  });

  tibia.children = [foot];
  femur.children = [tibia];
  hip.children = [femur];

  return hip;
}

export function createHexapodLeg(legId: string, scale: number = 1): BoneNode {
  const coxa = createBoneNode(legId, 'coxa', 0.4 * scale, 0.2 * scale, {
    type: 'ball_and_socket',
    coneAngle: 60,
    twistLimit: 20,
    stiffness: 0.4,
  });

  const femur = createBoneNode(`${legId}_femur`, 'femur', 0.8 * scale, 0.15 * scale, {
    type: 'hinge',
    axis: 'backward',
    minAngle: 0,
    maxAngle: 120,
    stiffness: 0.5,
  });

  const tibia = createBoneNode(`${legId}_tibia`, 'tibia', 0.7 * scale, 0.12 * scale, {
    type: 'hinge',
    axis: 'backward',
    minAngle: 0,
    maxAngle: 120,
    stiffness: 0.5,
  });

  coxa.children = [femur];
  femur.children = [tibia];

  return coxa;
}
