
/**
 * @file ActionPane.tsx
 * This component displays available actions to the player.
 * It includes standard actions (Talk, Take, Move), Oracle interaction,
 * and dynamic actions generated by Gemini (e.g. from Look Around).
 */
import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Menu, X } from 'lucide-react';
import { Location, Action, NPC, Item } from '../types';

interface ActionPaneProps {
  currentLocation: Location;
  npcsInLocation: NPC[];
  itemsInLocation: Item[];
  onAction: (action: Action) => void;
  disabled: boolean;
  geminiGeneratedActions: Action[] | null;
  isDevDummyActive: boolean;
  unreadDiscoveryCount: number;
  hasNewRateLimitError: boolean;
}

const ActionButton: React.FC<{
  action: Action;
  onClick: (action: Action) => void;
  disabled: boolean;
  className?: string;
  isGeminiAction?: boolean;
  badgeCount?: number;
  hasNotification?: boolean;
}> = ({ action, onClick, disabled, className = '', isGeminiAction = false, badgeCount, hasNotification }) => {
  const baseClasses = "btn";
  
  let colorClasses = "btn-primary";
  
  // Determine color based on action type
  if (action.type === 'toggle_party_overlay') colorClasses = "btn-green";
  else if (action.type === 'save_game') colorClasses = "btn-yellow";
  else if (action.type === 'go_to_main_menu') colorClasses = "btn-red";
  else if (action.type === 'toggle_dev_menu') colorClasses = "btn-orange";
  else if (action.type === 'gemini_custom_action') colorClasses = "btn-teal";
  else if (action.type === 'ask_oracle' || (action.type === 'custom' && action.label.toLowerCase().includes('oracle'))) colorClasses = "btn-purple";
  else if (action.type === 'ANALYZE_SITUATION') colorClasses = "btn-indigo";
  else if (action.type === 'TOGGLE_DISCOVERY_LOG') colorClasses = "btn-lime";
  else if (action.type === 'TOGGLE_LOGBOOK') colorClasses = "btn-amber";
  else if (action.type === 'TOGGLE_QUEST_LOG') colorClasses = "btn-amber"; // Using btn-amber for Quest Log too
  else if (action.type === 'TOGGLE_GLOSSARY_VISIBILITY') colorClasses = "btn-indigo-dark";
  else if (action.type === 'TOGGLE_GAME_GUIDE') colorClasses = "btn-blue";

  if (isGeminiAction && action.type !== 'gemini_custom_action') {
    colorClasses = "btn-teal";
  }
  
  const handleClick = () => {
      // Ensure targetId for movement actions is a string to avoid type errors, without mutating prop
      if (action.type === 'move' && action.targetId && typeof action.targetId !== 'string') {
          onClick({ ...action, targetId: String(action.targetId) });
      } else {
          onClick(action);
      }
  };


  return (
    <motion.button
      {...{
        layout: true,
        initial: { opacity: 0, scale: 0.8 },
        animate: { opacity: 1, scale: 1 },
        exit: { opacity: 0, scale: 0.8 },
        whileHover: { scale: 1.05 },
        whileTap: { scale: 0.95 },
      } as any}
      onClick={handleClick}
      disabled={disabled}
      className={`${baseClasses} ${colorClasses} ${className}`}
      aria-label={action.label}
    >
      {action.label}
      {badgeCount !== undefined && badgeCount > 0 && (
        <span className="absolute -top-2 -right-2 inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-red-100 bg-red-600 rounded-full">
          {badgeCount > 99 ? '99+' : badgeCount}
        </span>
      )}
      {hasNotification && (
        <span className="absolute -top-1 -right-1 h-3 w-3 rounded-full bg-red-500 border-2 border-gray-800 animate-pulse"></span>
      )}
    </motion.button>
  );
};

const ActionPane: React.FC<ActionPaneProps> = ({
  currentLocation,
  npcsInLocation,
  itemsInLocation,
  onAction,
  disabled,
  geminiGeneratedActions,
  isDevDummyActive,
  unreadDiscoveryCount,
  hasNewRateLimitError,
}) => {
  const [isOracleInputVisible, setIsOracleInputVisible] = useState(false);
  const [oracleQuery, setOracleQuery] = useState('');
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  // Close menu when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(event.target as Node)) {
        setIsMenuOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, []);

  const generalActions: Action[] = [];

  // Populate interactions for NPCs and Items in current location
  if (!currentLocation.id.startsWith('coord_')) {
    npcsInLocation.forEach((npc) => {
      generalActions.push({ type: 'talk', label: `Talk to ${npc.name}`, targetId: npc.id });
    });
  }

  if (!currentLocation.id.startsWith('coord_')) {
    itemsInLocation.forEach((item) => {
      generalActions.push({ type: 'take_item', label: `Take ${item.name}`, targetId: item.id });
    });
  }
  
  // Move actions for named exits (standard non-compass moves)
  if (currentLocation.exits) {
    Object.entries(currentLocation.exits).forEach(([direction, exit]) => {
       if (!['North', 'South', 'East', 'West', 'NorthEast', 'NorthWest', 'SouthEast', 'SouthWest'].includes(direction)) {
        // Handle exit being string (legacy) or object
        const targetId = typeof exit === 'string' ? exit : exit.targetId;
        // Optionally verify exit is visible if it's an object
        if (typeof exit === 'string' || !exit.isHidden) {
             generalActions.push({ type: 'move', label: `Go ${direction}`, targetId: targetId });
        }
      }
    });
  }

  const handleAskOracleClick = () => setIsOracleInputVisible(true);
  const handleOracleSubmit = () => {
    if (oracleQuery.trim() && !disabled) {
      onAction({ type: 'ask_oracle', label: 'Ask the Oracle', payload: { query: oracleQuery.trim() } });
      setOracleQuery('');
      setIsOracleInputVisible(false);
    }
  };

  return (
    <div className="bg-gray-800 p-4 rounded-lg shadow-xl border border-gray-700">
      <h2 className="text-xl font-bold text-amber-400 mb-4 border-b-2 border-amber-500 pb-2">Actions</h2>

      {/* Top Row: Oracle, Analyze, System Toggles */}
      <div className="mb-4 grid grid-cols-1 gap-2 sm:grid-cols-2">
        {!isOracleInputVisible && (
          <ActionButton 
             action={{ type: 'custom', label: 'Ask the Oracle' }} 
             onClick={handleAskOracleClick} 
             disabled={disabled} 
          />
        )}
        <ActionButton 
          action={{ type: 'ANALYZE_SITUATION', label: 'Analyze Situation' }}
          onClick={onAction}
          disabled={disabled}
        />
      </div>

      {isOracleInputVisible && (
        <div className="mb-4 p-3 border border-purple-500 rounded-lg bg-gray-700/50">
          <input
            type="text"
            value={oracleQuery}
            onChange={(e) => setOracleQuery(e.target.value)}
            placeholder="Ask your question..."
            className="w-full px-3 py-2 bg-gray-900 border border-gray-600 rounded-md text-gray-200 focus:ring-1 focus:ring-purple-500 outline-none mb-2"
            onKeyDown={(e) => e.key === 'Enter' && handleOracleSubmit()}
          />
          <div className="flex gap-2">
            <button onClick={handleOracleSubmit} disabled={disabled || !oracleQuery.trim()} className="flex-1 bg-green-600 text-white py-1 rounded hover:bg-green-500">Submit</button>
            <button onClick={() => setIsOracleInputVisible(false)} className="flex-1 bg-gray-500 text-white py-1 rounded hover:bg-gray-400">Cancel</button>
          </div>
        </div>
      )}
      
      {/* Gemini Generated Actions */}
      <AnimatePresence>
        {geminiGeneratedActions && geminiGeneratedActions.length > 0 && (
          <div className="mb-4">
            <h3 className="text-sm font-semibold text-teal-400 mb-2">Suggested Actions</h3>
            <div className="grid grid-cols-1 gap-2">
              {geminiGeneratedActions.map((action, index) => (
                <ActionButton 
                  key={`gemini-${index}`} 
                  action={action} 
                  onClick={onAction} 
                  disabled={disabled || isOracleInputVisible} 
                  isGeminiAction 
                />
              ))}
            </div>
          </div>
        )}
      </AnimatePresence>

      {/* Standard Context Actions */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
        {generalActions.map((action, index) => (
          <ActionButton 
            key={`gen-${index}`} 
            action={action} 
            onClick={onAction} 
            disabled={disabled || isOracleInputVisible} 
          />
        ))}
      </div>
      
      {/* System/Menu Actions */}
      <div className="mt-6 pt-4 border-t border-gray-700 flex justify-end relative" ref={menuRef}>
         <button
            onClick={() => setIsMenuOpen(!isMenuOpen)}
            disabled={disabled}
            className="flex items-center gap-2 px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded-lg shadow transition-colors"
         >
            {isMenuOpen ? <X size={20} /> : <Menu size={20} />}
            <span>System</span>
            {(unreadDiscoveryCount > 0 || hasNewRateLimitError) && (
              <span className="absolute -top-1 -right-1 h-3 w-3 rounded-full bg-red-500 border-2 border-gray-800 animate-pulse"></span>
            )}
         </button>

         <AnimatePresence>
            {isMenuOpen && (
              <motion.div
                initial={{ opacity: 0, y: 10, scale: 0.95 }}
                animate={{ opacity: 1, y: 0, scale: 1 }}
                exit={{ opacity: 0, y: 10, scale: 0.95 }}
                transition={{ duration: 0.15 }}
                className="absolute bottom-full right-0 mb-2 w-56 bg-gray-800 border border-gray-600 rounded-lg shadow-xl overflow-hidden z-20 flex flex-col p-2 gap-2"
              >
                 <ActionButton className="w-full text-left" action={{ type: 'TOGGLE_DISCOVERY_LOG', label: 'Journal' }} onClick={(a) => { onAction(a); setIsMenuOpen(false); }} disabled={disabled} badgeCount={unreadDiscoveryCount} />
                 <ActionButton className="w-full text-left" action={{ type: 'TOGGLE_QUEST_LOG', label: 'Quests' }} onClick={(a) => { onAction(a); setIsMenuOpen(false); }} disabled={disabled} />
                 <ActionButton className="w-full text-left" action={{ type: 'TOGGLE_LOGBOOK', label: 'Logbook' }} onClick={(a) => { onAction(a); setIsMenuOpen(false); }} disabled={disabled} />
                 <ActionButton className="w-full text-left" action={{ type: 'toggle_party_overlay', label: 'Party' }} onClick={(a) => { onAction(a); setIsMenuOpen(false); }} disabled={disabled} />
                 <ActionButton className="w-full text-left" action={{ type: 'TOGGLE_GAME_GUIDE', label: 'Game Guide' }} onClick={(a) => { onAction(a); setIsMenuOpen(false); }} disabled={disabled} />
                 <div className="h-px bg-gray-600 my-1"></div>
                 <ActionButton className="w-full text-left" action={{ type: 'save_game', label: 'Save Game' }} onClick={(a) => { onAction(a); setIsMenuOpen(false); }} disabled={disabled} />
                 <ActionButton className="w-full text-left" action={{ type: 'go_to_main_menu', label: 'Main Menu' }} onClick={(a) => { onAction(a); setIsMenuOpen(false); }} disabled={disabled} />
                 {isDevDummyActive && (
                    <ActionButton className="w-full text-left" action={{ type: 'toggle_dev_menu', label: 'Dev Menu' }} onClick={(a) => { onAction(a); setIsMenuOpen(false); }} disabled={disabled} hasNotification={hasNewRateLimitError} />
                 )}
              </motion.div>
            )}
         </AnimatePresence>
      </div>
    </div>
  );
};

export default ActionPane;
