/**
 * @file WorldPane.tsx
 * This component displays the game's message log, showing system messages,
 * player actions, and NPC dialogue. It automatically scrolls to the latest message.
 */
import React, { useEffect, useRef, useContext } from 'react';
import { GameMessage } from '../types'; // Path relative to src/components/
import { formatGameTime, getGameDay } from '@/utils/core';
import Tooltip from './ui/Tooltip'; // Import the new Tooltip component
import GlossaryContext from '../context/GlossaryContext';
import { LoreService } from '../services/LoreService';
import { UI_ID } from '../styles/uiIds';

interface WorldPaneProps {
  messages: GameMessage[];
  /**
   * Opening-situation entry status (gameEntry.status). When the player has just
   * spawned and the opening scene is still being generated by the local model,
   * the message log is empty for several seconds. Rather than show a blank panel
   * (the largest element on screen) we render an honest "the world is taking
   * shape" placeholder. This invents NO scene content — it only signals that the
   * real, model-written opening is on its way (consistent with D-NOFB).
   */
  openingStatus?: string;
}

/**
 * WorldPane component.
 * Renders the list of game messages with appropriate styling for different senders.
 * Automatically scrolls to the bottom when new messages are added.
 * @param {WorldPaneProps} props - The props for the component.
 * @returns {React.FC} The rendered WorldPane component.
 */
const WorldPane: React.FC<WorldPaneProps> = ({ messages, openingStatus }) => {
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  const glossaryEntries = useContext(GlossaryContext);

  /**
   * Scrolls the message container to the bottom.
   */
  const scrollToBottom = () => {
    if (scrollContainerRef.current) {
      scrollContainerRef.current.scrollTo({
        top: scrollContainerRef.current.scrollHeight,
        behavior: 'smooth'
      });
    }
  };

  useEffect(scrollToBottom, [messages]); // Scroll when messages change

  /**
   * Determines the CSS class for a message based on its sender.
   * @param {GameMessage['sender']} sender - The sender of the message.
   * @returns {string} The CSS class string.
   */
  const getMessageStyle = (sender: GameMessage['sender']): string => {
    switch (sender) {
      case 'system':
        return 'text-sky-300 italic';
      case 'player':
        return 'text-amber-300';
      case 'npc':
        return 'text-emerald-300';
      default:
        return 'text-gray-300';
    }
  };

  /**
   * Normalizes raw log text before rendering.
   * G14: some upstream entries (notably the "DM Insight" system message produced in
   * handleObservation.ts) arrive with literal markdown bold (`**Situational Analysis:**`)
   * and a pair of stray wrapping double-quotes. We cannot edit that producer here, so we
   * fix it at render time: strip a single pair of outer wrapping quotes, then split the
   * string into bold/plain runs on `**...**` so the bold renders as actual emphasis rather
   * than visible asterisks.
   * @param {string} text - The raw message text.
   * @returns {{ content: string; bold: boolean }[]} Ordered runs to render.
   */
  const normalizeMarkdownRuns = (text: string): { content: string; bold: boolean }[] => {
    let working = text;

    // Strip a single pair of stray wrapping double-quotes, e.g. `DM Insight: "…point to."`.
    // Only when the body (after an optional `Label:` prefix) is fully wrapped in quotes.
    const wrapped = working.match(/^(\s*[^:"]*:\s*)?"([\s\S]*)"\s*$/);
    if (wrapped) {
      working = `${wrapped[1] ?? ''}${wrapped[2]}`;
    }

    // Split on **bold** runs. Even indices are plain, odd indices are bold content.
    const segments = working.split(/\*\*([\s\S]+?)\*\*/g);
    const runs: { content: string; bold: boolean }[] = [];
    segments.forEach((seg, i) => {
      if (seg === '') return;
      runs.push({ content: seg, bold: i % 2 === 1 });
    });
    return runs.length > 0 ? runs : [{ content: working, bold: false }];
  };

  /**
   * Linkifies a single plain-text run against the glossary (tooltip buttons for matched terms).
   * @param {string} text - A plain (non-bold) text run.
   * @param {string} keyPrefix - Stable key prefix to keep React keys unique across runs.
   * @returns {React.ReactNode} The run, potentially with Tooltip components.
   */
  const linkifyRun = (text: string, keyPrefix: string): React.ReactNode => {
    // RALPH: Knowledge Injector.
    // Uses the LoreService to dynamically match text against the full game glossary.
    // This provides on-demand help for rules, items, and lore.
    if (!glossaryEntries || glossaryEntries.length === 0) return text;

    const matchedEntries = LoreService.findTermsInText(text, glossaryEntries);
    if (matchedEntries.length === 0) return text;

    // Create regex from matched entry titles and aliases
    const terms = matchedEntries.flatMap(e => [e.title, ...(e.aliases || [])]);
    const regex = LoreService.getTermsRegex(terms);

    const parts = text.split(regex);

    return parts.map((part, index) => {
      const lowerPart = part.toLowerCase();
      // Find which entry matched this specific part
      const entry = matchedEntries.find(e =>
        e.title.toLowerCase() === lowerPart ||
        e.aliases?.some(a => a.toLowerCase() === lowerPart)
      );

      if (entry) {
        return (
          <Tooltip
            key={`${keyPrefix}-${part}-${index}-tooltip`}
            content={entry.excerpt || entry.title}
          >
            <button
              type="button"
              className="text-sky-400 underline decoration-sky-500/70 decoration-dotted cursor-help bg-transparent border-0 p-0"
            >
              {part}
            </button>
          </Tooltip>
        );
      }
      return part;
    });
  };

  /**
   * Processes message text: strips stray quotes, renders markdown bold, and linkifies
   * glossary terms within the plain runs.
   * @param {string} text - The message text.
   * @returns {React.ReactNode} The rendered message body.
   */
  const processMessageText = (text: string): React.ReactNode => {
    const runs = normalizeMarkdownRuns(text);
    return runs.map((run, i) =>
      run.bold ? (
        <strong key={`b-${i}`} className="font-semibold">
          {linkifyRun(run.content, `b-${i}`)}
        </strong>
      ) : (
        <React.Fragment key={`p-${i}`}>{linkifyRun(run.content, `p-${i}`)}</React.Fragment>
      )
    );
  };


  return (
    <div
      id={UI_ID.WORLD_PANE}
      data-testid={UI_ID.WORLD_PANE}
      ref={scrollContainerRef}
      className="flex-grow bg-gray-800 p-6 rounded-lg shadow-xl overflow-y-auto scrollable-content border border-gray-700 min-h-0"
    >
      {' '}
      {/* Added min-h-0 for flex-grow with overflow */}
      {/*
        G13: pad the right edge so right-aligned (player) bubbles never run underneath the
        clipped PARTY CHAT drawer tab pinned to the top-right of the viewport.
      */}
      <h2 className="text-2xl font-bold text-amber-400 mb-4 border-b-2 border-amber-500 pb-2 pr-10">
        Log
      </h2>
      {/*
        G10: constrain the log to a readable, centered column instead of letting entries hug
        the far left/right edges of a ~900px-wide panel. Bubbles + per-side alignment make the
        "right = me (player), left = world" convention (G11) legible at a glance.
      */}
      <div className="mx-auto w-full max-w-3xl space-y-3 text-lg leading-relaxed pr-8">
        {messages.length === 0 && openingStatus === 'generating' && (
          <div
            data-testid="world-pane-opening-generating"
            className="flex flex-col items-center justify-center text-center py-16 px-6 text-gray-400"
          >
            <span
              className="inline-block w-3 h-3 rounded-full bg-amber-400 animate-pulse mb-4"
              aria-hidden="true"
            />
            <p className="text-amber-200/90 text-lg font-medium">
              The world is taking shape around you&hellip;
            </p>
            <p className="text-sm text-gray-500 mt-2 max-w-md">
              Your opening scene is being written. This can take a few moments while
              the story finds you.
            </p>
          </div>
        )}
        {messages.map((msg) => {
          const isBanter = msg.metadata?.type === 'banter';

          if (isBanter) {
            // Extract name and text if possible (format: Name: "Text")
            const match = msg.text.match(/^([^:]+): "(.*)"$/);
            const speakerName = match ? match[1] : '';
            const dialogue = match ? match[2] : msg.text;

            // Banter is "world" voice → left-aligned bubble (G11).
            return (
              <div key={msg.id} className="flex justify-start">
                <div className="max-w-[85%] p-4 rounded-xl bg-gray-900/60 border border-amber-900/30 shadow-sm">
                  {speakerName && (
                    <h4 className="text-amber-500 text-xs font-bold uppercase tracking-wider mb-1">
                      {speakerName}
                    </h4>
                  )}
                  <p className="text-amber-100 italic text-base leading-relaxed">
                    &quot;{processMessageText(dialogue)}&quot;
                  </p>
                  <p className="text-[10px] text-gray-500 mt-2 text-right">
                    {formatGameTime(new Date(msg.timestamp), {
                      hour: '2-digit',
                      minute: '2-digit',
                    })}
                  </p>
                </div>
              </div>
            );
          }

          // G11: consistent alignment semantics — the player's own actions are "me"
          // (right), everything the world says back (system narration, NPC dialogue) is
          // "world" (left). One rule, applied to every non-banter entry.
          const isPlayer = msg.sender === 'player';
          const bubbleTone = isPlayer
            ? 'bg-amber-500/10 border border-amber-500/20'
            : 'bg-gray-900/50 border border-gray-700/60';

          return (
            <div
              key={msg.id}
              className={`flex ${isPlayer ? 'justify-end' : 'justify-start'}`}
            >
              <div className={`max-w-[85%] px-4 py-2 rounded-2xl shadow-sm ${bubbleTone}`}>
                <p className={`${getMessageStyle(msg.sender)} ${isPlayer ? 'text-right' : 'text-left'}`}>
                  {processMessageText(msg.text)}
                </p>
                <p className={`text-xs text-gray-500 mt-1 ${isPlayer ? 'text-right' : 'text-left'}`}>
                  {formatGameTime(new Date(msg.timestamp), {
                    hour: '2-digit',
                    minute: '2-digit',
                  })}
                </p>
              </div>
            </div>
          );
        })}

      </div>
    </div>
  );
};

export default WorldPane;
