/**
 * @file WorldPane.tsx
 * This component displays the game's message log, showing system messages,
 * player actions, and NPC dialogue. It automatically scrolls to the latest message.
 */
import React from 'react';
import { GameMessage } from '../types';
interface WorldPaneProps {
    messages: GameMessage[];
    /**
     * Opening-situation entry status (gameEntry.status). When the player has just
     * spawned and the opening scene is still being generated by the local model,
     * the message log is empty for several seconds. Rather than show a blank panel
     * (the largest element on screen) we render an honest "the world is taking
     * shape" placeholder. This invents NO scene content — it only signals that the
     * real, model-written opening is on its way (consistent with D-NOFB).
     */
    openingStatus?: string;
}
/**
 * WorldPane component.
 * Renders the list of game messages with appropriate styling for different senders.
 * Automatically scrolls to the bottom when new messages are added.
 * @param {WorldPaneProps} props - The props for the component.
 * @returns {React.FC} The rendered WorldPane component.
 */
declare const WorldPane: React.FC<WorldPaneProps>;
export default WorldPane;
