/**
 * This module owns the strict spell-template vocabulary used by the runtime audit.
 *
 * The main audit script asks whether each spell follows the shared structured
 * markdown and runtime JSON contract. Keeping the allowed labels and accepted
 * enum-like values here makes bucket migrations easier to review: adding a new
 * field family changes this registry, while the audit script keeps the checking
 * and report-writing behavior.
 *
 * Called by: `auditSpellRuntimeTemplate.ts`.
 * Depends on: no runtime data; this file is the static vocabulary registry.
 */

// ============================================================================
// Strict Template Vocabulary
// ============================================================================
// This section is the canonical field vocabulary for the current strict audit.
// If a future bucket needs a new field, it should be added here deliberately
// instead of appearing as an unreviewed one-off label in a spell file.
// ============================================================================

export const CANONICAL_STRUCTURED_LABELS = new Set([
  'Level',
  'School',
  'Ritual',
  'Classes',
  'Sub-Classes',
  'Access Grants',
  'Casting Time Value',
  'Casting Time Unit',
  'Combat Cost',
  'Reaction Trigger',
  'Range Type',
  'Range Distance',
  'Range Distance Unit',
  'Targeting Type',
  'Targeting Range',
  'Targeting Range Unit',
  'Targeting Max',
  'Target Participation Requires Full Casting Range',
  'Target Participation Notes',
  'Target Cluster Requirement',
  'Target Cluster Max Distance',
  'Target Cluster Distance Unit',
  'Target Cluster Scope',
  'Target Cluster Notes',
  'Per Target Choice Type',
  'Per Target Choice Scope',
  'Per Target Choice Options',
  'Per Target Choice Different Choices Allowed',
  'Per Target Choice Required',
  'Per Target Choice Notes',
  'Area Target Selection Mode',
  'Area Target Selection Scope',
  'Area Target Selection Count',
  'Area Target Selection Excludes Unchosen',
  'Area Target Selection Requires Line Of Sight',
  'Area Target Selection Notes',
  'Target Instance Type',
  'Target Instance Base Count',
  'Target Instance Scaling Rule',
  'Target Instance Assignment',
  'Target Instance Resolution',
  'Target Instance Notes',
  'Valid Targets',
  'Line of Sight',
  'Target Willingness',
  'Target Object Worn Or Carried',
  'Target Object Magical Status',
  'Target Object Fixed To Surface',
  'Target Object Max Size',
  'Target Object Max Weight Pounds',
  'Target Object Max Weight Scaling',
  'Target Can Hear Caster',
  'Target Can Understand Caster',
  'Target Can See Caster',
  'Target Ability Threshold Ability',
  'Target Ability Threshold Operator',
  'Target Ability Threshold Value',
  'Target Self Relation',
  'Target Excluded Creature Types',
  'Target Filter Sizes',
  'Target Filter Notes',
  'Area Shape',
  'Area Size',
  'Area Size Type',
  'Area Size Unit',
  'Area Height',
  'Area Height Unit',
  'Area Width',
  'Area Width Unit',
  'Area Thickness',
  'Area Thickness Unit',
  'Area Follows Caster',
  'Verbal',
  'Somatic',
  'Material',
  'Material Description',
  'Material Cost GP',
  'Consumed',
  'Duration Type',
  'Duration Value',
  'Duration Unit',
  'Concentration',
  'Effect Type',
  'Attack Roll',
  'Damage Dice',
  'Damage Flat',
  'Damage Type',
  'Damage Mitigation Bypass',
  'Primary Damage Dice',
  'Primary Damage Type',
  'Secondary Damage Dice',
  'Secondary Damage Type',
  'Secondary Target Trigger',
  'Secondary Target Origin',
  'Secondary Target Range',
  'Secondary Target Range Unit',
  'Secondary Target Valid Targets',
  'Secondary Target Selection',
  'Secondary Target Must Be Different',
  'Secondary Target Requires Line Of Sight',
  'Secondary Target Requires Attack Roll',
  'Secondary Target Requires Damage Roll',
  'Secondary Target Repeat Rule',
  'Secondary Target Max Leaps',
  'Secondary Target Unique Per Casting',
  'Secondary Target Notes',
  'Mode Choice Type',
  'Mode Choice Timing',
  'Mode Choice Option Count',
  'Mode Choice Options Source',
  'Mode Choice Max Active Noninstantaneous',
  'Mode Choice Can Dismiss Active',
  'Mode Choice Notes',
  'Attack Augments',
  'Ability Check Modifier Applies To',
  'Ability Check Modifier Bonus Dice',
  'Ability Check Modifier Flat Modifier',
  'Ability Check Modifier Skill Selection',
  'Ability Check Modifier Skill Chooser',
  'Ability Check Modifier Skill Pool',
  'Ability Check Modifier Frequency',
  'Ability Check Modifier Duration Scope',
  'Ability Check Modifier Notes',
  'Controlled Entity Type',
  'Controlled Entity Count',
  'Controlled Entity Appears At',
  'Controlled Entity Duration Scope',
  'Controlled Entity Control Action Type',
  'Controlled Entity Initial Use On Cast',
  'Controlled Entity Later Control Timing',
  'Controlled Entity Movement Distance',
  'Controlled Entity Movement Unit',
  'Controlled Entity Max Distance From Caster',
  'Controlled Entity Can Attack',
  'Controlled Entity Can Activate Magic Items',
  'Controlled Entity Carry Capacity Pounds',
  'Controlled Entity Allowed Interactions',
  'Controlled Entity Ending Triggers',
  'Controlled Entity Notes',
  'Effect Schedule Timing',
  'Effect Schedule Entry Count',
  'Effect Schedule Notes',
  'Healing Dice',
  'Save Stat',
  'Save Outcome',
  'Save Cover Ignored',
  'Save Auto Outcome',
  'Save Auto Outcome Condition',
  'Repeat Save Timing',
  'Repeat Save Additional Timings',
  'Repeat Save Type',
  'Repeat Save Success Ends',
  'Repeat Save Prerequisites',
  'Repeat Save Progression',
  'Escape Check Ability',
  'Escape Check Skill',
  'Escape Check DC',
  'Escape Check Action Cost',
  'Escape Check Eligible Actors',
  'Secondary Save Stat',
  'Secondary Save Outcome',
  'Conditions Applied',
  'Conditions Removed',
  'Condition Break Triggers',
  'Utility Type',
  'Utility Options',
  'Terrain Type',
  'Defense Type',
  'Defense Value',
  'Condition Immunities',
  'Prevention Immunities',
  'Damage Type Exclusions',
  'Defense Damage Type Source',
  'Damage Reduction Dice',
  'Damage Reduction Applies To',
  'Damage Reduction Frequency',
  'Defense Source Categories',
  'Defense Source Attack Magical Status',
  'Barrier Damage Block Directions',
  'Barrier Damage Block Source Categories',
  'Spell Effect Prevention Source Side',
  'Spell Effect Prevention Max Spell Level',
  'Spell Effect Prevention Affected Subjects',
  'Spell Effect Prevention Excludes Area Of Effect',
  'Linked Damage Trigger',
  'Linked Damage Recipient',
  'Linked Damage Amount',
  'Linked Damage Amount Basis',
  'Linked Damage Type Source',
  'Linked Damage Recipient Mitigation',
  'Resistance Suppression Damage Types',
  'Resistance Suppression Damage Type Source',
  'Damage Interaction Modes',
  'Damage Interaction Damage Types',
  'Damage Interaction Damage Type Source',
  'Damage Interaction Subject Scope',
  'Damage Interaction Duration Scope',
  'Condition Suppressions',
  'Condition Immunity Source Creature Types',
  'Attack Roll Modifier',
  'Attack Roll Direction',
  'Attack Roll Kind',
  'Attack Roll Consumption',
  'Attack Roll Duration',
  'Attack Roll Notes',
  'Exploration Time Value',
  'Exploration Time Unit',
  'Exploration Cost Value',
  'Exploration Cost Unit',
  'Triggered Applications',
  'Light Bright Radius',
  'Light Dim Radius',
  'Light Color Choice',
  'Light Opaque Cover Blocks',
  'Light Emits Heat',
  'Light Ignites Objects',
  'Light Consumes Fuel',
  'Light Can Be Covered Or Hidden',
  'Light Can Be Smothered Or Quenched',
  'Sound Audible Radius',
  'Sound Audible Radius Unit',
  'Sound Source',
  'Sound Trigger',
  'Conditional Ending Triggers',
  'Conditional Ending Scope',
  'Conditional Ending Distance Feet',
  'Conditional Ending Duration Value',
  'Conditional Ending Duration Unit',
  'Duration Progression Trigger',
  'Duration Progression Required Casts',
  'Duration Progression Cadence',
  'Duration Progression Same Target Required',
  'Duration Progression Same Location Required',
  'Duration Progression Same Configuration Required',
  'Duration Progression Requires Full Concentration',
  'Duration Progression Extension',
  'Duration Progression Outcome',
  'Duration Progression Dispellable',
  'Death Prevention Triggers',
  'Death Prevention Drop To Hit Points',
  'Death Prevention Negates Instant Death Without Damage',
  'Death Prevention Consumption',
  'Death Prevention Scope',
  'End Cleanup Trigger',
  'End Cleanup Removes',
  'End Cleanup Source',
  'End Cleanup Scope',
  'End Cleanup Amount',
  'End Cleanup Consequence',
  'End Cleanup Destination',
  'End Cleanup Prevented By',
  'Sustain Requirement Timing',
  'Sustain Requirement Actor',
  'Sustain Requirement Action Type',
  'Sustain Requirement Action Cost',
  'Sustain Requirement Failure Outcome',
  'Granted Action Actor',
  'Granted Action Name',
  'Granted Action Type',
  'Granted Action Frequency',
  'Granted Action Area Shape',
  'Granted Action Area Size',
  'Granted Action Area Size Unit',
  'Granted Action Effect Indices',
  'Granted Action Prerequisites',
  'Fall Descent Rate',
  'Fall Descent Rate Unit',
  'Fall Damage On Landing',
  'Fall Control Ends On Landing',
  'Sensory Manifestation Mode Source',
  'Sensory Manifestation Variant Count',
  'Illusion Reveal Scope',
  'Illusion Reveal Methods',
  'Illusion Reveal Action Cost',
  'Illusion Reveal Ability',
  'Illusion Reveal Skill',
  'Illusion Reveal DC',
  'Illusion Reveal Applies To',
  'Illusion Discerned State',
  'Target Filter Creature Types',
  'Damage Trigger',
  'Control Options',
  'Movement Type',
  'Forced Movement',
  'Temporary HP',
  'Flood',
  'Part Water',
  'Redirect Flow',
  'Whirlpool',
  'Armor Class',
  'Hit Points',
  'Speed',
  'Senses',
  'Languages',
  'Description',
  'Higher Levels',
]);

export const NUMBERED_STRUCTURED_LABEL_PATTERNS = [
  /^Access Grant \d+ (Source Type|Class|Feature|Access Type|Automatic|Consumes Selection|Notes)$/,
  /^Utility Option \d+ (Name|Effect|Details)$/,
  /^Save Modifier \d+ (Type|Target Creature Types|Reason)$/,
  /^Spatial Form \d+ (Label|Shape|Size Value|Size Type|Size Unit|Height Value|Height Unit|Width Value|Width Unit|Thickness Value|Thickness Unit|Segment Count|Segment Width Value|Segment Width Unit|Segment Height Value|Segment Height Unit|Notes)$/,
  /^Spatial Detail \d+ (Label|Kind|Subject|Value|Unit|Qualifier|Notes)$/,
  /^Mode Choice Option \d+ (Label|Summary|Effect Indices|Control Option Indices|Effect Types|Duration|Notes)$/,
  /^Sensory Manifestation Variant \d+ (Label|Allowed Senses|Excluded Senses|Volume Range|Timing|Max Shape|Max Size|Max Size Unit)$/,
  /^Attack Augment \d+ (Attack Type|Weapon Types|Weapon Proficiency Required|Weapon Minimum Value CP|Weapon Held By Caster|Granted Attack Timing|Granted Attack Count|Uses Casting Weapon|Ability Attack Roll|Ability Damage Roll|Ability Replaces|Damage Die Override|Damage Die Scaling|Damage Type Choice Timing|Damage Type Choice Options|Additional Damage Dice|Additional Damage Type|Applies On|Notes)$/,
  /^Ability Check Modifier (Applies To|Bonus Dice|Flat Modifier|Skill Selection|Skill Chooser|Skill Pool|Frequency|Duration Scope|Notes)$/,
  /^Controlled Entity (Type|Count|Appears At|Duration Scope|Control Action Type|Initial Use On Cast|Later Control Timing|Movement Distance|Movement Unit|Max Distance From Caster|Can Attack|Can Activate Magic Items|Carry Capacity Pounds|Allowed Interactions|Ending Triggers|Notes)$/,
  /^Effect Schedule Entry \d+ (Label|Timing|Turn Start|Turn End|Effect Indices|Effect Types|Target Count|Target Valid Targets|Target Selection|Target Must Be Different|Summary|Notes)$/,
  /^Scaling Rule \d+ (Type|Applies To|Base|Levels|Bonus Per Level|Slot Level|Area Size|Target Count|Notes)$/,
];

export const DEPRECATED_LABEL_REPLACEMENTS = new Map([
  ['Range Unit', 'Range Distance Unit'],
  ['Effect Types', 'Effect Type'],
  ['Condition', 'Conditions Applied'],
  ['Additional Damage', 'Secondary Damage Dice / Secondary Damage Type'],
]);

export const CASTING_TIME_UNITS = new Set(['action', 'bonus_action', 'reaction', 'minute', 'hour', 'special']);
export const RANGE_TYPES = new Set(['self', 'touch', 'ranged', 'sight', 'unlimited', 'special']);
export const DISTANCE_UNITS = new Set(['feet', 'miles', 'inches']);
export const DURATION_TYPES = new Set(['instantaneous', 'timed', 'special', 'until_dispelled', 'until_dispelled_or_triggered']);
export const DURATION_UNITS = new Set(['round', 'minute', 'hour', 'day']);
export const AREA_SHAPES = new Set(['Cone', 'Cube', 'Cylinder', 'Line', 'Sphere', 'Square', 'Circle', 'Emanation', 'Wall', 'Hemisphere', 'Ring']);
export const AREA_SIZE_TYPES = new Set(['radius', 'diameter', 'length', 'edge', 'side', 'square']);
export const TARGET_WILLINGNESS = new Set(['required', 'not_applicable']);
export const TARGET_OBJECT_WORN_OR_CARRIED = new Set(['excluded', 'not_applicable']);
export const TARGET_OBJECT_MAGICAL_STATUS = new Set(['any', 'nonmagical', 'not_applicable']);
export const TARGET_OBJECT_FIXED_TO_SURFACE = new Set(['excluded', 'not_applicable']);
export const TARGET_COMMUNICATION_PREREQUISITE = new Set(['required', 'not_applicable']);
export const TARGET_ABILITY_THRESHOLD_ABILITIES = new Set(['Strength', 'Dexterity', 'Constitution', 'Intelligence', 'Wisdom', 'Charisma', 'not_applicable']);
export const TARGET_ABILITY_THRESHOLD_OPERATORS = new Set(['greater_than', 'greater_than_or_equal', 'less_than', 'less_than_or_equal', 'not_applicable']);
export const TARGET_SELF_RELATION = new Set(['must_be_self', 'must_be_other', 'self_allowed', 'not_applicable']);
export const AREA_TARGET_SELECTION_MODES = new Set(['all_valid_targets', 'caster_choice', 'random', 'not_applicable']);
export const AREA_TARGET_SELECTION_SCOPES = new Set(['creatures_in_area', 'not_applicable']);
export const AREA_TARGET_SELECTION_COUNTS = new Set(['all_chosen', 'not_applicable']);
export const TARGET_INSTANCE_TYPES = new Set(['dart', 'beam', 'ray', 'projectile', 'light', 'animated_tree', 'controlled_undead', 'not_applicable']);
export const TARGET_INSTANCE_ASSIGNMENTS = new Set(['same_or_different_targets', 'unique_targets', 'single_target_only', 'independent_positions', 'not_applicable']);
export const TARGET_INSTANCE_RESOLUTIONS = new Set(['simultaneous', 'sequential', 'persistent', 'not_applicable']);
export const TARGET_CLUSTER_REQUIREMENTS = new Set(['required', 'not_applicable']);
export const TARGET_CLUSTER_SCOPES = new Set(['all_targets', 'not_applicable']);
export const PER_TARGET_CHOICE_TYPES = new Set(['ability', 'not_applicable']);
export const PER_TARGET_CHOICE_SCOPES = new Set(['each_target', 'not_applicable']);
export const SECONDARY_TARGET_TRIGGERS = new Set(['primary_hit', 'duplicate_damage_die', 'not_applicable']);
export const SECONDARY_TARGET_ORIGINS = new Set(['primary_target', 'previous_target', 'not_applicable']);
export const SECONDARY_TARGET_VALID_TARGETS = new Set(['creature', 'creature_or_object', 'not_applicable']);
export const SECONDARY_TARGET_SELECTIONS = new Set(['caster_choice', 'not_applicable']);
export const SECONDARY_TARGET_REPEAT_RULES = new Set(['none', 'slot_level_max_leaps', 'not_applicable']);
export const SECONDARY_TARGET_MAX_LEAPS = new Set(['slot_level', 'not_applicable']);
export const MODE_CHOICE_TYPES = new Set(['choose_one', 'not_applicable']);
export const MODE_CHOICE_TIMINGS = new Set(['on_cast', 'on_cast_or_later_action', 'not_applicable']);
export const MODE_CHOICE_OPTIONS_SOURCES = new Set(['modeChoice.options', 'effects', 'controlOptions', 'mixed', 'not_applicable']);
export const EFFECT_SCHEDULE_TIMINGS = new Set(['caster_later_turn_start', 'not_applicable']);
export const TARGETING_TYPES = new Set([
  'self',
  'single',
  'multi',
  'area',
  'melee',
  'ranged',
  'point',
  'creature',
  'object',
  'creature_or_object',
  'touch',
  'creature or object',
  'creatures',
]);
export const VALID_TARGETS = new Set([
  'self',
  'creatures',
  'allies',
  'enemies',
  'objects',
  'point',
  'ground',
  'creature',
  'creature_or_object',
  'object',
  'humanoid',
  'humanoids',
  'willing_creature',
  'willing_beast',
  'beast_tiny',
  'corpse',
  'manufactured_metal_object',
  'none',
  'location',
  'plants',
  'dead_creature',
  'nonmagical_weapon',
  'creature_hit',
  'creature_touched',
  'creature_or_location',
  'corpses',
  'weapons',
  'beasts',
  'unoccupied space',
  'location_or_object',
  'creature_object_or_effect',
  'creature_hearing',
  'creature_casting',
  'creatures_visual',
  'stone_surface',
  'quiver_of_arrows',
  'object_or_surface',
]);
export const SAVE_OUTCOMES = new Set([
  'none',
  'half',
  'negates_condition',
  'negates',
  'half damage; negates movement',
  'negates_repeat',
  'negates_effect',
]);
export const SAVE_COVER_IGNORED = new Set([
  'half',
  'three_quarters',
  'total',
]);
export const SAVE_AUTO_OUTCOMES = new Set([
  'auto_success',
  'auto_failure',
]);
export const SAVE_AUTO_OUTCOME_CONDITIONS = new Set([
  'challenge_rating_not_zero',
  'fighting_caster_or_allies',
  'cannot_understand_caster',
  'immune_to_charmed',
  'immune_to_frightened',
  'is_shapechanger',
  'is_plant_creature',
  'not_humanoid',
  'recently_affected_by_spell',
]);
export const REPEAT_SAVE_TIMINGS = new Set([
  'turn_end',
  'turn_start',
  'on_damage',
  'on_action',
  'after_forced_movement',
  'not_applicable',
]);
export const REPEAT_SAVE_TYPES = new Set([
  'Strength',
  'Dexterity',
  'Constitution',
  'Intelligence',
  'Wisdom',
  'Charisma',
  'strength_check',
  'wisdom_check',
  'not_applicable',
]);
export const REPEAT_SAVE_PREREQUISITES = new Set([
  'no_line_of_sight_to_caster',
  'not_applicable',
]);
export const SOUND_RADIUS_UNITS = new Set([
  'feet',
  'miles',
  'not_applicable',
]);
export const SOUND_SOURCES = new Set([
  'caster',
  'target',
  'target_object',
  'origin_space',
  'spell_area',
  'not_applicable',
]);
export const SOUND_TRIGGERS = new Set([
  'on_cast',
  'on_hit',
  'after_teleport',
  'on_trigger',
  'not_applicable',
]);
export const CONDITIONAL_ENDING_TRIGGERS = new Set([
  'end_on_recast',
  'caster_leaves_area',
  'holder_releases_item',
  'caster_or_ally_damages_target',
  'caster_or_companion_harms_target',
  'target_takes_damage_or_witnesses_allies_damaged',
  'all_target_instances_expended',
  'temporary_hit_points_depleted',
  'target_drops_to_0_hp',
  'target_uses_magic_action_to_end_effect',
  'target_dons_armor',
  'target_lands',
  'target_makes_attack_roll',
  'target_casts_spell',
  'target_deals_damage',
  'carried_weight_exceeds_limit',
  'created_entity_drops_to_0_hp',
  'created_entity_takes_damage',
  'caster_drops_to_0_hp',
  'linked_creatures_separated_beyond_distance',
  'spell_cast_again_on_connected_creature',
  'target_outside_spell_range',
  'target_has_total_cover_from_caster',
  'strong_wind_disperses_effect',
  'initial_save_success',
  'repeat_save_success',
  'sustain_action_not_taken',
  'suggested_activity_completed',
  'already_on_destination_plane',
  'unsupported_area_collapses_next_turn',
  'certain_death_activity_requested',
  'drop_to_0_hp_prevented',
  'instant_death_no_damage_prevented',
  'on_attack_hit',
  'on_attack_hit_or_miss',
  'beyond_max_distance',
  'inscribed_ward_moved_beyond_distance',
  'ward_triggered',
  'triggered_duration_expires',
  'disintegrate_targets_effect',
  'no_creature_restrained_by_spell_after_trigger',
  'not_applicable',
]);
export const ESCAPE_CHECK_ABILITIES = new Set([
  'Strength',
  'Dexterity',
  'Constitution',
  'Intelligence',
  'Wisdom',
  'Charisma',
  'not_applicable',
]);
export const ESCAPE_CHECK_ACTION_COSTS = new Set(['action', 'bonus_action', 'not_applicable']);
export const ESCAPE_CHECK_ELIGIBLE_ACTORS = new Set([
  'affected_creature',
  'creature_that_can_reach_affected_creature',
  'not_applicable',
]);
export const CONDITIONAL_ENDING_SCOPES = new Set([
  'spell',
  'effect',
  'item',
  'area',
  'not_applicable',
]);
export const SENSORY_MANIFESTATION_MODE_SOURCES = new Set([
  'modeChoice.options',
  'effect',
  'not_applicable',
]);
export const SENSORY_CHANNELS = new Set([
  'sight',
  'sound',
  'light',
  'smell',
  'other_sensory_effect',
  'not_applicable',
]);
export const SENSORY_MANIFESTATION_VOLUME_RANGES = new Set([
  'whisper_to_scream',
  'not_applicable',
]);
export const SENSORY_MANIFESTATION_TIMINGS = new Set([
  'continuous',
  'discrete_before_spell_end',
  'continuous_or_discrete_before_spell_end',
  'not_applicable',
]);
export const SENSORY_MANIFESTATION_SHAPES = new Set([
  'Cube',
  'Sphere',
  'Line',
  'Cone',
  'Cylinder',
  'not_applicable',
]);
export const SENSORY_MANIFESTATION_SIZE_UNITS = new Set([
  'feet',
  'not_applicable',
]);
export const ILLUSION_REVEAL_SCOPES = new Set([
  'per_creature',
  'global',
  'not_applicable',
]);
export const ILLUSION_REVEAL_METHODS = new Set([
  'study_action',
  'physical_interaction',
  'not_applicable',
]);
export const ILLUSION_REVEAL_ACTION_COSTS = new Set([
  'action',
  'not_applicable',
]);
export const ILLUSION_REVEAL_ABILITIES = new Set([
  'Intelligence',
  'not_applicable',
]);
export const ILLUSION_REVEAL_SKILLS = new Set([
  'Investigation',
  'not_applicable',
]);
export const ILLUSION_REVEAL_DCS = new Set([
  'spell_save_dc',
  'not_applicable',
]);
export const ILLUSION_DISCERNED_STATES = new Set([
  'faint_to_discerning_creature',
  'transparent_to_discerning_creature',
  'not_applicable',
]);
export const BOOLEAN_SENTINEL = new Set([
  'true',
  'false',
  'not_applicable',
]);
export const LIGHT_COLOR_CHOICES = new Set([
  'caster_choice',
  'fixed',
  'not_applicable',
]);
export const EFFECT_TYPES = new Set([
  'DAMAGE',
  'HEALING',
  'STATUS_CONDITION',
  'ATTACK_ROLL_MODIFIER',
  'MOVEMENT',
  'SUMMONING',
  'TERRAIN',
  'UTILITY',
  'DEFENSIVE',
  'BUFF',
  'DEBUFF',
  'STATUS',
  'SUMMON',
  'CONTROL',
  'TELEPORT',
  'RESURRECTION',
  'DEFENSE',
  'BLINDNESS',
  'WARD',
  'PETRIFICATION',
  'BANISHMENT',
  'RESTRAINT',
]);
