/**
 * ARCHITECTURAL ADVISORY:
 * SHARED UTILITY: Multiple systems rely on these exports.
 *
 * Last Sync: 15/07/2026, 09:56:09
 * Dependents: systems/combat/fightInPlace/activeGroundCombatSession.ts, systems/combat/worldScenario/liveSettlementEncounter.ts, systems/combat/worldScenario/settlementDefenderProjection.ts, systems/combat/worldScenario/statePatrolWorldEvent.ts, systems/combat/worldScenario/worldBattleScenario.ts
 * Imports: 7 files
 *
 * MULTI-AGENT SAFETY:
 * If you modify exports/imports, re-run the sync tool to update this header:
 * > npx tsx misc/dev_hub/codebase-visualizer/server/index.ts --sync [this-file-path]
 * See misc/dev_hub/codebase-visualizer/VISUALIZER_README.md for more info.
 */
/**
 * This file decides whether a generated settlement patrol may become enemies.
 *
 * WorldForge supplies the settlement and controlling state, but those facts do
 * not say what the party has done. Combat therefore requires two independent
 * receipts: an explicit confrontation trigger and matching player-state
 * evidence (a witnessed local crime or a hostile state standing). Missing or
 * mismatched evidence keeps the patrol out of the enemy team.
 *
 * Called by: worldBattleScenario while attaching a defending force
 * Depends on: the existing crime-location and faction-standing semantics
 */
import type { Crime } from '@/types/crime';
import type { PlayerFactionStanding } from '@/types/factions';
import type { BattleMapSettlementHostility, BattleMapSettlementHostilityTrigger } from '@/types/combat';
import type { GroundSettlementDefense } from '@/systems/worldforge/bridge/settlementDefense';
export type SettlementEncounterTrigger = Exclude<BattleMapSettlementHostilityTrigger, {
    kind: 'none';
}>;
export interface SettlementEncounterHostilityInput {
    trigger?: SettlementEncounterTrigger;
    knownCrimes?: readonly Crime[];
    playerStanding?: Pick<PlayerFactionStanding, 'factionId' | 'publicStanding'>;
}
/** Stable faction key for an FMG state that is not part of the authored faction registry. */
export declare function worldforgeStateFactionId(stateId: number): string;
/** Crime and confrontation systems key procedural locations by atlas cell. */
export declare function settlementDefenseLocationId(defense: GroundSettlementDefense): string;
/**
 * Resolve patrol hostility without mutating WorldForge or player state.
 *
 * A bad standing or wanted record is not enough by itself: guards only enter
 * combat when a matching scene trigger says a confrontation is happening now.
 */
export declare function resolveSettlementEncounterHostility(defense: GroundSettlementDefense, input?: SettlementEncounterHostilityInput): BattleMapSettlementHostility;
/**
 * Create the explicit player-state fixture used by the Legium visual scenario.
 * The fixture is labeled at every layer so it can prove the hostility bridge
 * without pretending a witnessed assault was generated by WorldForge.
 */
export declare function createVisualHarnessWantedWatchInput(defense: GroundSettlementDefense, fixtureId: string): SettlementEncounterHostilityInput;
/**
 * Create the explicitly labeled hostile-standing fixture used by the state
 * patrol visual scenario. The generated state and faction id still come from
 * the real settlement defense; only the player's hostile standing is synthetic.
 */
export declare function createVisualHarnessHostileStateInput(defense: GroundSettlementDefense, fixtureId: string): SettlementEncounterHostilityInput;
