/**
 * ============================================================================
 * TREE INSTANCE BATCHING FOR GPU RENDERING
 * ============================================================================
 *
 * WHAT THIS FILE DOES:
 * This file combines scattered trees from multiple terrain chunks into large,
 * single-draw-call batches for the 3D graphics card.
 *
 * WHY IT EXISTS:
 * If every chunk submitted its own instanced meshes, a single camera view would trigger
 * hundreds of separate draw calls with only a few trees each, crippling frame rates.
 * Batching merges all loaded trees sharing the same model (species/biome, variant, and
 * shadow tier) into one unified buffer across all active chunks.
 *
 * KEY CAPABILITIES:
 * - Preset Batching (`buildTreeBatches`): Scales instances using species baseline tables.
 * - Grown Batching (`buildGrownTreeBatches`): Scales instances using per-variant measured
 *   heights (`grownTreeHeightM`) so each climate variation renders with correct proportions.
 *
 * HOW IT CONNECTS:
 * - Called by: VegetationTreeField.tsx and grownTreeWiring.ts to prepare scene meshes.
 * - Calls into: treeInstancePartition.ts, grownTreeVariants.ts, and treeMeshGenerator.ts.
 * ============================================================================
 */

import type { VegetationScatter } from '../../world3d/types';
import type { TreeSpecies } from './treeMeshGenerator';
import { SPECIES_HEIGHT_M, TREE_SPECIES, VARIANTS_PER_SPECIES } from './treeMeshGenerator';
import { partitionGrownTreeInstances, partitionTreeInstances } from './treeInstancePartition';
import { GROWN_VARIANTS_PER_BIOME, grownTreeHeightM } from './grownTreeVariants';

// ============================================================================
// TYPES & INTERFACES
// ============================================================================

/** Input contribution from a single chunk including local scatter and scene offset. */
export interface TreeBatchInput {
  /** The vegetation scatter data generated by the chunk loader. */
  scatter: VegetationScatter;
  /** Offset in scene units (X, Y, Z) added to all chunk-local coordinates. */
  offset: readonly [number, number, number];
  /** True if instances in this chunk are close enough to cast shadows. */
  castShadow: boolean;
}

/** Flat, world-space instance data for a legacy preset instanced draw call. */
export interface TreeBatch {
  species: TreeSpecies;
  variant: number;
  castShadow: boolean;
  count: number;
  /** 3 floats per instance, world/scene space coordinates. */
  position: Float32Array;
  /** 1 float per instance: final uniform scale factor. */
  scale: Float32Array;
  /** 1 float per instance: yaw rotation in radians. */
  rotation: Float32Array;
  /** 3 floats per instance (RGB) when vertex coloring is active. */
  color?: Float32Array;
}

/** Flat, world-space instance data for an environment-biased grown tree draw call. */
export interface GrownTreeBatch {
  /** The biome key (replaces species as the primary aesthetic axis). */
  biome: string;
  variant: number;
  castShadow: boolean;
  count: number;
  /** 3 floats per instance, world/scene space coordinates. */
  position: Float32Array;
  /** 1 float per instance: final scale including per-variant measured botanical height. */
  scale: Float32Array;
  /** 1 float per instance: yaw rotation in radians. */
  rotation: Float32Array;
  /** 3 floats per instance (RGB) when vertex coloring is active. */
  color?: Float32Array;
}

/** Upper bound on legacy preset batches across all chunks. */
export const MAX_TREE_BATCHES = TREE_SPECIES.length * VARIANTS_PER_SPECIES * 2;

// ============================================================================
// INTERNAL ACCUMULATORS
// ============================================================================

interface Accumulator {
  species: TreeSpecies;
  variant: number;
  castShadow: boolean;
  position: number[];
  scale: number[];
  rotation: number[];
  color: number[];
  sawColor: boolean;
}

interface GrownAccumulator {
  biome: string;
  variant: number;
  castShadow: boolean;
  position: number[];
  scale: number[];
  rotation: number[];
  color: number[];
  sawColor: boolean;
}

// ============================================================================
// PRESET TREE BATCHING
// ============================================================================

/**
 * Merges per-chunk scatter data into world-space batches for preset tree rendering.
 *
 * @param inputs List of chunk scatter inputs with scene offsets
 * @returns Array of populated TreeBatch objects
 */
export function buildTreeBatches(inputs: readonly TreeBatchInput[]): TreeBatch[] {
  const accumulators = new Map<string, Accumulator>();
  const keyOf = (species: TreeSpecies, variant: number, castShadow: boolean) =>
    `${species}|${variant}|${castShadow ? 'near' : 'far'}`;

  // Pre-seed all possible species and variant combinations
  for (const species of TREE_SPECIES) {
    for (let v = 0; v < VARIANTS_PER_SPECIES; v++) {
      for (const castShadow of [true, false]) {
        accumulators.set(keyOf(species, v, castShadow), {
          species, variant: v, castShadow,
          position: [], scale: [], rotation: [], color: [], sawColor: false,
        });
      }
    }
  }

  for (const input of inputs) {
    const { scatter, offset, castShadow } = input;
    const baseHeightBySpecies = SPECIES_HEIGHT_M;
    for (const bucket of partitionTreeInstances(scatter)) {
      if (bucket.instanceIndices.length === 0) continue;
      const acc = accumulators.get(keyOf(bucket.species, bucket.variant, castShadow));
      if (!acc) continue;
      const baseH = baseHeightBySpecies[bucket.species];
      for (const i of bucket.instanceIndices) {
        acc.position.push(
          scatter.positions[i * 3] + offset[0],
          scatter.positions[i * 3 + 1] + offset[1],
          scatter.positions[i * 3 + 2] + offset[2],
        );
        acc.scale.push(scatter.scales[i] * baseH);
        acc.rotation.push(scatter.rotations[i]);
        if (scatter.colors) {
          acc.sawColor = true;
          acc.color.push(scatter.colors[i * 3], scatter.colors[i * 3 + 1], scatter.colors[i * 3 + 2]);
        } else {
          acc.color.push(0.35, 0.55, 0.3);
        }
      }
    }
  }

  const batches: TreeBatch[] = [];
  for (const acc of accumulators.values()) {
    const count = acc.scale.length;
    if (count === 0) continue;
    batches.push({
      species: acc.species,
      variant: acc.variant,
      castShadow: acc.castShadow,
      count,
      position: new Float32Array(acc.position),
      scale: new Float32Array(acc.scale),
      rotation: new Float32Array(acc.rotation),
      ...(acc.sawColor ? { color: new Float32Array(acc.color) } : {}),
    });
  }
  return batches;
}

/** Returns a stable React key for a preset batch. */
export const treeBatchKey = (b: TreeBatch): string =>
  `${b.species}|${b.variant}|${b.castShadow ? 'near' : 'far'}`;

// ============================================================================
// ENVIRONMENT-BIASED GROWN TREE BATCHING (PER-VARIANT HEIGHT SCALING)
// ============================================================================

/**
 * Merges per-chunk scatter data into world-space batches for environment-grown tree rendering.
 *
 * Each batch is scaled using the exact measured botanical height of that specific variant
 * (`grownTreeHeightM(biome, variant)`), ensuring dynamic, realistic heights.
 *
 * @param inputs List of chunk scatter inputs with scene offsets
 * @returns Array of populated GrownTreeBatch objects
 */
export function buildGrownTreeBatches(
  inputs: readonly TreeBatchInput[],
): GrownTreeBatch[] {
  const accumulators = new Map<string, GrownAccumulator>();
  const keyOf = (biome: string, variant: number, castShadow: boolean) =>
    `${biome}|${variant}|${castShadow ? 'near' : 'far'}`;

  for (const input of inputs) {
    const { scatter, offset, castShadow } = input;
    for (const bucket of partitionGrownTreeInstances(scatter)) {
      if (bucket.instanceIndices.length === 0) continue;
      const key = keyOf(bucket.biome, bucket.variant, castShadow);
      let acc = accumulators.get(key);
      if (!acc) {
        acc = {
          biome: bucket.biome, variant: bucket.variant, castShadow,
          position: [], scale: [], rotation: [], color: [], sawColor: false,
        };
        accumulators.set(key, acc);
      }

      // Look up the simulated botanical height for this specific variant
      const baseH = grownTreeHeightM(bucket.biome, bucket.variant);

      for (const i of bucket.instanceIndices) {
        acc.position.push(
          scatter.positions[i * 3] + offset[0],
          scatter.positions[i * 3 + 1] + offset[1],
          scatter.positions[i * 3 + 2] + offset[2],
        );
        // Multiply individual scatter scale factor by the variant's measured height
        acc.scale.push(scatter.scales[i] * baseH);
        acc.rotation.push(scatter.rotations[i]);
        if (scatter.colors) {
          acc.sawColor = true;
          acc.color.push(scatter.colors[i * 3], scatter.colors[i * 3 + 1], scatter.colors[i * 3 + 2]);
        } else {
          acc.color.push(0.35, 0.55, 0.3);
        }
      }
    }
  }

  const batches: GrownTreeBatch[] = [];
  for (const acc of accumulators.values()) {
    const count = acc.scale.length;
    if (count === 0) continue;
    batches.push({
      biome: acc.biome,
      variant: acc.variant,
      castShadow: acc.castShadow,
      count,
      position: new Float32Array(acc.position),
      scale: new Float32Array(acc.scale),
      rotation: new Float32Array(acc.rotation),
      ...(acc.sawColor ? { color: new Float32Array(acc.color) } : {}),
    });
  }
  return batches;
}

/** Returns a stable React key for a grown tree batch. */
export const grownTreeBatchKey = (b: GrownTreeBatch): string =>
  `${b.biome}|${b.variant}|${b.castShadow ? 'near' : 'far'}`;

/** Upper bound on grown batches for a given number of active biomes. */
export const maxGrownTreeBatches = (biomeCount: number): number =>
  biomeCount * GROWN_VARIANTS_PER_BIOME * 2;
