/**
 * Component inventory catalog for the Atomic Design System preview.
 *
 * PreviewComponents.tsx renders this catalog as the "Component Inventory" table:
 * every visible UI element with a stable id, its type, source location, purpose,
 * and known usage locations. Keeping the catalog here keeps the preview component
 * thin and lets the table data be reviewed or reused without touching the JSX.
 */

export type ComponentCatalogEntry = {
  id: string;
  name: string;
  type: string;
  location: string;
  purpose: string;
  notes?: string;
  usage?: string[];
};

export const COMPONENT_CATALOG: ComponentCatalogEntry[] = [
  {
    id: 'cmp-button',
    name: 'Button',
    type: 'Action',
    location: 'src/components/ui/Button.tsx',
    purpose: 'Primary call-to-action buttons and utility triggers.',
    notes: 'Variants: primary, secondary, action, success, danger, ghost.',
    usage: [
      'components/CharacterCreator/CharacterCreator.tsx',
      'components/CharacterCreator/Race/RaceSelection.tsx',
      'components/CharacterCreator/ui/CreationStepLayout.tsx',
      'components/DesignPreview/steps/PreviewComponents.tsx',
      'components/Organization/OrgMembersList.tsx',
      'components/Organization/OrgMissionsList.tsx',
      'components/Organization/OrgUpgradesList.tsx',
      'components/ui/ConfirmationModal.tsx',
    ],
  },
  {
    id: 'cmp-input',
    name: 'Input Primitives',
    type: 'Action',
    location: 'src/components/ui/Input.tsx',
    purpose: 'Standard glassmorphic inputs, textareas, selects, and checkbox elements.',
    notes: 'Components: Input, Checkbox, Select, TextArea.',
    usage: [
      'components/ui/OllamaDependencyModal.tsx',
      'components/ui/BanterInterruptUI.tsx',
      'components/DesignPreview/steps/PreviewComponents.tsx',
    ],
  },
  {
    id: 'cmp-selection-list',
    name: 'SelectionListItem',
    type: 'Selection',
    location: 'src/components/ui/SelectionList.tsx',
    purpose: 'Vertical list choices for step-based selection.',
    notes: 'Supports badges via rightContent.',
    usage: [
      'components/CharacterCreator/Class/ClassSelection.tsx',
      'components/DesignPreview/steps/PreviewComponents.tsx',
    ],
  },
  {
    id: 'cmp-selection-card',
    name: 'SelectionCard',
    type: 'Selection',
    location: 'src/components/ui/SelectionCard.tsx',
    purpose: 'Card-based selection option for richer choices.',
  },
  {
    id: 'cmp-wizard-stepper',
    name: 'WizardStepper',
    type: 'Navigation',
    location: 'src/components/ui/WizardStepper.tsx',
    purpose: 'Progress indicator for multi-step flows.',
  },
  {
    id: 'cmp-split-pane',
    name: 'SplitPaneLayout',
    type: 'Layout',
    location: 'src/components/ui/SplitPaneLayout.tsx',
    purpose: 'Two-column selection + preview layout.',
    usage: [
      'components/CharacterCreator/AbilityScoreAllocation.tsx',
      'components/CharacterCreator/BackgroundSelection.tsx',
      'components/CharacterCreator/Class/ClassSelection.tsx',
      'components/CharacterCreator/FeatSelection.tsx',
      'components/CharacterCreator/NameAndReview.tsx',
      'components/CharacterCreator/Race/RaceSelection.tsx',
      'components/CharacterCreator/SkillSelection.tsx',
      'components/DesignPreview/steps/PreviewComponents.tsx',
    ],
  },
  {
    id: 'cmp-window-frame',
    name: 'WindowFrame',
    type: 'Layout',
    location: 'src/components/ui/WindowFrame.tsx',
    purpose: 'Framed window shell with title bar.',
    usage: [
      'components/CharacterCreator/CharacterCreator.tsx',
      'components/CharacterSheet/CharacterSheetModal.tsx',
      'components/Combat/EncounterModal.tsx',
      'components/Crafting/AlchemyBenchPanel.tsx',
      'components/Crime/ThievesGuild/ThievesGuildInterface.tsx',
      'components/DesignPreview/DesignPreviewPage.tsx',
      'components/DesignPreview/steps/PreviewWindowFrame.tsx',
      'components/Glossary/Glossary.tsx',
      'components/MapPane.tsx',
      'components/Naval/ShipPane.tsx',
      'components/Party/PartyEditorModal.tsx',
      'components/Party/PartyOverlay.tsx',
      'components/Religion/TempleModal.tsx',
      'components/Trade/TradeRouteDashboard.tsx',
      'components/debug/GeminiLogViewer.tsx',
      'components/debug/NobleHouseList.tsx',
      'components/debug/NpcInteractionTestModal.tsx',
      'components/debug/UnifiedDebugLogViewer.tsx',
      'components/dice/DiceRollerModal.tsx',
      'components/puzzles/LockpickingModal.tsx',
      'components/ui/CollapsibleBanterPanel.tsx',
    ],
  },
  {
    id: 'cmp-resize-handles',
    name: 'ResizeHandles',
    type: 'Layout',
    location: 'src/components/ui/ResizeHandles.tsx',
    purpose: 'Drag handles for resizable panels.',
    usage: [
      'components/ui/WindowFrame.tsx',
    ],
  },
  {
    id: 'cmp-image-pane',
    name: 'ImagePane',
    type: 'Media',
    location: 'src/components/ui/ImagePane.tsx',
    purpose: 'Image display panel with framing (currently inactive).',
  },
  {
    id: 'cmp-typography',
    name: 'Typography',
    type: 'Text',
    location: 'src/components/ui/Typography.tsx',
    purpose: 'Text primitives: SectionTitle, SubsectionTitle, BodyText, Label, Description.',
    usage: [
      'components/CharacterCreator/AgeSelection.tsx',
      'components/DesignPreview/steps/PreviewComponents.tsx',
    ],
  },
  {
    id: 'cmp-table',
    name: 'Table',
    type: 'Data',
    location: 'src/components/ui/Table.tsx',
    purpose: 'Standardized table layout for structured data.',
    usage: [
      'components/DesignPreview/steps/PreviewComponents.tsx',
      'components/DesignPreview/steps/PreviewMissingIcons.tsx',
      'components/DesignPreview/steps/PreviewTables.tsx',
      'components/Glossary/GlossarySpellsOfTheMarkTable.tsx',
      'components/Glossary/GlossarySummaryTable.tsx',
      'components/Glossary/GlossaryTraitTable.tsx',
      'components/Naval/ShipPane.tsx',
    ],
  },
  {
    id: 'cmp-coin-display',
    name: 'CoinDisplay',
    type: 'Data',
    location: 'src/components/ui/CoinDisplay.tsx',
    purpose: 'Single currency value display.',
  },
  {
    id: 'cmp-coin-purse',
    name: 'CoinPurseDisplay',
    type: 'Data',
    location: 'src/components/ui/CoinPurseDisplay.tsx',
    purpose: 'Multi-currency breakdown display.',
    usage: [
      'components/CharacterSheet/Overview/InventoryList.tsx',
      'components/Trade/MerchantModal.tsx',
    ],
  },
  {
    id: 'cmp-time-widget',
    name: 'TimeWidget',
    type: 'Data',
    location: 'src/components/ui/TimeWidget.tsx',
    purpose: 'In-world time display widget.',
    usage: [
      'components/CompassPane/index.tsx',
    ],
  },
  {
    id: 'cmp-version-display',
    name: 'VersionDisplay',
    type: 'Data',
    location: 'src/components/ui/VersionDisplay.tsx',
    purpose: 'Build/version badge with custom styling.',
    notes: 'Styles: src/components/ui/VersionDisplay.css.',
    usage: [
      'components/layout/GameLayout.tsx',
      'components/layout/MainMenu.tsx',
    ],
  },
  {
    id: 'cmp-spinner',
    name: 'Spinner',
    type: 'Feedback',
    location: 'src/components/ui/Spinner.tsx',
    purpose: 'Inline loading indicator.',
    usage: [
      'components/ui/Button.tsx',
    ],
  },
  {
    id: 'cmp-loading-spinner',
    name: 'LoadingSpinner',
    type: 'Feedback',
    location: 'src/components/ui/LoadingSpinner.tsx',
    purpose: 'Full-screen or sectional loading state.',
    usage: [
      'App.tsx',
      'components/CharacterCreator/CharacterCreator.tsx',
      'components/Glossary/SingleGlossaryEntryModal.tsx',
      'components/layout/GameModals.tsx',
      'context/GlossaryContext.tsx',
      'context/SpellContext.tsx',
    ],
  },
  {
    id: 'cmp-error-overlay',
    name: 'ErrorOverlay',
    type: 'Feedback',
    location: 'src/components/ui/ErrorOverlay.tsx',
    purpose: 'Blocking error state overlay.',
    usage: [
      'context/GlossaryContext.tsx',
      'context/SpellContext.tsx',
    ],
  },
  {
    id: 'cmp-notification-system',
    name: 'NotificationSystem',
    type: 'Feedback',
    location: 'src/components/ui/NotificationSystem.tsx',
    purpose: 'Toast-style or persistent notifications.',
    usage: [
      'App.tsx',
    ],
  },
  {
    id: 'cmp-tooltip',
    name: 'Tooltip',
    type: 'Feedback',
    location: 'src/components/ui/Tooltip.tsx',
    purpose: 'Hover or focus explanations.',
    usage: [
      'components/BattleMap/AbilityButton.tsx',
      'components/BattleMap/ActionEconomyBar.tsx',
      'components/BattleMap/CharacterToken.tsx',
      'components/BattleMap/InitiativeTracker.tsx',
      'components/BattleMap/PartyDisplay.tsx',
      'components/CharacterCreator/Class/DruidFeatureSelection.tsx',
      'components/CharacterCreator/NameAndReview.tsx',
      'components/CharacterCreator/SkillSelection.tsx',
      'components/CharacterSheet/Overview/CharacterOverview.tsx',
      'components/CharacterSheet/Overview/EquipmentMannequin.tsx',
      'components/CharacterSheet/Overview/InventoryList.tsx',
      'components/CharacterSheet/Skills/SkillDetailDisplay.tsx',
      'components/CharacterSheet/Skills/SkillsTab.tsx',
      'components/Glossary/GlossaryTooltip.tsx',
      'components/Logbook/DiscoveryLogPane.tsx',
      'components/Party/PartyOverlay.tsx',
      'components/Party/PartyPane/PartyCharacterButton.tsx',
      'components/Party/PartyPane/PartyMemberCard.tsx',
      'components/Religion/TempleModal.tsx',
      'components/Tooltip.tsx',
      'components/Trade/MerchantModal.tsx',
      'components/ui/CoinDisplay.tsx',
      'components/ui/CoinPurseDisplay.tsx',
      'components/ui/TimeWidget.tsx',
      'components/ui/WindowFrame.tsx',
    ],
  },
  {
    id: 'cmp-confirmation-modal',
    name: 'ConfirmationModal',
    type: 'Modal',
    location: 'src/components/ui/ConfirmationModal.tsx',
    purpose: 'Confirm destructive or critical actions.',
    usage: [
      'components/SaveLoad/LoadGameModal.tsx',
      'components/SaveLoad/SaveSlotSelector.tsx',
    ],
  },
  {
    id: 'cmp-missing-choice-modal',
    name: 'MissingChoiceModal',
    type: 'Modal',
    location: 'src/components/ui/MissingChoiceModal.tsx',
    purpose: 'Warns about incomplete selections.',
  },
  {
    id: 'cmp-rest-modal',
    name: 'RestModal',
    type: 'Modal',
    location: 'src/components/ui/RestModal.tsx',
    purpose: 'Rest/short rest interaction modal.',
    usage: [
      'components/ActionPane/index.tsx',
    ],
  },
  {
    id: 'cmp-game-guide-modal',
    name: 'GameGuideModal',
    type: 'Modal',
    location: 'src/components/ui/GameGuideModal.tsx',
    purpose: 'In-app guide/help content.',
  },
  {
    id: 'cmp-image-modal',
    name: 'ImageModal',
    type: 'Modal',
    location: 'src/components/ui/ImageModal.tsx',
    purpose: 'Expanded image viewer.',
    usage: [
      'components/CharacterCreator/Race/RaceDetailModal.tsx',
      'components/CharacterCreator/Race/RaceDetailPane.tsx',
      'components/Glossary/GlossaryEntryTemplate.tsx',
      'components/ImageModal.tsx',
    ],
  },
  {
    id: 'cmp-ollama-modal',
    name: 'OllamaDependencyModal',
    type: 'Modal',
    location: 'src/components/ui/OllamaDependencyModal.tsx',
    purpose: 'Dependency/setup warning for Ollama.',
  },
  {
    id: 'cmp-banter-panel',
    name: 'CollapsibleBanterPanel',
    type: 'Narrative',
    location: 'src/components/ui/CollapsibleBanterPanel.tsx',
    purpose: 'Expandable narrative/log panel.',
    usage: [
      'App.tsx',
    ],
  },
  {
    id: 'cmp-banter-interrupt',
    name: 'BanterInterruptUI',
    type: 'Narrative',
    location: 'src/components/ui/BanterInterruptUI.tsx',
    purpose: 'Interrupt UI for banter scenes.',
  },
  {
    id: 'cmp-companion-card',
    name: 'CompanionCard',
    type: 'Character',
    location: 'src/components/ui/CompanionCard.tsx',
    purpose: 'Companion overview card.',
    usage: [
      'components/Party/RelationshipsPane.tsx',
    ],
  },
  {
    id: 'cmp-companion-reaction',
    name: 'CompanionReaction',
    type: 'Character',
    location: 'src/components/ui/CompanionReaction.tsx',
    purpose: 'Reaction or emotion indicator for companions.',
    usage: [
      'App.tsx',
    ],
  },
  {
    id: 'cmp-not-found',
    name: 'NotFound',
    type: 'System',
    location: 'src/components/ui/NotFound.tsx',
    purpose: '404 / missing route fallback.',
  },
];
