/**
 * @file src/systems/worldforge/bridge/__tests__/townEconomy.test.ts
 * ECON-WIRE-1 regression tests: town-claimed businesses participate in the
 * SAME NpcBusinessManager daily sim as other NPC-owned worldBusinesses.
 *
 * Key findings (see REPORT-ECON-WIRE-1.md):
 *   - worldReducer step 6b already iterates ALL worldBusinesses with
 *     ownerType === 'npc' through processAllNpcBusinesses.
 *   - Town businesses generated by World3DWrapper carry ownerType: 'npc'
 *     and a valid npcOwnerProfile, so they flow through for free.
 *
 * These tests PROVE the integration works and protect it against regressions:
 *   1. Pure helper unit tests (isTownClaimedBusiness, getTownBusinessKey, etc.)
 *   2. Daily-sim integration: a town business advanced N days earns/spends
 *   3. Bankruptcy path reachable for a town business
 *   4. Non-town businesses' golden daily behavior UNCHANGED
 *   5. worldReducer integration: ADVANCE_TIME processes town businesses
 */
export {};
