/**
 * @file src/systems/worldforge/bridge/__tests__/townEconomy.test.ts
 * ECON-WIRE-1 regression tests: town-claimed businesses participate in the
 * SAME NpcBusinessManager daily sim as other NPC-owned worldBusinesses.
 *
 * Key findings (see REPORT-ECON-WIRE-1.md):
 *   - worldReducer step 6b already iterates ALL worldBusinesses with
 *     ownerType === 'npc' through processAllNpcBusinesses.
 *   - Town businesses generated by World3DWrapper carry ownerType: 'npc'
 *     and a valid npcOwnerProfile, so they flow through for free.
 *
 * These tests PROVE the integration works and protect it against regressions:
 *   1. Pure helper unit tests (isTownClaimedBusiness, getTownBusinessKey, etc.)
 *   2. Daily-sim integration: a town business advanced N days earns/spends
 *   3. Bankruptcy path reachable for a town business
 *   4. Non-town businesses' golden daily behavior UNCHANGED
 *   5. worldReducer integration: ADVANCE_TIME processes town businesses
 */

import { describe, it, expect, vi } from 'vitest';
import {
    isTownClaimedBusiness,
    getTownBusinessKey,
    validateTownBusinessForDailySim,
    getTownBusinessLedger,
} from '../townEconomy';
import {
    generateNpcBusiness,
    processAllNpcBusinesses,
} from '../../../economy/NpcBusinessManager';
import { SeededRandom } from '../../../../utils/random/seededRandom';
import type { WorldBusiness } from '../../../../types/business';
import type { EconomyState } from '../../../../types/economy';
// worldReducer + factory for integration tests; vi.mock below is hoisted by vitest
import { worldReducer } from '../../../../state/reducers/worldReducer';
import { createMockGameState } from '../../../../utils/core/factories';

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const MINIMAL_NPC = {
    id: 'npc_test_keeper',
    name: 'Test Keeper',
    role: 'merchant',
    biography: { level: 5, classId: 'rogue' },
};

const STUB_ECONOMY: EconomyState = {
    tradeRoutes: [],
    regionalWealth: {},
    globalInflation: 0,
    activeEvents: [],
    marketEvents: [],
    marketFactors: { scarcity: [], surplus: [] },
    buyMultiplier: 1,
    sellMultiplier: 1,
} as unknown as EconomyState;

const STUB_FACTIONS = {};

/** Builds a town-claimed business deterministically from a seed. */
const makeTownBusiness = (seed: number, overrides: Partial<WorldBusiness> = {}): WorldBusiness => {
    const rng = new SeededRandom(seed);
    const biz = generateNpcBusiness(
        MINIMAL_NPC,
        'coord_5_5',
        'tavern',
        100,
        rng
    );
    // Apply town-claim markers (burgId + plotId) as World3DWrapper does
    biz.burgId = 7;
    biz.plotId = 3;
    biz.id = 'biz_burg_7_plot_3';
    biz.name = 'The Golden Test Tavern';
    biz.ownerId = 'npc_burg_7_plot_3';
    return { ...biz, ...overrides };
};

/** Builds a non-town NPC business (no burgId/plotId). */
const makeNonTownBusiness = (seed: number): WorldBusiness => {
    const rng = new SeededRandom(seed);
    const biz = generateNpcBusiness(
        { id: 'npc_plain', name: 'Plain Merchant', role: 'merchant', biography: { level: 3 } },
        'village-center',
        'general_store',
        100,
        rng
    );
    return biz;
};

// ---------------------------------------------------------------------------
// 1. Pure helper unit tests
// ---------------------------------------------------------------------------

describe('townEconomy — pure helpers', () => {
    it('isTownClaimedBusiness returns true for town businesses with burgId+plotId', () => {
        const biz = makeTownBusiness(42);
        expect(isTownClaimedBusiness(biz)).toBe(true);
    });

    it('isTownClaimedBusiness returns false for non-town businesses', () => {
        const biz = makeNonTownBusiness(42);
        expect(isTownClaimedBusiness(biz)).toBe(false);
    });

    it('isTownClaimedBusiness returns false when only one marker is present', () => {
        const biz = makeTownBusiness(42);
        expect(isTownClaimedBusiness({ ...biz, burgId: undefined })).toBe(false);
        expect(isTownClaimedBusiness({ ...biz, plotId: undefined })).toBe(false);
    });

    it('getTownBusinessKey returns stable { burgId, plotId } for town businesses', () => {
        const biz = makeTownBusiness(42);
        expect(getTownBusinessKey(biz)).toEqual({ burgId: 7, plotId: 3 });
    });

    it('getTownBusinessKey returns null for non-town businesses', () => {
        const biz = makeNonTownBusiness(42);
        expect(getTownBusinessKey(biz)).toBeNull();
    });

    it('validateTownBusinessForDailySim returns valid for a properly generated town business', () => {
        const biz = makeTownBusiness(42);
        const result = validateTownBusinessForDailySim(biz);
        expect(result.valid).toBe(true);
        expect(result.missing).toHaveLength(0);
    });

    it('validateTownBusinessForDailySim reports missing npcOwnerProfile', () => {
        const biz = makeTownBusiness(42);
        const broken = { ...biz, npcOwnerProfile: undefined };
        const result = validateTownBusinessForDailySim(broken);
        expect(result.valid).toBe(false);
        expect(result.missing).toContain('npcOwnerProfile');
    });

    it('validateTownBusinessForDailySim reports non-npc ownerType', () => {
        const biz = makeTownBusiness(42);
        const playerBiz = { ...biz, ownerType: 'player' as const };
        const result = validateTownBusinessForDailySim(playerBiz);
        expect(result.valid).toBe(false);
        expect(result.missing).toContain('ownerType must be "npc"');
    });

    it('validateTownBusinessForDailySim reports missing metrics fields', () => {
        const biz = makeTownBusiness(42);
        const broken = {
            ...biz,
            metrics: { ...biz.metrics, customerSatisfaction: undefined as unknown as number },
        };
        const result = validateTownBusinessForDailySim(broken);
        expect(result.valid).toBe(false);
        expect(result.missing).toContain('metrics.customerSatisfaction');
    });

    it('getTownBusinessLedger extracts the correct snapshot', () => {
        const biz = makeTownBusiness(42);
        const ledger = getTownBusinessLedger(biz);
        expect(ledger.id).toBe('biz_burg_7_plot_3');
        expect(ledger.name).toBe('The Golden Test Tavern');
        expect(ledger.burgId).toBe(7);
        expect(ledger.plotId).toBe(3);
        expect(ledger.ownerType).toBe('npc');
        expect(ledger.businessType).toBe('tavern');
        expect(typeof ledger.revenue).toBe('number');
        expect(typeof ledger.profit).toBe('number');
        expect(typeof ledger.financialPressure).toBe('number');
    });
});

// ---------------------------------------------------------------------------
// 2. Daily-sim integration: town business advanced N days earns/spends
// ---------------------------------------------------------------------------

describe('townEconomy — daily-sim integration (ECON-WIRE-1 proof)', () => {
    it('a generated town business advanced 7 days produces non-trivial book changes', () => {
        const biz = makeTownBusiness(12345);
        const initialReport = { ...biz.lastDailyReport };
        const initialMetrics = { ...biz.metrics };

        const rng = new SeededRandom(99999);
        const businesses: Record<string, WorldBusiness> = { [biz.id]: biz };

        // Advance 7 days
        let current = businesses;
        for (let day = 101; day <= 107; day++) {
            const result = processAllNpcBusinesses(current, STUB_ECONOMY, STUB_FACTIONS, day, rng);
            current = result.worldBusinesses;
        }

        const after = current[biz.id];
        expect(after).toBeDefined();

        // The books must have moved — revenue and costs are non-zero after sim
        expect(after.lastDailyReport.day).toBe(107);
        expect(after.lastDailyReport.revenue).not.toBe(initialReport.revenue);
        // Revenue should be positive for a functioning tavern
        expect(after.lastDailyReport.revenue).toBeGreaterThan(0);
        // Costs are the template base daily costs (always positive)
        expect(after.lastDailyReport.costs).toBeGreaterThan(0);

        // Metrics drift: at least one of reputation or satisfaction changed
        const metricsChanged =
            after.metrics.reputation !== initialMetrics.reputation ||
            after.metrics.customerSatisfaction !== initialMetrics.customerSatisfaction;
        expect(metricsChanged).toBe(true);
    });

    it('produces deterministic results for the same seed', () => {
        const runSim = () => {
            const biz = makeTownBusiness(55555);
            const rng = new SeededRandom(77777);
            let current: Record<string, WorldBusiness> = { [biz.id]: biz };
            for (let day = 101; day <= 103; day++) {
                const result = processAllNpcBusinesses(current, STUB_ECONOMY, STUB_FACTIONS, day, rng);
                current = result.worldBusinesses;
            }
            return current[biz.id];
        };

        const a = runSim();
        const b = runSim();
        expect(a.lastDailyReport).toEqual(b.lastDailyReport);
        expect(a.metrics).toEqual(b.metrics);
        expect(a.npcOwnerProfile).toEqual(b.npcOwnerProfile);
    });
});

// ---------------------------------------------------------------------------
// 3. Bankruptcy path reachable
// ---------------------------------------------------------------------------

describe('townEconomy — bankruptcy path', () => {
    it('a town business with sustained losses eventually closes (financialPressure > 90, daysUnprofitable >= 30)', () => {
        const biz = makeTownBusiness(42);

        // Force the business into near-bankruptcy state to test the path
        const stressed: WorldBusiness = {
            ...biz,
            npcOwnerProfile: {
                ...biz.npcOwnerProfile!,
                financialPressure: 91,
                daysUnprofitable: 30,
            },
            // Very high price multiplier ensures continued losses
            priceMultiplier: 3.0,
            metrics: {
                ...biz.metrics,
                customerSatisfaction: 5,
                reputation: 5,
            },
        };

        const rng = new SeededRandom(11111);
        const businesses: Record<string, WorldBusiness> = { [stressed.id]: stressed };

        // Process one more day — should trigger bankruptcy closure
        const result = processAllNpcBusinesses(businesses, STUB_ECONOMY, STUB_FACTIONS, 200, rng);

        // The business should be closed (removed from the record)
        expect(result.closedBusinessIds).toContain(stressed.id);
        expect(result.worldBusinesses[stressed.id]).toBeUndefined();
    });

    it('a healthy town business does NOT go bankrupt in normal conditions', () => {
        const biz = makeTownBusiness(42);
        const rng = new SeededRandom(22222);
        let current: Record<string, WorldBusiness> = { [biz.id]: biz };
        const closedIds: string[] = [];

        for (let day = 101; day <= 130; day++) {
            const result = processAllNpcBusinesses(current, STUB_ECONOMY, STUB_FACTIONS, day, rng);
            current = result.worldBusinesses;
            closedIds.push(...result.closedBusinessIds);
        }

        // A healthy tavern should survive 30 days without bankruptcy
        expect(closedIds).not.toContain(biz.id);
        expect(current[biz.id]).toBeDefined();
    });
});

// ---------------------------------------------------------------------------
// 4. Non-town businesses' golden daily behavior UNCHANGED
// ---------------------------------------------------------------------------

describe('townEconomy — non-town business golden behavior', () => {
    it('processAllNpcBusinesses produces identical results for a fixed set across repeated runs (determinism)', () => {
        const nonTown = makeNonTownBusiness(88888);
        const town = makeTownBusiness(44444);

        // Run the same mixed set twice with the same RNG seed
        const runMixed = () => {
            const rng = new SeededRandom(33333);
            let current: Record<string, WorldBusiness> = {
                [nonTown.id]: nonTown,
                [town.id]: town,
            };
            for (let day = 101; day <= 105; day++) {
                const result = processAllNpcBusinesses(current, STUB_ECONOMY, STUB_FACTIONS, day, rng);
                current = result.worldBusinesses;
            }
            return current[nonTown.id];
        };

        const run1 = runMixed();
        const run2 = runMixed();

        // Same input set + same seed → identical output (the core golden guarantee)
        expect(run1.lastDailyReport).toEqual(run2.lastDailyReport);
        expect(run1.metrics).toEqual(run2.metrics);
        expect(run1.npcOwnerProfile).toEqual(run2.npcOwnerProfile);
    });

    it('non-town businesses are passed through unchanged by processAllNpcBusinesses for player-owned entries', () => {
        // Player-owned businesses are explicitly passed through (not simulated)
        // by processAllNpcBusinesses. This golden behavior must hold.
        const playerBiz: WorldBusiness = {
            ...makeNonTownBusiness(55555),
            ownerType: 'player',
            id: 'biz_player_1',
        };

        const rng = new SeededRandom(66666);
        const businesses: Record<string, WorldBusiness> = { [playerBiz.id]: playerBiz };
        const result = processAllNpcBusinesses(businesses, STUB_ECONOMY, STUB_FACTIONS, 200, rng);

        // Player business should be completely unchanged
        expect(result.worldBusinesses[playerBiz.id]).toEqual(playerBiz);
    });
});

// ---------------------------------------------------------------------------
// 5. worldReducer integration: ADVANCE_TIME processes town businesses
// ---------------------------------------------------------------------------

// Mock WorldEventManager to avoid unrelated side-effects in the worldReducer
// integration tests. vi.mock is hoisted by vitest, so it applies to the static
// import of worldReducer above.
vi.mock('../../../world/WorldEventManager', () => ({
    processWorldEvents: vi.fn((state) => ({
        state: { ...state },
        logs: [],
    })),
}));

describe('townEconomy — worldReducer ADVANCE_TIME integration', () => {

    it('ADVANCE_TIME runs the daily sim on a town-claimed worldBusiness (step 6b)', () => {
        const gameTime = new Date('2024-06-01T12:00:00Z');
        const townBiz = makeTownBusiness(77777);

        const baseState = createMockGameState({
            gameTime,
            worldBusinesses: { [townBiz.id]: townBiz },
        });

        const action = {
            type: 'ADVANCE_TIME' as const,
            payload: { seconds: 86400 }, // 1 day
        };

        const result = worldReducer(baseState, action);

        // The town business must have been processed — lastDailyReport.day updated
        const afterBiz = result.worldBusinesses?.[townBiz.id];
        expect(afterBiz).toBeDefined();
        expect(afterBiz!.lastDailyReport.day).not.toBe(townBiz.lastDailyReport.day);
        // Revenue should be non-zero for a functioning tavern
        expect(afterBiz!.lastDailyReport.revenue).toBeGreaterThan(0);
    }, 15000);

    it('ADVANCE_TIME processes both town and non-town businesses in the same tick', () => {
        const gameTime = new Date('2024-06-01T12:00:00Z');
        const townBiz = makeTownBusiness(11111);
        const nonTownBiz = makeNonTownBusiness(22222);

        const baseState = createMockGameState({
            gameTime,
            worldBusinesses: {
                [townBiz.id]: townBiz,
                [nonTownBiz.id]: nonTownBiz,
            },
        });

        const action = {
            type: 'ADVANCE_TIME' as const,
            payload: { seconds: 86400 }, // 1 day
        };

        const result = worldReducer(baseState, action);

        const afterTown = result.worldBusinesses?.[townBiz.id];
        const afterNonTown = result.worldBusinesses?.[nonTownBiz.id];

        expect(afterTown).toBeDefined();
        expect(afterNonTown).toBeDefined();

        // Both businesses should have been processed
        expect(afterTown!.lastDailyReport.revenue).toBeGreaterThan(0);
        expect(afterNonTown!.lastDailyReport.revenue).toBeGreaterThan(0);
    });

    it('ADVANCE_TIME clears NPC businessId when a town business goes bankrupt', () => {
        const gameTime = new Date('2024-06-01T12:00:00Z');
        const townBiz = makeTownBusiness(33333);

        // Push the business to near-bankruptcy
        const stressedBiz: WorldBusiness = {
            ...townBiz,
            npcOwnerProfile: {
                ...townBiz.npcOwnerProfile!,
                financialPressure: 95,
                daysUnprofitable: 31,
            },
            priceMultiplier: 3.0,
            metrics: { ...townBiz.metrics, customerSatisfaction: 2, reputation: 2 },
        };

        // The NPC must exist in generatedNpcs with a businessId reference
        const npc = {
            id: stressedBiz.ownerId,
            name: 'Bankrupt Keeper',
            businessId: stressedBiz.id,
        } as unknown as import('../../../../types').RichNPC;

        const baseState = createMockGameState({
            gameTime,
            worldBusinesses: { [stressedBiz.id]: stressedBiz },
            generatedNpcs: { [npc.id]: npc },
        });

        const action = {
            type: 'ADVANCE_TIME' as const,
            payload: { seconds: 86400 }, // 1 day
        };

        const result = worldReducer(baseState, action);

        // The bankrupt business should be removed
        expect(result.worldBusinesses?.[stressedBiz.id]).toBeUndefined();
        // The NPC's businessId should be cleared
        const updatedNpc = result.generatedNpcs?.[npc.id];
        expect(updatedNpc?.businessId).toBeUndefined();
    });
});
