/**
 * GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by scripts/ingestMonsters.ts
 */
import { MonsterData } from '../types';
export declare const INGESTED_MONSTERS: Record<string, MonsterData>;
